Tencent/tdesign-miniprogram

src/side-bar/_example/base/index.js, src/side-bar/_example/custom/index.js, src/side-bar/_example/with-icon/index.js
- fix(SideBar): 修复示例初始化时定位不准确问题
=> fix(SideBar): fix inaccurate positioning when the page was init

src/slider/README.md, src/slider/props.ts, src/slider/slider.wxml, src/slider/slider.wxs, src/slider/type.ts
无
移除 colors 和 disabledColor，建议使用 CSS Variables 修改
- break(Slider): 移除 colors 和 disabledColor，建议使用 CSS Variables 修改
=> fix(slider): remove colors and disabledColor property

src/avatar-group/avatar-group.less, src/avatar-group/avatar-group.wxml, src/avatar/__test__/__snapshots__/index.test.js.snap, src/avatar/__test__/__virtualHostSnapshot__/index.test.js.snap, src/avatar/avatar.less, src/avatar/avatar.ts, src/avatar/avatar.wxml, src/avatar/avatar.wxs
- feat(AvatarGroup): 头像组中默认带边框
=> feat(AvatarGroup): add border style

src/dialog/index.ts
=> fix(dialog): resolve action tsd error and support buttonLayout (#1654)

src/badge/badge.less
fix #1601
- fix(Badge): 调整 display 使用 block 替换 inline-block 
=> fix(Cell): resolve demo problems

src/cascader/README.en-US.md, src/cascader/README.md, src/cascader/cascader.ts, src/cascader/cascader.wxml, src/cascader/type.ts
无
文档补充事件相关的信息
补充 close和 pick 事件
- fix(Cascader): 修复 pick 事件的参数
- feat(Cascader): 新增 close 事件
=> fix(cascader): resolve events

src/date-time-picker/README.en-US.md, src/date-time-picker/README.md, src/date-time-picker/__test__/__snapshots__/index.test.js.snap, src/date-time-picker/date-time-picker.ts, src/date-time-picker/date-time-picker.wxml, src/date-time-picker/type.ts, src/picker-item/type.ts, src/picker/README.en-US.md, src/picker/README.md, src/picker/picker.ts, src/picker/type.ts
fix #1602
piker 和 dateTimePicker 新增close事件
- feat(Picker): 新增 close 事件
- feat(DateTimePicker): 新增 close 事件
=> feat(picker): add close event

src/date-time-picker/README.md, src/loading/README.en-US.md, src/loading/README.md, src/message/message.ts
- fix(Message): 修复外部样式类 `t-class-link` 无效问题
=> fix(Message): fix t-class-link invalid

src/date-time-picker/README.md, src/footer/README.md, src/loading/README.en-US.md, src/loading/README.md
更新loading、date-time-picker 组件文档， 处理footer组件文档样式错误
=> fix: fix docs

src/cascader/cascader.wxml, src/dropdown-item/dropdown-item.wxml, src/tree-select/tree-select.wxml, src/upload/upload.json
无
修复 radio 和 checkbox 的 align 更名成 placement 之后，没有正确使用的问题
- fix(Cascader): 修复 radio 图标显示位置不正确的问题
- fix(DropdownMenu): 修复 radio 图标显示位置不正确的问题
- fix(TreeSelect): 修复 radio 图标显示位置不正确的问题
=> fix: resolve radio placement

package.json, src/button/__test__/__virtualHostSnapshot__/demo.test.js.snap, src/cell/__test__/__virtualHostSnapshot__/index.test.js.snap, src/collapse/__test__/__virtualHostSnapshot__/index.test.js.snap, src/date-time-picker/__test__/__virtualHostSnapshot__/index.test.js.snap, src/image-viewer/__test__/__virtualHostSnapshot__/index.test.js.snap, src/input/__test__/__snapshots__/index.test.js.snap, src/loading/__test__/__virtualHostSnapshot__/demo.test.js.snap, src/navbar/__test__/__virtualHostSnapshot__/demo.test.js.snap, src/radio/__test__/__virtualHostSnapshot__/demo.test.js.snap, src/rate/__test__/__virtualHostSnapshot__/demo.test.js.snap, src/toast/__test__/__virtualHostSnapshot__/demo.test.js.snap
背景：快照错误
描述： 补充 `npm run test:update`， 更新测试快照，commit 之前先执行该脚本，以确保当前快照为最新。(先快速简易处理，后续优化开启虚拟节点情况下的快照生成问题)
=> chore: add test:snap-update

src/action-sheet/action-sheet.ts
fix #1725 
fix #1724
无
- fix(ActionSheet): 修复点击报错的问题
=> fix(action-sheet): resolve click event

site/pages/used.vue, site/site.config.mjs, site/vite.config.ts
=> feat: update used page

src/swiper/swiper.less
解决方案：[参考自微信开放社区](https://developers.weixin.qq.com/community/develop/doc/00026658428810dd8c07c062556400?highLine=swiper%2520%25E5%259C%2586%25E8%25A7%2592)
- fix(Swiper): 修复在真机上圆角无效问题
=> fix(Swiper): resolve border radius invalid

src/navbar/README.en-US.md, src/navbar/README.md, src/navbar/__test__/__snapshots__/index.test.js.snap, src/navbar/navbar.wxml
fix #1727
无
- fix(NavBar): 修复外部样式类不可用的问题
=> fix(navbar): resolve extenal class

src/footer/README.en-US.md, src/footer/README.md
fix #1719
- fix(Footer): 补齐 API 文档描述
=> docs(Footer): update docs

src/checkbox/__test__/__virtualHostSnapshot__/demo.test.js.snap, src/common/template/image.wxml, src/navbar/__test__/__virtualHostSnapshot__/index.test.js.snap, src/radio/__test__/__virtualHostSnapshot__/demo.test.js.snap
fix #1731 
- fix(Swiper): 修复基础调试库低于2.19.2时，图片不显示问题
=> fix(Swiper): the image is disappears when the version is lower than 2.19.2

src/checkbox/__test__/__virtualHostSnapshot__/demo.test.js.snap, src/input/README.md, src/input/__test__/__snapshots__/index.test.js.snap, src/input/__test__/__virtualHostSnapshot__/index.test.js.snap, src/input/__test__/index.test.js, src/input/input.wxml, src/input/props.ts, src/input/type.ts, src/radio/__test__/__virtualHostSnapshot__/demo.test.js.snap
fix #1730 
fix #1702 
- fix(Input): 修复 `maxLength` 无效问题，并将默认值变更为 -1
- fix(Input): 修复键盘弹起时，点击 clear 没反应的问题
=> fix(Input): resolve maxLength invalid

src/dropdown-item/dropdown-item.ts, src/dropdown-item/dropdown-item.wxml, src/dropdown-menu/dropdown-menu.ts
fix #1682 
修复 label 的展示逻辑，radio 图标的展示位置
- fix(DropdownMenu): 修复 label 的展示逻辑
- fix(DropdownMenu): 修复 radio 图标的展示位置
=> fix(dropdown-menu): resolve label and radio icon placement

src/calendar/__test__/__snapshots__/index.test.js.snap, src/calendar/__test__/__virtualHostSnapshot__/index.test.js.snap, src/date-time-picker/__test__/__snapshots__/index.test.js.snap, src/date-time-picker/__test__/__virtualHostSnapshot__/index.test.js.snap, src/dialog/__test__/__snapshots__/index.test.js.snap, src/dialog/__test__/__virtualHostSnapshot__/index.test.js.snap, src/picker/__test__/__snapshots__/index.test.js.snap, src/picker/__test__/__virtualHostSnapshot__/index.test.js.snap, src/popup/popup.wxml
修复popup组件close按钮层级过低无法点击问题
- fix(Popup): 修复关闭按钮无法点击的问题
=> fix(popup): resolve close can not tap

src/calendar/calendar.ts
无
使 format 属性变成响应式
- fix(Calendar): 修复 format 属性不是响应式的问题
=> fix(calendar): resolve format property reactive

src/checkbox-group/checkbox-group.ts
fix #1531
- fix(Checkbox): 修复存在 disabled 选项时，全选出错的问题
=> fix(checkbox): resolve check all when some is diabled

src/badge/badge.less, src/badge/badge.wxml
fix #1543
修复 color 属性
- fix(Badge): 修复 shape = ribbon 时，修改 color 不能改变全部颜色的问题
=> fix(badge): resolve color property

src/cell/cell.less
fix #1768 
- fix(Cell): 修复 `note` 内容超出被遮挡问题
=> fix(Cell): resolve the incomplete display of note content

src/progress/progress.wxml
fix #1770 
- fix(Progress): 修复 label 插槽无效
=> fix(Progress): resolve slot invalid when label is true

src/grid-item/grid-item.wxml, src/grid/README.md
无
修复 grid-item 的 image 插槽无法使用的问题。
但需要给 grid-item 赋值 slot 字符串
- fix(Grid): 修复 grid-item 的 image 插槽不可用的问题，需传入 image =  'slot' 才可使用插槽
=> fix(grid): resolve image slot

src/textarea/textarea.less
fix #1773 
- fix(Textarea): 修复 `autosize` 为 `true` 时，`placeholder` 上移问题
=> fix(Textarea): resolve the style problem when autosize is true

src/avatar/__test__/__virtualHostSnapshot__/index.test.js.snap, src/calendar/__test__/__virtualHostSnapshot__/index.test.js.snap, src/cell/__test__/__virtualHostSnapshot__/index.test.js.snap, src/collapse/__test__/__virtualHostSnapshot__/index.test.js.snap, src/count-down/__test__/__virtualHostSnapshot__/index.test.js.snap, src/date-time-picker/__test__/__virtualHostSnapshot__/index.test.js.snap, src/dialog/__test__/__virtualHostSnapshot__/index.test.js.snap, src/divider/__test__/__virtualHostSnapshot__/index.test.js.snap, src/footer/__test__/__virtualHostSnapshot__/index.test.js.snap, src/image-viewer/__test__/__virtualHostSnapshot__/index.test.js.snap, src/image/__test__/__virtualHostSnapshot__/index.test.js.snap, src/input/__test__/__virtualHostSnapshot__/index.test.js.snap, src/message/__test__/__virtualHostSnapshot__/index.test.js.snap, src/navbar/__test__/__virtualHostSnapshot__/index.test.js.snap, src/notice-bar/__test__/__virtualHostSnapshot__/index.test.js.snap, src/overlay/__test__/__virtualHostSnapshot__/index.test.js.snap, src/picker/__test__/__virtualHostSnapshot__/index.test.js.snap, src/search/__test__/__virtualHostSnapshot__/index.test.js.snap, src/skeleton/__test__/__virtualHostSnapshot__/index.test.js.snap, src/stepper/__test__/__virtualHostSnapshot__/index.test.js.snap, src/switch/__test__/__virtualHostSnapshot__/index.test.js.snap, src/textarea/__test__/__virtualHostSnapshot__/index.test.js.snap, src/upload/upload.ts, src/upload/upload.wxml
fix #1778 
fix(Upload): 修复点击事件失效的问题
=> fix(upload): 修复upload点击事件失效问题

src/switch/__test__/__snapshots__/demo.test.js.snap, src/switch/__test__/index.test.js, src/switch/_example/label/index.wxml, src/switch/switch.wxml
无
修复 label 和 icon 渲染顺序错误的问题
- fix(Switch): 修复 label 和 icon 渲染顺序错误的问题
=> fix(switch): resolve label and icon

src/loading/loading.wxml
fix #1777 
修复 style 出现 false 这样的 boolean 导致 wxs 报错
- fix(Loading): 修复错误的 style 导致 wxs 报错
=> fix(loading): resolve style error

src/radio/props.ts, src/radio/radio.ts, src/radio/radio.wxml
fix #1786
处理 radio-group 和 radio 的同名属性 placement 优先级问题
- fix(Radio): 修复 placement 优先级的问题
=> fix(radio): resolve placement

src/button/button.ts
fix #1784 
解决多个插槽都当成默认插槽的问题
- fix(Button): 解决多个插槽的渲染问题
=> fix(button): resolve multiple slot

src/avatar/__test__/__virtualHostSnapshot__/index.test.js.snap, src/calendar/__test__/__virtualHostSnapshot__/index.test.js.snap, src/cell/__test__/__virtualHostSnapshot__/index.test.js.snap, src/collapse/__test__/__virtualHostSnapshot__/index.test.js.snap, src/count-down/__test__/__virtualHostSnapshot__/index.test.js.snap, src/date-time-picker/__test__/__virtualHostSnapshot__/index.test.js.snap, src/dialog/__test__/__virtualHostSnapshot__/index.test.js.snap, src/divider/__test__/__virtualHostSnapshot__/index.test.js.snap, src/footer/__test__/__virtualHostSnapshot__/index.test.js.snap, src/image-viewer/__test__/__virtualHostSnapshot__/index.test.js.snap, src/image/__test__/__virtualHostSnapshot__/index.test.js.snap, src/input/__test__/__virtualHostSnapshot__/index.test.js.snap, src/message/__test__/__virtualHostSnapshot__/index.test.js.snap, src/navbar/__test__/__virtualHostSnapshot__/index.test.js.snap, src/notice-bar/__test__/__virtualHostSnapshot__/index.test.js.snap, src/overlay/__test__/__virtualHostSnapshot__/index.test.js.snap, src/picker/__test__/__virtualHostSnapshot__/index.test.js.snap, src/search/__test__/__virtualHostSnapshot__/index.test.js.snap, src/skeleton/__test__/__virtualHostSnapshot__/index.test.js.snap, src/stepper/__test__/__virtualHostSnapshot__/index.test.js.snap, src/switch/__test__/__virtualHostSnapshot__/index.test.js.snap, src/textarea/__test__/__virtualHostSnapshot__/index.test.js.snap, src/upload/upload.ts
fix #1779
fix: #1779
fix(Upload): 修复 limit 限制的问题
=> fix(upload): 修复limit限制的问题

src/grid-item/grid-item.ts, src/link/link.ts, src/tab-panel/tab-panel.ts
无
解决 multipleSlots 未开启的问题
- fix(Link): 解决多个插槽无法渲染的问题
- fix(TabPanel): 解决多个插槽无法渲染的问题
=> fix: resolve multiple slots

src/search/README.md, src/search/props.ts, src/search/search.wxml, src/search/type.ts
add type prop to input component
fix #1793
https://github.com/Tencent/tdesign-miniprogram/issues/1793
将type透传至search中的input，并更新文档
- feat(Search):  新增 type 属性透传至 input，默认为 text
=> feat(search): add type prop to input component

src/notice-bar/notice-bar.less
fix #1820 
- fix(NoticeBar): 修复二轮滚动初始位置不正确
=> fix(NoticeBar): resolve scroll

src/pull-down-refresh/props.ts, src/pull-down-refresh/pull-down-refresh.ts
add default value to loading-texts
fix #1806
add default value to loading-texts
- fix(PullDownRefresh): 修复 loading-texts 默认值缺失的问题
=> feat(pulldownrefresh): add default value to loading-texts

src/pull-down-refresh/pull-down-refresh.ts
无
无
- fix(PullDownRefresh): 解决外部样式类 t-class-text 拼写错误的问题
=> fix(pulldown-refresh): resolve external class

src/grid-item/grid-item.wxml
fix #1829 
无
- fix(Grid): 修复 t-class-image 无法赋予 image 样式的问题
=> fix(grid): resolve image class

src/tab-panel/tab-panel.less, src/tab-panel/tab-panel.wxml, src/tabs/README.md, src/tabs/tabs.ts
fix #1823 
fix #1815 
fix #1798
修复 theme != 'line' 的时候，获取 track 报错的问题
修复设置 animation 导致 panel 内容无法切换的问题
- fix(Tabs): 修复设置 animation 导致 panel 内容无法切换的问题
- fix(Tabs): 修复 theme 不等于 line 时，获取 track 报错的问题
=> fix(tabs): resolve animation and uncaught error

src/tab-panel/tab-panel.ts, src/tab-panel/tab-panel.wxml
无
修复内容重叠的问题
- fix(Tabs): 解决问题重叠的问题
=> fix(tabs): resolve content overlay

src/drawer/drawer.wxml
fix #1831
- fix(Drawer): 修复 destroyOnClose 属性不生效 
=> fix(drawer): resolve destroyOnClose error

src/radio/radio.less, src/radio/radio.wxml
fix #1799 
移除多余的空隙，完善 CSS Variables
- fix(Radio): 优化样式，新增 CSS Variables 控制文字激活态颜色
=> fix(radio): resolve style

src/divider/divider.less
变量控制分割线的样式。
- feat(Divider): 新增 CSS Variables 用于控制线条样式
=> feat: 支持分割线组件的线条使用变量控制属性

src/action-sheet/show.ts
fix #1898
- fix(ActionSheet): 解决 show 方法的 TS 报错
=> fix(action-sheet): resolve ts error of show method

src/radio/radio.less, src/radio/radio.wxml
fix #1857
无
- fix(Radio): 修复图标尺寸无法调整的问题
=> Bitjian fix/radio icon size

src/upload/upload.ts
无
修复 max 计算错误的问题
- fix(Upload): 修复 max 属性相关的问题
=> fix(upload): resolve max

src/navbar/navbar.less
#1622
修复胶囊边框层级过高，遮挡内容点击事件的问题
- fix(NavBar): 修复胶囊边框层级过高，遮挡内容点击事件的问题
=> fix(navbar): resolve capsule zindex

src/button/button.less, src/button/button.wxml
fix #1718 
- fix(Button): 修复 variant=outline 状态下 loading 不展示的问题
=> fix(button): 修复variant=outline等状态下loading不展示

src/dropdown-item/dropdown-item.less, src/dropdown-item/dropdown-item.wxml
fix #1303
临时支持下 radio 的多列模式，样式可能不直观
- fix(DropdownMenu): 修复单选情况下无法使用多列的问题
=> fix(dropdown-menu): support multiple column radio

src/calendar/calendar.ts, src/common/shared/calendar/index.ts
无
解决异步赋值的问题，将 this.base 的赋值改动 created 生命周期里，保证运行其他函数前先赋值。
- fix(Calendar): 修复 format 报错的问题
=> fix(calendar): resolve error

src/tab-panel/tab-panel.less, src/tabs/__test__/__snapshots__/demo.test.js.snap, src/tabs/_example/with-content/index.js, src/tabs/_example/with-content/index.wxml, src/tabs/_example/with-content/index.wxss, src/tabs/tabs.less, src/tabs/tabs.ts, src/tabs/tabs.wxml
- [x 日常 bug 修复
fix #1932
- 修复带内容的示例
- 移除冗余的样式
- 增加新的外部样式类 t-class-content
- feat(Tabs): 新增外部样式类 `t-class-content`
=> fix(tabs): resolve content overflow

src/link/__test__/__snapshots__/demo.test.js.snap, src/link/__test__/__virtualHostSnapshot__/demo.test.js.snap, src/link/_example/content/index.js, src/link/_example/content/index.wxml, src/link/link.ts, src/link/link.wxml, src/link/props.ts, src/link/type.ts
- Break(Link): 移除 navigator 组件相关改用 view 实现，navigatorProps 属性类型出现不兼容变更 
=> refactor(Link): implementation based on view

src/input/input.less
fix #1918 
背景：
修改后：
- fix(Input): 修复垂直布局时样式错误
=> fix(Input): resolve vertical layout style error

src/collapse-panel/collapse-panel.wxml, src/collapse-panel/props.ts, src/collapse-panel/type.ts, src/collapse/README.en-US.md, src/collapse/README.md, src/collapse/props.ts, src/collapse/type.ts
fix #1916
增加 headerLeftIcon 支持标题左侧传入图标
- feat(CollapsePanel): 新增 headerLeftIcon 属性，支持面板头左侧使用图标
=> feat(collapse): add header-left-icon property

src/slider/slider.ts, src/slider/slider.wxml
无
修复 dragstart、dragend 事件没反应的问题
- fix(Slider): 修复 dragstart、dragend 事件没反应的问题
=> fix(slider): enable dragstart and dragend event

CHANGELOG.md, src/swiper-nav/type.ts, src/swiper/README.en-US.md, src/swiper/README.md, src/swiper/type.ts
- feat(Swiper): 更新 swiper 组件 API 文档
=> feat(Swiper): update api docs

src/picker/picker.ts
fix #1885
解决使用 falsy 值导致无法正确选择的问题
- fix(Picker): 解决使用 falsy 值导致无法正确选择的问题
=> fix(picker): enable to using falsy value

src/toast/toast.ts
fix #1921
当出现 Toast 的页面隐藏的时候，自动隐藏当前 Toast
- fix(Toast): 页面隐藏的时候自动关闭
=> fix(toast): auto hide when page is hide

src/common/template/image.wxml, src/swiper/README.md, src/swiper/__test__/__snapshots__/demo.test.js.snap, src/swiper/_example/base/index.js, src/swiper/_example/base/index.wxml, src/swiper/swiper.ts, src/swiper/swiper.wxml
fix #1872 
无
- feat(Swiper): 新增 image-load 事件
=> feat(swiper): add image-load event

src/pull-down-refresh/README.en-US.md, src/pull-down-refresh/README.md, src/pull-down-refresh/__test__/index.test.js, src/pull-down-refresh/_example/base/index.js, src/pull-down-refresh/_example/base/index.wxml, src/pull-down-refresh/props.ts, src/pull-down-refresh/pull-down-refresh.ts, src/pull-down-refresh/pull-down-refresh.wxml, src/pull-down-refresh/type.ts
fix #1954 
fix #1801
支持透传更多属性至 scroll-view 组件，
- feat(PulldownRefresh): 支持透传更多属性至 scroll-view 组件
=> feat(pulldown-refresh): add some properties from scroll-view

src/pull-down-refresh/_example/base/index.js, src/pull-down-refresh/pull-down-refresh.ts
fix #1667 
无
- fix(PulldownRefresh): 解决 value = true 时无法触发加载状态的问题
=> fix(pulldown-refresh): resolve value

src/dropdown-menu/dropdown-menu.less
fix #1599
新增 CSS Variable
- feat(DropdownMenu): 新增 CSS Variable 用于调整边框宽度
=> feat(dropdown-menu): add css variable for border width

src/stepper/stepper.ts
fix #1970 
- fix(Stepper): 修复无法输入空值的问题
=> feat(Stepper): allow input to be empty

src/calendar/calendar.ts
fix #1541
解决不使用 popup 时，没有自动定位到当前值的问题
- fix(Calendar): 解决 usePopup = false 时，没有自动定位到当前值的问题
=> fix(calendar): enable scroll into view when use-popup is false

src/action-sheet/action-sheet.ts, src/dropdown-menu/_example/single/index.js, src/image-viewer/__test__/__snapshots__/demo.test.js.snap, src/image-viewer/_example/base/index.js, src/image-viewer/_example/base/index.wxml, src/image-viewer/_example/delete/index.js, src/image-viewer/_example/delete/index.json, src/image-viewer/_example/delete/index.wxml, src/image-viewer/_example/image-viewer.wxml, src/image-viewer/image-viewer.json
fix #1398
优化示例
- fix(ActionSheet): 修复使用命令行方式点击取消按钮无法关闭的问题
=> chore(image-viewer): update demo

src/navbar/navbar.wxml
=> fix(navbar): Fix invalid fixed attribute of Navbar component

src/dropdown-item/dropdown-item.less, src/dropdown-item/dropdown-item.ts, src/dropdown-item/dropdown-item.wxml
fix #1788 
再次打开选项自动滚动到选中位置
- feat(DropdownMenu): 选项过多时自动滚动到已选项
=> fix(DropdownMenu): auto scroll to current (#1788)

src/date-time-picker/date-time-picker.wxml, src/date-time-picker/props.ts, src/date-time-picker/type.ts
1. 支持时间日期选择插件可以修改蒙层
- feat(DateTimePikcer): 新增支持 popupProps 属性
=> feat: 添加支持date-picker的蒙层属性透

src/image-viewer/__test__/__virtualHostSnapshot__/demo.test.js.snap, src/slider/__test__/__snapshots__/demo.test.js.snap, src/slider/__test__/__virtualHostSnapshot__/demo.test.js.snap, src/slider/__test__/index.test.js, src/slider/_example/base/index.js, src/slider/_example/base/index.wxml, src/slider/slider.ts, src/slider/tool.ts
背景： step 属性支持小数
- feat(Slider): 属性 `step` 支持传入小数
- fix(Slider): 修复 change 事件重复触发相同值的问题
=> feat(Slider): the step attribute supports decimals

src/grid/README.md, src/grid/__test__/__snapshots__/demo.test.js.snap, src/grid/__test__/__virtualHostSnapshot__/demo.test.js.snap, src/grid/_example/grid.ts, src/grid/_example/icon-grid/index.js, src/grid/_example/icon-grid/index.json, src/grid/_example/icon-grid/index.wxml, src/grid/_example/icon-grid/index.wxss
=> feat(Grid): enrich demo

src/input/input.less
- fix(Input): 修复 label 为英文时无法换行
=> feat(Input): resolve label content wraps

src/button/button.ts
fix: 修复动态改button的variant无效bug.
- fix(Button): 修复 variant 无法动态响应的问题
=> fix: 修复动态改button的variant无效bug.

src/action-sheet/action-sheet.ts, src/action-sheet/action-sheet.wxml, src/action-sheet/props.ts, src/action-sheet/type.ts
1. action-sheet支持层级
- feat(ActionSheet): 新增 PopupProps 属性，透传至 Popup
=> feat: action-sheet支持层级

src/dialog/dialog.ts, src/dialog/dialog.wxml
=> fix(dialog): display of cancel and confirm button when calling a command.

src/calendar/calendar.ts
fix #2001
修复 calendar 类型失效的问题
- fix(Calendar): 修复 type 属性失效的问题
=> fix(calendar): enable calendar type

src/action-sheet/index.ts
背景： 引入报错
解决： 
不再直接导出组件实例
- fix(ActionSheet): 解决 ActionSheet 引入报错
=> chore(ActionSheet): prohibit exporting components at index

src/action-sheet/action-sheet.less
1. action-sheet支持cancel的颜色变量
- feat(ActionSheet): 新增 CSS Variable 用于控制取消按钮颜色
=> feat: action-sheet支持cancel的颜色变量

src/sticky/sticky.less
fix #2006
sticky 在锁定的情况下，宽度计算错误
- fix(Sticky): 处理在锁定的情况下，宽度计算错误的问题
=> fix(sticky): resolve width

src/side-bar-item/side-bar-item.less
fix #2010
- fix(SideBarItem): 修复选中态样式问题
=> fix(side-bar-item): fix prefix and suffix style anomalies

src/tab-bar-item/tab-bar-item.less
fix #1776
fix #2009
修正 virtualHost 不可用时的宽度
- fix(TabBar): 修正 virtualHost 不可用时的宽度
=> fix(tabbar): resolve width when virtual-host not available

babel.config.js, package.json
#2045 
如 issue
- fix: 修改并显示安装缺失依赖
=> fix: rename proposal to transform and display installation dependencies

src/calendar/__test__/__snapshots__/index.test.js.snap, src/calendar/__test__/__virtualHostSnapshot__/index.test.js.snap, src/date-time-picker/__test__/__snapshots__/index.test.js.snap, src/date-time-picker/__test__/__virtualHostSnapshot__/index.test.js.snap, src/dialog/__test__/__snapshots__/index.test.js.snap, src/dialog/__test__/__virtualHostSnapshot__/index.test.js.snap, src/dropdown-item/dropdown-item.wxml, src/dropdown-menu/__test__/__snapshots__/index.test.js.snap, src/dropdown-menu/__test__/__virtualHostSnapshot__/index.test.js.snap, src/dropdown-menu/__test__/index.test.js, src/picker/__test__/__snapshots__/index.test.js.snap, src/picker/__test__/__virtualHostSnapshot__/index.test.js.snap, src/popup/popup.wxml
- fix(DropdownMenu): 修复基础调试版本低于 2.19.2时无法使用的问题
=> fix(DropdownMenu): resolved the basic library cannot be used under version 2.19.2

src/navbar/navbar.less
fix #2048
无
- fix(NavBar): 修复背景色支持渐变色
=> fix(navbar): polish bg support

src/image/image.ts
fix #2037
修复 width、height 无法支持动态计算的问题
- fix(Image): 修复 width 和 height 无动态响应的问题
=> fix(image): enable dynamic dimension

src/icon/__test__/__snapshots__/demo.test.js.snap, src/icon/__test__/__virtualHostSnapshot__/demo.test.js.snap, src/icon/_example/data.js, src/icon/icon.less
fix #2072 
- fix(Icon): 修复命名错误的问题
=> fix(Icon): resolved icon naming error

src/tree-select/tree-select.ts, src/tree-select/tree-select.wxml
fix #2079
修复使用 keys 之后无法使用的问题
- fix(TreeSelect): 修复使用 keys 之后无法正常使用的问题
=> fix(tree-select): enable keys property

src/radio-group/radio-group.ts, src/radio-group/radio-group.wxml
fix #2078 
- fix(RadioGroup): 修复使用 options 时值为 falsy 时异常的问题
=> fix(radio-group): fix abnormal display of radio group selection status

src/cell-group/cell-group.wxml, src/cell/__test__/__snapshots__/index.test.js.snap, src/cell/__test__/__virtualHostSnapshot__/index.test.js.snap
fix #2088 
- fix(CellGroup): 修复 `bordered` 属性无效的问题
=> fix(CellGroup): resolved borderen invalid

src/grid-item/grid-item.less
fix #2102 
- fix(Grid): 修复 `align='left'` 无效的问题
=> fix(Grid): resolved align='left' valid

src/common/template/button.wxml
fix #2075
- fix(Fab): 修复 `buttonProps` 中的 `hoverClass`属性透传至 `button` 无效
=> fix(Fab): resolved hover-class invalid

src/notice-bar/README.en-US.md, src/notice-bar/README.md, src/notice-bar/__test__/__snapshots__/demo.test.js.snap, src/notice-bar/__test__/__virtualHostSnapshot__/demo.test.js.snap, src/notice-bar/_example/scrolling/index.wxml, src/notice-bar/notice-bar.wxml, src/notice-bar/props.ts, src/notice-bar/type.ts
- feat(notice-bar): add interval property when direction='vertical'
=> feat(notice-bar): add interval property when direction='vertical'

src/upload/__test__/index.test.js, src/upload/upload.ts
- fix #2071 
- fix(Upload): 修复图片尺寸超出的问题
=> fix(upload): fix abnormal image display

src/tab-panel/props.ts, src/tab-panel/type.ts, src/tabs/README.en-US.md, src/tabs/README.md, src/tabs/props.ts, src/tabs/tabs.less, src/tabs/tabs.wxml, src/tabs/type.ts
fix #2111
增加 split 属性
- feat(Tabs): 新增 split 属性
=> feat(tabs): add split property

src/slider/slider.ts
- fix #2109 
- fix(slider): fix abnormal calculation of slider mark
=> fix(slider): fix abnormal calculation of slider mark

src/input/input.ts
fix #2103 
- fix(Input): 修复 `type='number'` 时，`value=0` 无效的问题
=> fix(Input): resolve value=0 is valid when type is number

src/common/bus.ts, src/slider/README.md, src/slider/slider.ts
无
因为 slider 被 display: none 隐藏的时候，也会计算 DOM 的尺寸，导致刻度渲染错误。
因此优化代码，支持调用 `init` 函数重新渲染
- fix(Slider): 修复异步展示时导致刻度渲染错误的问题
=> fix(slider): enable async render

src/action-sheet/action-sheet.ts
无
修复 disabled 下的事件触发
- fix(ActionSheet): 修复点击 disabled 的选项仍触发 close、visible-change 事件
=> fix(action-sheet): do not trigger close event when disabled

src/stepper/stepper.ts
fix #2022
无
- fix(Stepper): 保证值发生变化才触发 change 事件
=> fix(stepper): trigger change when value changed

src/tabs/tabs.less
- fix #2122 
- fix(Tabs): 解决选项过多时样式错误的问题
=> fix(tabs): fix style anomalies caused by too many tabs items

src/picker/picker.ts
- fix #2105 
- fix(Picker): 修复默认值无效
=> fix(picker): fix default value is invalid

src/radio/radio.less
- fix #2017 
- fix(Radio): 修复自定义图标大小之后的垂直对齐问题
=> fix(radio): fix vertical align

src/checkbox/__test__/__snapshots__/demo.test.js.snap, src/checkbox/_example/base/index.wxml, src/checkbox/checkbox.less
无
无
- fix(Checkbox): 修复自定义图标尺寸后的垂直对齐问题
=> fix(checkbox): resolve align when icon size changed

src/checkbox-group/checkbox-group.ts, src/checkbox-group/checkbox-group.wxml, src/checkbox-group/props.ts, src/checkbox-group/type.ts, src/checkbox/README.en-US.md, src/checkbox/README.md, src/checkbox/checkbox.ts, src/checkbox/props.ts, src/checkbox/type.ts
fix #2134
无
- fix(CheckboxGroup): 修复使用 options 时，disabled 不生效的问题
- fix(Checkbox): 修复 disabled 优先级的问题
=> docs(checkbox): update

src/search/__test__/__snapshots__/index.test.js.snap, src/search/search.wxml
fix #2131 
无
- fix(Search): 截获点击 clear 触发的 tap 事件
=> fix(search): catch tap event when trigger clear

src/divider/__test__/__snapshots__/index.test.js.snap, src/divider/divider.wxml
fix #2129
调整外部样式类的位置
- fix(Divider): 修复外部样式类的位置
=> fix(divider): replace external class

src/toast/toast.ts
fix #2138 
无
- fix(Toast): 解决 close 事件重复触发
=> fix(toast): resolve repeated event triggering

src/dropdown-item/dropdown-item.ts, src/dropdown-menu/README.en-US.md, src/dropdown-menu/README.md
fix #2107
增加事件
- feat(DropdownItem): 新增 close 事件
=> feat(dropdown-item): add close event

src/popup/popup.less
fix #2151 
无
- fix(Popup): 修复底部弹出时的宽度问题
=> fix(popup): update width when placement is bottom

src/pull-down-refresh/props.ts, src/pull-down-refresh/pull-down-refresh.wxml, src/pull-down-refresh/type.ts
- feat(PullDownRefresh): 增加 show-scrollbar 属性
=> feat(pull-down-refresh): 增加show-scrollbar参数

src/picker/picker.ts
- fix #2160 
无
- fix(DateTimePicker): 修复无法选择的问题
=> fix(picker): observe value

src/tabs/tabs.ts, src/tabs/tabs.wxml
fix #2165
无
- fix(Tabs): 修复超出时滚动不流畅的问题
=> fix(tabs): enable scroll smoothly

src/button/README.md, src/divider/README.md, src/grid/README.md
- site: API文档新增 `externalClass` 内容
=> docs: add external-class content

src/action-sheet/action-sheet.wxml, src/action-sheet/props.ts, src/action-sheet/type.ts
- fix #2189 
无
- feat(ActionSheet): 支持show-overlay属性
=> feat(action-sheet): support the show-overlay property

src/toast/index.ts
- fix #2190 
无
- fix(Toast): 修复close方法类型声明错误
=> fix(toast): fix type error in the close method of toast

src/action-sheet/README.en-US.md, src/action-sheet/README.md
无
无
- docs(ActionSheet): 新增 show-overlay 属性
=> docs(action-sheet): enable show-overlay

src/picker-item/picker-item.ts, src/picker/picker.ts
- fix #1983 
- fix #2183 
无
- fix(picker): column index is always zero
=> fix(picker): column index is always zero

src/action-sheet/_example/align/index.js, src/action-sheet/action-sheet.less, src/action-sheet/template/list.wxml, src/action-sheet/type.ts
fix #2016
增加后置插槽
- feat(ActionSheet): 新增 suffixIcon，仅在 `theme = list` 时展示
=> feat(action-sheet): support suffix icon for list type

src/common/bus.ts
fix #2199
无
- fix(Slider): 修复无法滑动的问题
=> fix: resolve slider render

src/tree-select/tree-select.less, src/tree-select/tree-select.wxml
- feat(TreeSelect):  `label` 内容支持文本超长省略
=> feat(TreeSelect): support label super long ellipsis

src/indexes/indexes.ts, src/mixins/page-scroll.ts, src/sticky/sticky.ts
fix #2213
当组件销毁时，正常移除滚动函数
- fix(Sticky): 当组件销毁时，正常移除滚动函数
=> fix: enable remove scroller when component detached

src/common/utils.wxs
=> fix: resolve grammar problem

src/link/README.md
https://github.com/Tencent/tdesign-miniprogram/issues/2222
- docs(link): 补充使用说明，修复文档中句号导致的链接跳转错误
=> docs(link): 补充使用说明，修复文档中句号导致的链接跳转错误

src/dialog/_example/button/index.js, src/fab/__test__/__snapshots__/demo.test.js.snap, src/fab/_example/advance/index.js, src/fab/_example/advance/index.wxml
无
https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/getRealtimePhoneNumber.html
- fix: 因能力收费，移除 getphonenumber 相关示例
=> chore: remove getphonenumber on demo

src/swipe-cell/swipe-cell.ts
fix #2238
无
- fix(SwipeCell): 修复 left、right 没有动态响应的问题
=> fix(swipe-cell): enable dynaimc props

src/dropdown-menu/README.en-US.md, src/dropdown-menu/README.md, src/dropdown-menu/__test__/__snapshots__/index.test.js.snap, src/dropdown-menu/dropdown-menu.ts, src/dropdown-menu/dropdown-menu.wxml, src/dropdown-menu/props.ts, src/dropdown-menu/type.ts
fix #2232
无
- fix(DropdownMenu): 支持自定义箭头图标
=> feat(dropdown-menu): support custom icon for arrow

src/swiper/__test__/__snapshots__/demo.test.js.snap, src/swiper/_example/vertical/index.wxml, src/swiper/_example/vertical/index.wxss, src/swiper/swiper.less
- fix(Swiper): 修复图片加载中/加载错误占位符未居中的问题
- other(Swiper): 修复示例错误
=> fix(Swiper): resolved loading style

src/tab-bar/README.md
fix #2255 
- fix(TabBar): 修复示例代码展示错误
=> fix(TabBar): resolved demo code error

src/grid-item/grid-item.less
- fix #2250 
无
- fix(GridItem): 修复无效的css变量
=> fix(grid-item): invalid less variables

package.json
- docs(Icon): 更新图标展示UI组件至 0.2.0 版本
=> chore: upgrade icon-view component

src/dropdown-menu/__test__/__snapshots__/index.test.js.snap, src/radio/radio.ts
fix #2266
避免多次setdata导致重复渲染
- fix(Radio): 修复调整 placement 之后的渲染抖动的问题
=> fix(radio): avoid unnecessary render

src/swipe-cell/swipe-cell.wxs
fix #2276
无
- fix(SwipeCell): 阻止默认的垂直滚动，优化交互体验
=> fix(swipe-cell): prevent default scroll

src/collapse-panel/collapse-panel.ts, src/collapse/__test__/__snapshots__/index.test.js.snap, src/collapse/collapse.ts
fix #2267 
修复默认展开全部时，无法正常收起的问题
- fix(Collapse): 修复默认展开全部时，无法正常收起的问题
=> fix(collapse): enable expand all

src/checkbox/checkbox.wxml
fix #2261 
无
- fix(Checkbox): 修复 icon 无法使用插槽的问题
=> fix(checkbox): enable icon using slot

src/cell-group/cell-group.ts
- fix(CellGroup): 修复 `updateLastChid` 事件被多次触发的问题
=> fix(CellGroup): resolved updateLastChid is triggered multiple times

src/popup/popup.ts
- fix(Popup): 修复 `visibleChange` 事件参数错误的问题
=> fix(Popup): resolved visibleChange event parameter error

src/rate/rate.wxs
无
无
- fix(rate): when value = 0, default-value != 0, allow-half = true, the effect is abnormal
=> fix(rate): when value = 0, default-value != 0, allow-half = true, the effect is abnormal

src/stepper/__test__/__snapshots__/index.test.js.snap, src/stepper/__test__/index.test.js, src/stepper/stepper.ts, src/stepper/stepper.wxml
fix #2263
无
- fix(Stepper): 修复无法输出小数的问题
- fix(Stepper): 修复输入小数后增减的精度问题
=> fix(stepper): enable input decimal number

src/tree-select/tree-select.ts
fix #2312
fix #2313
无
- fix(TreeSelect): 解决异步 options 导致无法渲染的问题
- fix(TreeSelect): 解决异步数据导致的报错问题
=> fix(tree-select): resolve async options

src/action-sheet/action-sheet.json
- fix #2317 
无
- fix(ActionSheet): 移除未使用的组件
=> fix(action-sheet): remove unused component

src/button/props.ts, src/button/type.ts
- fix #2336 
无
- fix(Button): `t-id`属性没有默认值导致控制台警告问题
=> fix(button): no default value is set for t-id

src/calendar/__test__/__snapshots__/index.test.js.snap, src/common/template/button.wxml
#2341
- fix(Dialog): 修复隐私协议接口 bindagreeprivacyauthorization 回调信息丢失问题
=> fix(dialog): bindagreeprivacyauthorization callback information loss

src/image-viewer/image-viewer.less, src/image-viewer/image-viewer.wxml
【IssueShoot】[ImageViewer] 无障碍支持
fix #1062 
1.修复焦点穿透问题
2.图标按钮添加替代描述 (关闭按钮、删除按钮)
3.蒙层(支持点击关闭) 添加替代描述 (同“关闭按钮”)
feat(ImageViewer): 支持无障碍访问
=> feat(image-viewer): accessibility

src/input/README.md, src/link/README.md, src/notice-bar/README.md
=> docs: Remove extra symbols

src/checkbox/_example/special/index.json, src/radio/_example/special/index.json
- fix #2347 
- `Radio` 和 `Checkbox` 特殊演示示例中未引入 `t-icon` 组件
- fix: 更新`Radio` 和 `Checkbox` 特殊演示示例中未引入 `t-icon` 组件
=> fix: update example

README.md
=> docs: add qrcode

src/search/search.less
- fix #2339 
- 设置`input`最小高度为 48rpx
- fix(Search): `input` 未设置最小高度导致异常问题
=> fix(search): no minimum height is set for the input

src/picker/picker.ts
fix #2357 
- fix(Picker): 兼容 keys 为 null 的情况
=> fix(picker): props keys is unexpected

src/rate/README.en-US.md, src/rate/README.md, src/rate/props.ts, src/rate/rate.less, src/rate/rate.wxml, src/rate/type.ts
- fix #2286 
- feat(Rate): 新增 `placement` 属性
=> feat(rate): enable props placement

site/plugin-tdoc/component.vue
=> fix: resolved miniprogram-live src wrong

src/cell/README.en-US.md, src/cell/README.md, src/cell/cell.less, src/common/style/mixins/_hairline.less
fix #2385
- feat(Cell): 新增css变量 `--td-cell-border-width`
=> feat(cell): add css variable --td-cell-border-width

src/back-top/README.en-US.md, src/back-top/README.md, src/back-top/__test__/__snapshots__/demo.test.js.snap, src/back-top/_example/back-top.ts, src/back-top/_example/back-top.wxml, src/back-top/_example/base/index.js, src/back-top/_example/base/index.wxml, src/back-top/_example/half-round/index.js, src/back-top/_example/half-round/index.wxml, src/back-top/back-top.ts, src/back-top/back-top.wxml, src/back-top/props.ts, src/back-top/type.ts, src/pull-down-refresh/__test__/__snapshots__/demo.test.js.snap, src/pull-down-refresh/_example/base/index.js, src/pull-down-refresh/_example/base/index.wxml
fix #1604 
无
- feat(BackTop): 新增 `scrollTop` 和 `visibilityHeight` 属性
=> feat(back-top): enable property scroll-top and visibility-height

src/checkbox/checkbox.json
- 使用微信开发者工具代码质量扫描时会提示存在无使用的组件
- fix(Checkbox): 移除未使用的组件 `Cell`
=> fix(checkbox): 移除未使用的组件t-cell

src/radio/radio.json
- 使用微信开发者工具代码质量扫描时会提示存在无使用的组件
- fix(Radio): 移除未使用的组件 `Cell`
=> fix(radio): 移除未使用的组件t-cell

src/link/link.ts
https://github.com/Tencent/tdesign-miniprogram/issues/2222
- fix(link): 修复跳转方式为返回或退出时链接样式为禁用的问题
=> fix(link): 修复跳转方式为返回或退出时链接样式为禁用的问题

example/pages/home/home.json, example/pages/home/home.less, example/pages/home/home.ts, example/pages/home/home.wxml
=> fix(chore/trd-privacy): remove trd-privacy form home page

.husky/pre-commit
=> ci: add email check

src/cell/README.md, src/cell/__test__/__snapshots__/index.test.js.snap, src/cell/cell.ts, src/cell/cell.wxml, src/collapse/__test__/__snapshots__/index.test.js.snap
fix #2428 
- feat(Cell): 新增外部样式类 `t-class-center`
=> feat(Cell): add t-class-center

src/checkbox/checkbox.ts
fix #2400
[t-checkbox] 中的 checked 属性不生效，无法选中 #2400
- fix(Checkbox):  修复 `checked` 属性无效的问题
=> fix(checkbox.ts): 解决CheckBox组件checked属性无效问题

src/back-top/back-top.less
=> fix(back-top): 返回顶部按钮，增加 iphone 底部安全区 #2411

src/textarea/README.en-US.md, src/textarea/README.md, src/textarea/type.ts
- other(Textarea):  修复文档 ` confirm-type ` 属性默认值描述错误
=> docs(textarea): update the default value of confirm-type props

src/input/README.en-US.md, src/input/README.md, src/input/input.ts, src/input/input.wxml, src/input/props.ts, src/input/type.ts
fix #2369 
- feat(Input): 新增 `clearTrigger` 属性
=> feat(input): enable props clear-trigger

src/step-item/step-item.ts
fix #2479 
- fix(Step): 修复 `status` 属性变更后子项未及时更新的问题
=> perf(step-item): listen for change in status to update the node

src/grid-item/grid-item.less
fix #2501 
- fix(GridItem): 修复 `hover` 属性无效的问题
=> fix(grid-item): resolve the issue of ineffective click when hover is true

.github/issue-shoot.md
=> docs: IssueShoot.md add jarmywang

src/swiper/swiper.ts
#2502
需求背景：滑动时，current没有更新导致组件问题
解决方案：滑动后，在onChange事件内同步更新current
#2502
- fix(swiper): t-class-prev-image和t-class-next-image 无法动态变化问题修复
=> fix(swiper): t-class-prev-image和t-class-next-image 无法动态变化问题修复

src/calendar/calendar.ts
use-popup为false时,异步设置value,选择日期无法更新渲染
- fix(Calendar): 处理use-popup为false，动态设置value没重新渲染问题
=> fix(component): 动态更新calendar面板value值

src/fab/draggable/draggable.wxml
fix #2548
- fix(Fab): 修复滚动事件穿透的问题
=> fix(Fab): resolve scroll over throught

src/navbar/__test__/__snapshots__/index.test.js.snap, src/navbar/navbar.ts
fix #2543 
尺寸未适配原因为 `boxStyle`中使用的 px，应改用 rpx。
- fix(Navbar): 修复大屏适配问题
=> fix(Navbar): unit use rpx

src/dropdown-menu/__test__/__snapshots__/index.test.js.snap, src/tabs/tabs.ts
fix #2503
fix #2503 
- fix(Tabs): 修复最后一项 `disabled` 时卡死问题
=> fix(tabs): 修复最后一项disabled时卡死问题. (#2503)

src/action-sheet/README.en-US.md, src/action-sheet/README.md, src/action-sheet/props.ts, src/action-sheet/type.ts
=> feat(action-sheet): action-sheet api更新

src/action-sheet/README.md
- fix(ActionSheet):  修复示例文档缺失的问题
=> fix(ActionSheet): resolved doc error

src/search/search.wxml
fix #2568 
- fix(Search): 处理 `slot` 互斥问题
=> fix(search): slot mutually exclusive

src/notice-bar/type.ts
- other(NoticeBar): 声明 `NoticeBarTrigger` 类型
=> fix(notice-bar): declare the `NoticeBarTrigger` type

src/cascader/cascader.ts
fix #2577 
- fix(Cascader): 监听 `value` 值变化
=> fix(cascader): listening value

src/pull-down-refresh/pull-down-refresh.wxml
https://github.com/Tencent/tdesign-miniprogram/issues/2435
问题：scroll-view快速滚动的时候scrollTop不准
解决方案：scroll-view增加参数throttle="{{false}}"关闭事件派发的节流，自己实现节流
暂无
- fix(pull-down-refresh): scroll-view快速滚动的时候scrollTop不准
=> fix(pull-down-refresh): scroll-view快速滚动scrollTop不准确

src/tag/README.md, src/tag/__test__/index.test.js, src/tag/props.ts, src/tag/tag.ts, src/tag/tag.wxml, src/tag/type.ts
fix #1564
- feat(Tag):  `closable` 属性支持 `Object` 和 `Slot`类型
=> feat(Tag): closable attributes support object type

src/dialog/dialog.ts
fix #2585 
- fix(Dialog): 处理基础调试库无 `3.3.3` ～ `3.3.4` 版本时控制台报错
=> fix(Dialog): resolve error reported in base version 3.3.4 console

src/slider/README.md, src/slider/_example/label/index.wxss, src/slider/_example/slider.json, src/slider/_example/slider.wxml, src/slider/_example/step/index.wxss, src/slider/_example/vertical/index.js, src/slider/_example/vertical/index.json, src/slider/_example/vertical/index.wxml, src/slider/_example/vertical/index.wxss, src/slider/props.ts, src/slider/slider.less, src/slider/slider.ts, src/slider/slider.wxml, src/slider/type.ts
fix #2547
存在问题：slider不支持垂直方向的滑块
解决方案：slider增加`vertical`属性，支持垂直方向的滑块
实现方式：增添`vertical`属性，通过样式优先级控制滑块样式，在滑块初始化时判断是否为`vertical`，如果为`vertical`则进行垂直方向的计算，再拖动时也进行垂直方向的计算,实现垂直方向的滑块
https://github.com/Tencent/tdesign-miniprogram/assets/72006584/9e779d8d-99b1-4720-80eb-376019caf431
- feat(Slider): 新增加 `vertical`属性
=> Slider 支持 vertical 属性

src/swiper/swiper.ts, src/swiper/swiper.wxml
fix #2602 
- fix(Swiper): 意外的高频左右抖动
=> fix(swiper): unexpected high frequency left and right jitter

src/dialog/dialog.less, src/input/input.wxml, src/switch/switch.wxml
QQ小程序 input value无法加载
QQ小程序 switch 无法动态更新禁用态
QQ小程序 dialog 不支持两个按钮并存
将input的`model:value`改为`value`
将switch style里加入禁用态的判断 
```html
style="{{!disabled?bodyStyle:''}}"
```
- fix(input, switch, dialog): 修复QQ小程序部分问题
=> fix(input, switch, dialog): 修复QQ小程序部分问题

src/col/col.less, src/row/row.less
fix #2598
- fix(Layout): 改用 `flex` 布局，修复 `col` 高度塌陷问题
=> fix(layout): layout使用flex布局

src/slider/slider.ts
fix #2622
- fix(slider): 修复滑块点击偏移，点击位置定位不准确
=> fix(slider): 修复滑块点击偏移

src/tab-bar/tab-bar.less
=> style(tabbar): 移除重复样式类

src/fab/draggable/draggable.less, src/fab/draggable/draggable.wxml
fix #2620 
- fix(Fab): 修复拖拽模式点击不触发
=> fix(fab): 拖拽模式事件与页面事件冲突

src/dropdown-item/dropdown-item.less, src/dropdown-item/dropdown-item.wxml, src/dropdown-menu/__test__/__snapshots__/index.test.js.snap
- other(DropdownItem): 采用 [BEM](http://getbem.com/) 命名规范优化类名
=> perf(dropdown-item): optimized the class name

CHANGELOG.md, package.json
=> chore: publish v1.2.9

src/radio-group/radio-group.ts, src/radio/radio.ts, src/radio/radio.wxml
fix #2640 
- fix(RadioGroup): 修复 `disabled` 动态修改无效
=> fix(radio-group): dynamic modification of disabled attribute is invalid

src/pull-down-refresh/README.en-US.md, src/pull-down-refresh/README.md, src/pull-down-refresh/pull-down-refresh.wxml
fix #2651 
- feat(PullDownRefresh): 新增 `header` 插槽
=> feat(pull-down-refresh): add header slot

src/date-time-picker/README.en-US.md, src/date-time-picker/README.md, src/date-time-picker/date-time-picker.wxml, src/date-time-picker/props.ts, src/date-time-picker/type.ts, src/picker-item/type.ts, src/picker/README.en-US.md, src/picker/README.md, src/picker/picker.wxml, src/picker/props.ts, src/picker/type.ts, src/popup/index.ts
fix #2621
https://github.com/TDesignOteam/tdesign-api/pull/240
- feat(Picker): 新增 `footer` 插槽
- feat(DateTimePicker): 新增 `footer` 插槽
=> feat(Picker): add footer slot

src/checkbox-group/checkbox-group.ts, src/checkbox/checkbox.ts, src/checkbox/checkbox.wxml
fix #2646 
- fix(CheckboxGroup): 处理 `disabled` 动态修改无效的问题
=> fix(checkbox-group): dynamic modification of disabled attribute is invalid

src/footer/README.en-US.md, src/footer/README.md, src/footer/props.ts, src/footer/type.ts
https://github.com/TDesignOteam/tdesign-api/pull/256
=> feat(footer): sync api

src/result/README.en-US.md, src/result/README.md, src/result/props.ts, src/result/type.ts
https://github.com/TDesignOteam/tdesign-api/pull/262/
=> docs(result): sync api

src/slider/slider.less
fix #2689
- fix(Slider): 修复组件宽度失效
=> fix(Slider): resolved width invalid in t-cell

src/skeleton/__test__/index.test.js, src/skeleton/skeleton.ts, src/skeleton/skeleton.wxml
- feat(Skeleton): 新增 `delay` 属性
=> feat(Skeleton): support delay props

src/drawer/README.en-US.md, src/drawer/README.md, src/drawer/drawer.less
- fix(Drawer): 修复 `--td-drawer-item-icon-color` 名称错误
=> fix(Drawer): resolved css vars name error

src/tab-bar-item/tab-bar-item.less
fix #2694 
- fix(TabBarItem): 当 `tab-bar` 组件 `split` 属性为真时，样式异常
=> fix(tab-bar-item): when the split attribute is true, the style is abnormal

CHANGELOG.md, package.json
=> chore: publish v1.3.0

CHANGELOG.md
=> chore: 同步main的changelog.md，处理空格问题

src/common/utils.ts, src/message/__test__/__snapshots__/index.test.js.snap, src/message/message-item/message.wxs
- other(MessageItem): 逻辑容错异常处理
=> perf(message-item): logical fault tolerance exception handling

src/fab/__test__/__snapshots__/demo.test.js.snap, src/fab/_example/draggable/index.wxml, src/fab/fab.ts, src/mixins/using-custom-navbar.ts
- feat(Fab): 新增 `using-custom-navbar` 属性
=> feat(Fab): support using-custom-navbar props

package.json
=> chore: update package title

example/components/pull-down-list/index.less
- chore(PulDownList): 样式文件已在全局引入，避免重复引入
=> chore(PullDownList): using css token

src/input/input.ts
- feat(Input): 新增 `default-value` 属性
=> feat(input): enable props default-value

src/col/col.wxml, src/col/col.wxs, src/row/row.wxml, src/row/row.wxs
fix #2740 
- fix(Layout): 修复 `Col` 和 `Row` 的 `style` 与 `customStyle` 属性无效的问题
=> fix(Layout): resolved style invalid

src/textarea/textarea.ts
close #2736 
- feat(Textarea): 新增 `default-value` 属性
=> feat(textarea): enable props default-value

src/fab/README.md
=> fix(Fab): update docs

package.json
=> chore: publish v1.4.0

CHANGELOG.md
=> chore: update v1.4.0 CHANGELOG.md

CHANGELOG.md
=> chore: update v1.4.0 CHANGELOG.md (#2754)

src/count-down/README.md, src/count-down/count-down.less
- other(CountDown): 改用 `TCloudNumber` 字体
- [] 本条 PR 不需要纳入 Changelog
=> style(CountDown): using TCloudNumber font

src/date-time-picker/README.en-US.md, src/date-time-picker/README.md, src/date-time-picker/_example/date-time-picker.json, src/date-time-picker/_example/date-time-picker.wxml, src/date-time-picker/_example/without-popup/index.js, src/date-time-picker/_example/without-popup/index.json, src/date-time-picker/_example/without-popup/index.wxml, src/date-time-picker/date-time-picker.wxml, src/date-time-picker/props.ts, src/date-time-picker/type.ts, src/picker-item/type.ts, src/picker/README.en-US.md, src/picker/README.md, src/picker/_example/picker.json, src/picker/_example/picker.wxml, src/picker/_example/without-popup/index.js, src/picker/_example/without-popup/index.json, src/picker/_example/without-popup/index.wxml, src/picker/_example/without-popup/index.wxss, src/picker/picker.wxml, src/picker/props.ts, src/picker/template.wxml, src/picker/type.ts
fix #2746 
- feat(Picker): 新增 `use-popup` 属性
- feat(DateTimePicker): 新增 `use-popup` 属性
=> feat(Picker): support use-popup

src/calendar/calendar.json
fix #2756 
- fix(Calendar):  修复页面层无法修改组件样式的问题
=> chore(Calendar): supplement styleIsolation configuration

src/row/row.less
fix #2772 
- fix(Layout):  支持拆行
=> fix(Layout): support newline

example/app.json
=> chore: 示例skyline配置优化

src/picker-item/picker-item.less, src/picker/README.md
=> fix(Picker): fixed the problem that sub-items cannot be adapted

src/picker/template.wxml
=> fix(Picker): resolved wxs event

site/plugin-tdoc/component.vue
=> fix: 修复预览窗口内部切换时不更随颜色模式问题

src/icon/icon.ts
- perf(icon): set the size style
=> perf(icon): set the size style

src/cell-group/cell-group.less, src/cell/README.md, src/cell/__test__/__snapshots__/demo.test.js.snap, src/cell/_example/theme/index.wxml
- fix(CellGroup): 修复深色模式下外边框颜色错误
=> fix(CellGroup): resolved border color error in dark mode

package.json
=> chore: upgrade tdesign-site-components to 0.15.2

src/slider/slider.less
=> fix(Slider): optimize the vertical capsule sliding style

src/grid/_example/icon-grid/index.wxss, src/progress/progress.less, src/progress/progress.wxml, src/result/_example/result.wxml, src/sticky/__test__/__snapshots__/demo.test.js.snap, src/sticky/_example/container/index.json, src/sticky/_example/container/index.wxml, src/sticky/_example/container/index.wxss
- fix(Progress): 修复环状进度条深色模式颜色错误
=> fix(Progress): resolve circle type color error in dark mode

src/icon/__test__/index.test.js, src/icon/icon.less, src/icon/icon.ts
- fix(Icon): dynamically set image size
=> fix(icon): dynamically set image size

src/slider/__test__/__snapshots__/demo.test.js.snap, src/slider/_example/base/index.wxml, src/slider/_example/base/index.wxss, src/slider/_example/capsule/index.wxml, src/slider/_example/capsule/index.wxss, src/slider/_example/disabled/index.wxss, src/slider/_example/label/index.wxss, src/slider/_example/range/index.wxml, src/slider/_example/range/index.wxss, src/slider/_example/step/index.wxss
=> chore(slider): update slider demo padding

src/button/__test__/__snapshots__/demo.test.js.snap, src/button/_example/base/index.json, src/button/_example/base/index.wxss, src/button/_example/button.less, src/button/_example/disabled/index.wxss, src/button/_example/group-btn/index.wxss, src/button/_example/icon-btn/index.wxml, src/button/_example/icon-btn/index.wxss, src/button/_example/skyline/button.less, src/button/_example/theme/index.wxss
=> fix(Button): update demo style

src/progress/README.en-US.md, src/progress/README.md, src/progress/progress.less
=> feat(Progress): add some css variables

src/tab-bar-item/tab-bar-item.less, src/tab-bar-item/tab-bar-item.wxml
fix #2820
- fix(TabBar): 优化 `TabBarItem` 的 `icon` 插槽
=> fix(TabBar): fix icon slot invalid (#2820)

src/action-sheet/template/grid.wxml
fix #2837 
- fix(ActionSheet):  修复控制台告警
=> fix(ActionSheet): resolved console warning

src/tabs/tabs.less
from https://github.com/Tencent/tdesign-miniprogram/issues/1155#issuecomment-2148749442
- fix(Tabs): 部分 `css` 变量无效
=> fix(tabs): some css variables are invalid

package.json
=> chore: publish v1.4.2

src/swiper/swiper.less, src/swiper/swiper.wxml
- fix(Swiper): 修复slot=navigation无效问题
=> fix(Swiper): resolved navigation slot invalid

src/progress/__test__/__snapshots__/demo.test.js.snap, src/progress/_example/line/index.wxml, src/progress/_example/plump/index.wxml
=> feat(Progress): update demo

src/cascader/cascader.ts
fix #2848
fix #2840 
- fix(Cascader): 优化组件性能，支持4级地址
=> perf(cascader): 优化大数据表单

src/navbar/navbar.less
fix #2835 
+ Navbar占位符未明确box-sizing，被覆写时高度错误
+ 修复Navbar占位元素高度错误
- fix(Navbar): 修复占位区高度错误
=> fix(navbar): specified box-sizing for placeholder

src/radio/radio.less
fix #2863 
- fix(Radio): 修复禁用态样式错误
=> fix(Radio): fix disabled style error

src/common/common.ts, src/dialog/README.en-US.md, src/dialog/README.md, src/dialog/_example/command/index.js, src/dialog/props.ts, src/dialog/type.ts, src/overlay/README.en-US.md, src/overlay/README.md, src/overlay/overlay.ts, src/overlay/props.ts, src/overlay/type.ts, src/picker/__test__/__snapshots__/index.test.js.snap
fix #2869 
- fix(Dialog):  `close-on-overlay-click`属性默认值从 `undefined` 改为 `false`
=> fix(Dialog): resolved demo confirm event error

src/button/README.md
- other(Button): 支持示例代码导入开发者工具
=> chore(Button): support component sample code snippets

src/tabs/tabs.ts
fix #2850
- feat(TabPanel): 支持动态 `lable`
=> chore(Tabs): support dynamic label

CHANGELOG.md, package.json
=> chore: publish v1.4.3

src/dropdown-menu/_example/dropdown-menu.wxml, src/overlay/_example/overlay.wxml
=> fix: resolved example navbar title wrong

CHANGELOG.md, package.json
=> chore: publish v1.4.4

src/col/README.md, src/divider/README.md, src/fab/README.md, src/icon/README.md, src/link/README.md
- site(Divider): 支持示例代码导入开发者工具 
- site(Fab): 支持示例代码导入开发者工具 
- site(Icon): 支持示例代码导入开发者工具 
- site(Layout): 支持示例代码导入开发者工具 
- site(Link): 支持示例代码导入开发者工具 
=> feat: add some sample code snippets

src/progress/README.en-US.md, src/progress/README.md, src/progress/progress.less, src/progress/progress.wxml
fix #2901
- feat(Progress): circle theme 增加起始角度支持
=> feat(progress): circle theme add 'from' variables

src/drawer/README.md
fix #2892
- other(Drawer): 支持示例代码导入开发者工具
=> chore(Drawer): support component sample code snippets

src/tab-bar/README.md
fix #2900
TabBar 补充组件示例代码片段
- other(TabBar): 支持示例代码导入开发者工具
=> chore(tabbar): support component sample code snippets

src/navbar/README.md
fix #2896
- other(NavBar): 支持示例代码导入开发者工具
=> chore(NavBar): support component sample code snippets

.github/CODEOWNERS
=> chore: add reviewers

src/popup/popup.wxs
- fix(Popup): 修复右侧弹层未适配自定义标题栏高度
=> fix(popup): resolved right popup distanceTop is invalid

src/navbar/README.en-US.md, src/navbar/README.md, src/navbar/props.ts, src/navbar/type.ts
https://github.com/TDesignOteam/tdesign-api/pull/321
=> docs(Navbar): update api docs

script/test/setup.js, src/navbar/__test__/__snapshots__/index.test.js.snap, src/navbar/navbar.ts
- [ x ] 代码风格优化
- [ x ] Changelog 已提供或无须提供
=> chore(Navbar): simplify the code

script/test/setup.js, src/date-time-picker/__test__/__snapshots__/index.test.js.snap, src/date-time-picker/__test__/index.test.js, src/navbar/__test__/__snapshots__/index.test.js.snap, src/picker/__test__/__snapshots__/index.test.js.snap
=> test: mock getMenuButtonBoundingClientRect

CHANGELOG.md, package.json
=> chore: publish v1.4.5

.husky/prepare-commit-msg
win 系统和CI 环境跳过prepare-commit-msg
=> chore: update prepare-commit-msg

src/cell/README.md
=> docs(cell): update usingComponents

src/calendar/README.en-US.md, src/calendar/README.md, src/calendar/__test__/__snapshots__/index.test.js.snap, src/calendar/calendar.ts, src/calendar/props.ts, src/calendar/template.wxml
fix #2886 
- feat(Calendar):  新增 `scroll` 事件
=> feat(Calendar): add scroll event

src/rate/README.en-US.md, src/rate/README.md, src/rate/props.ts, src/rate/rate.wxml, src/rate/type.ts
fix #2978
###相关 PR
https://github.com/TDesignOteam/tdesign-api/pull/332
- feat(Rate): `placement` 属性可选项新增 `''`，表示不显示评分弹窗
=> feat(Rate): placement attribute optionally adds empty string

src/cell-group/cell-group.ts
fix #2976
- fix(Cell): 修复动态添加 `cell` 时底部 `border` 不显示的问题
=> fix(Cell): fixed dynamic adding cells not showing border

src/button/button.less
fix #2933 
- fix(Button): 修复`skyline`渲染模式下 `hover` 态失效
=> fix(Button): resolved hover invalid in skyline

package.json
```bash
[10:35:31] Finished 'dist:json' after 914 ms
error TS2688: Cannot find type definition file for 'node'.
The file is in the program because:
Entry point of type library 'node' specified in compilerOptions
src/toast/toast.ts(12,14): error TS2503: Cannot find namespace 'NodeJS'.
src/toast/toast.ts(12,14): error TS4081: Exported type alias 'Timer' has or is using private name 'NodeJS'.
```
=> chore: fix ts error

src/grid/grid.ts
close #2988 
- fix(Grid): 监听数据变化后未更新子组件样式
=> fix(grid): subcomponent style is not updated after monitoring data changes

src/side-bar/_example/base/index.wxml, src/side-bar/_example/custom/index.wxml, src/side-bar/_example/switch/index.wxml, src/side-bar/_example/with-icon/index.wxml, src/tab-bar-item/tab-bar-item.wxml, src/tab-bar/_example/base/index.wxml, src/tab-bar/_example/custom/index.wxml, src/tab-bar/_example/icon-only/index.wxml, src/tab-bar/_example/round/index.wxml, src/tab-bar/_example/sub/index.wxml
fix #3001
- other(TabBarItem): `wx:key` 从 `index` 更换为`value`属性值作为标识符
=> fix(TabBar): resolved wx:key wrong

.github/ISSUE_TEMPLATE/bug-report.zh-CN.yml
=> chore: update issue template

src/input/input.less, src/input/input.wxml
fix #2996 
- fix(Input): 修复占位符禁用态样式错误
=> fix(Input): fix incorrect placeholder text style

src/indexes/__test__/__snapshots__/demo.test.js.snap, src/indexes/_example/custom/index.wxml, src/indexes/_example/custom/index.wxss, src/indexes/indexes.ts, src/indexes/indexes.wxml
fix #2985 
- fix(Indexes): 修复位置错乱和滑动卡顿
=> fix(Indexes): resolved the problem of position confusion and jamming

.husky/commit-msg, .husky/pre-commit
=> chore(husky): ci 环境跳过husky

CHANGELOG.md, package.json
=> chore: publish v1.5.0

src/input/README.en-US.md, src/input/README.md, src/input/input.less
fix #3016 
- feat(Input): 新增 `--td-input-placeholder-text-font-size` 变量
=> feat(input): enable --td-input-placeholder-text-font-size

src/search/README.md
from https://github.com/Tencent/tdesign-miniprogram/issues/2568#issuecomment-2240971189
- docs(Search): 补充说明 `left-icon` 属性
=> docs(search): add left-icon description

src/notice-bar/__test__/__snapshots__/demo.test.js.snap, src/notice-bar/_example/base/index.wxml, src/notice-bar/notice-bar.less
fix #3023 
- fix(NoticeBar): 修复 `content` 插槽内容的底边距异常
=> fix(NoticeBar): fix content slot occupancy abnormality

src/popup/_example/custom-close/index.json
[#3037](https://github.com/Tencent/tdesign-miniprogram/issues/3037)
补充 popup 官网 demo 中的 json 缺少合适的组件声明
- fix(组件名称): popup
=> fix-example-popup-demo-bug

src/message/__test__/__snapshots__/index.test.js.snap, src/message/message.ts, src/message/message.wxml
fix #3050
- fix(Message): 修复duration-end事件未回调
=> fix(Message): resolved duration-end event is invalid

src/message/__test__/__snapshots__/demo.test.js.snap, src/message/_example/base/index.js, src/message/_example/base/index.wxml, src/message/message.ts
fix #2983
- feat(Message): 支持组件调用
=> feat(message): 支持组件调用

src/pull-down-refresh/__test__/__snapshots__/demo.test.js.snap, src/pull-down-refresh/__test__/index.test.js, src/pull-down-refresh/_example/base/index.js, src/pull-down-refresh/_example/base/index.wxml, src/pull-down-refresh/pull-down-refresh.less, src/pull-down-refresh/pull-down-refresh.ts, src/pull-down-refresh/pull-down-refresh.wxml
fix #2854
- fix(PullDownRefresh): 修复 skyline 下提示语占位高度计算错误
=> fix(pull-down-refresh): fix refresh tip error

.github/CODEOWNERS
=> chore:Update CODEOWNERS

src/dialog/_example/command/index.js, src/dialog/dialog.ts
- fix(Dialog): 修复命令行调用closeOnOverlayClick无效问题
=> fix(Dialog): resolved closeOnOverlayClick is invalid in command

src/checkbox/README.en-US.md, src/checkbox/README.md, src/checkbox/checkbox.less
fix #3068
- fix(Checkbox): 修复选中态和未选中态直径/边长大小不一致问题
=> fix(Checkbox): fix border width error

src/dialog/index.ts
fix #3070 
- fix(Dialog): `close` 方法参数类型定义异常
=> fix(dialog): close method parameter type definition exception

src/loading/loading.less, src/picker/picker.less
fix #3072
skyline对rgba(255, 255, 255, 0)写法不支持，改成transparent
- fix(Picker): 兼容 `Skyline` 在深色模式下遮罩显示
=> fix(Picker): adapted skyline

site/docs/custom-style.md, src/picker/README.md
=> docs: fix syntax error in custom-style.md

src/badge/__test__/__snapshots__/demo.test.js.snap, src/badge/_example/base/index.wxml, src/badge/_example/theme/index.wxml, src/calendar/__test__/__snapshots__/index.test.js.snap, src/calendar/template.wxml, src/cascader/cascader.wxml, src/dialog/dialog.wxml, src/dropdown-menu/README.en-US.md, src/dropdown-menu/README.md, src/dropdown-menu/dropdown-menu.less, src/icon/__test__/__snapshots__/demo.test.js.snap, src/icon/_example/iconImage/index.wxml, src/navbar/__test__/__snapshots__/demo.test.js.snap, src/navbar/_example/back-home/index.wxml, src/popup/__test__/__snapshots__/demo.test.js.snap, src/popup/_example/custom-close/index.wxml, src/rate/__test__/__snapshots__/demo.test.js.snap, src/rate/_example/special/index.wxml, src/search/__test__/__snapshots__/index.test.js.snap, src/search/search.wxml, src/step-item/step-item.wxml, src/steps/__test__/__snapshots__/demo.test.js.snap, src/steps/_example/special/index.wxml, src/tab-bar-item/tab-bar-item.wxml, src/upload/upload.wxml
- feat(DropdownMenu): 新增 `--td-dropdown-menu-height`
=> fix(DropdownMenu): use rpx units

CHANGELOG.md, package.json
=> chore: publish v1.6.0

src/slider/README.en-US.md, src/slider/README.md, src/slider/__test__/__snapshots__/demo.test.js.snap, src/slider/_example/range/index.js, src/slider/_example/range/index.wxml, src/slider/props.ts, src/slider/slider.ts, src/slider/type.ts
fix #3082
api pr: https://github.com/TDesignOteam/tdesign-api/pull/402
- fix(Slider): dragend事件增加返回value
=> feat(Slider): dragend event add value parameter

src/image-viewer/image-viewer.ts
fix #3102
- fix(ImageViewer): 修复 `images` 长度更新导致 `index` 显示异常
=> fix(ImageViewer): fixed images length update causing index display exception

src/checkbox/_example/horizontal/index.wxss, src/checkbox/_example/special/index.wxss, src/radio/_example/horizontal/index.wxss, src/radio/_example/special/index.wxss
=> chore(demo): optimize css style

src/date-time-picker/__test__/__snapshots__/index.test.js.snap, src/picker-item/picker-item.ts, src/picker-item/picker-item.wxml, src/picker/__test__/__snapshots__/demo.test.js.snap, src/picker/__test__/__snapshots__/index.test.js.snap, src/picker/_example/base/index.js, src/picker/_example/base/index.json, src/picker/_example/base/index.wxml, src/picker/_example/base/index.wxss
fix #3053 
- feat(PickerItem): 支持插槽，自定义 `label` 后缀内容
=> feat(PickerItem): support slot

src/button/README.en-US.md, src/button/README.md, src/button/button.less
=> fix(Button): fix text button style error

src/button/README.en-US.md, src/button/README.md, src/button/props.ts, src/button/type.ts
=> fix(Button): customDataset attribute type changed to any

src/checkbox/checkbox.ts
fix #3156 
- fix(Checkbox): 修复 `change` 事件中参数缺失的问题
=> fix(checkbox): missing item parameter when triggering parent component update

src/dialog/dialog.ts
fix: #3177
- fix(Dialog): 修复更新按钮属性 openType 未重置问题
=> fix(Dialog): fixed update button attribute not reset opentype

src/tab-panel/tab-panel.ts, src/tabs/__test__/__snapshots__/demo.test.js.snap, src/tabs/_example/with-content/index.wxml, src/tabs/_example/with-content/index.wxss, src/tabs/tabs.ts
fix #3098
fix #3153
- fix(Tabs): 修复开启 animation 时导致的面板滚动位置不准确问题
=> fix(Tabs): fix scrolling issues caused when using animated

src/switch/switch.less
fix #3180
- fix(Switch): 修复深色模式下文本颜色错误
=> fix(Switch): fix design token error

src/button/button.ts, src/button/button.wxml, src/common/template/button.wxml
fix #3202 
- feat(Fab):  新增默认插槽
=> feat(Fab): add default slot

site/theme/dark.ts, src/back-top/back-top.less, src/badge/badge.less, src/button/button.less, src/calendar/calendar.less, src/check-tag/check-tag.less, src/common/style/theme/_dark.less, src/count-down/count-down.less, src/image-viewer/image-viewer.less, src/indexes/indexes.less, src/progress/progress.less, src/step-item/step-item.less, src/swiper-nav/swiper-nav.less, src/switch/switch.less, src/tag/tag.less, src/toast/toast.less, src/upload/upload.less
- 这是 https://github.com/Tencent/tdesign-miniprogram/pull/3200 的补充内容
> 改动点：@text-color-anti 深色模式值也使用 @font-white-1。@text-color-anti  与 @font-white-1 在使用效果上完全一致，描述上前者更语义化，因此组件内部改用 @text-color-anti
=> chore: use @text-color-anti var

src/dropdown-menu/__test__/__snapshots__/index.test.js.snap, src/upload/upload.less
fix #3218 
- fix(Upload): 修复 `loading` 内容未居中问题
=> fix(Loading): fix loading content is not centered

src/navbar/__test__/__snapshots__/demo.test.js.snap, src/navbar/__test__/__snapshots__/index.test.js.snap, src/navbar/__test__/index.test.js, src/navbar/_example/left-title/index.js, src/navbar/_example/left-title/index.wxml, src/navbar/navbar.less, src/navbar/navbar.ts
fix #3193
fix #3126
fix #2414
- fix(Navbar): 修复安卓中因精度带来的标题宽度计算错误，并优化标题左侧间距
=> fix(Navbar): fix width bug in Android

src/indexes/README.en-US.md, src/indexes/README.md, src/indexes/indexes.less, src/indexes/indexes.wxml, src/indexes/indexes.wxs
fix #3017
效果：
https://github.com/user-attachments/assets/cc56318b-e660-4e83-b209-b3220ded87cc
- feat(Indexeds): 优化交互样式，索引仅展示首字符，气泡支持展示索引内容
=> style: optimize component interaction style

example/project.config.json, src/cascader/README.en-US.md, src/cascader/README.md, src/cascader/cascader.ts
fix #2789
https://github.com/TDesignOteam/tdesign-api/pull/449
- feat(Cascader): `pick` 事件补充 `label` 参数
=> feat(Cascader): the pick event supplements the label parameter

CHANGELOG.md, package.json
=> chore: publish v1.7.0

src/calendar/__test__/__snapshots__/index.test.js.snap, src/icon/__test__/index.test.js, src/icon/icon.ts, src/search/__test__/__snapshots__/index.test.js.snap
fix #3226 
- fix(Icon): 修复动态计算图片高度异常
=> fix(icon): dynamically calculate the height of the image

src/action-sheet/action-sheet.wxml
fix #3227
- fix(ActionSheet): 为 `cancelText` 补充默认值
=> fix(ActionSheet): supplement default value for cancelText

src/date-time-picker/README.en-US.md, src/date-time-picker/README.md, src/date-time-picker/type.ts
- https://github.com/TDesignOteam/tdesign-api/pull/448
=> docs(date-time-picker): filter props add ts type

src/side-bar/__test__/__snapshots__/demo.test.js.snap, src/side-bar/_example/base/index.wxml, src/side-bar/_example/custom/index.wxml, src/side-bar/_example/switch/index.wxml, src/side-bar/_example/with-icon/index.wxml
fix #3250 
- fix(side-bar): update the example
=> fix(side-bar): update the example

src/rate/rate.ts, src/rate/rate.wxml
fix: #3262
gap类型为String / Number，但是设置为'100rpx'这样不生效，现在增加_gap处理此问题
=> fix(Rate): fixed gap unit error

src/button/button.less
- fix(Button): 修复 danger + disable 时，文本颜色错误
=> fix(Button): fix design token error

src/search/README.en-US.md, src/search/README.md, src/search/search.less, src/search/search.wxml
- fix(Search): 修复 `t-class-left` 无法修复图标尺寸的问题，并丰富 css var
=> chore(Search): enrich css vars

src/color-picker/README.en-US.md, src/color-picker/README.md, src/color-picker/__test__/__snapshots__/demo.test.js.snap, src/color-picker/_example/color-picker.json, src/color-picker/_example/color-picker.wxml, src/color-picker/_example/use-popup/index.js, src/color-picker/_example/use-popup/index.json, src/color-picker/_example/use-popup/index.wxml, src/color-picker/color-picker.json, src/color-picker/color-picker.ts, src/color-picker/color-picker.wxml, src/color-picker/interfaces.ts, src/color-picker/props.ts, src/color-picker/template.wxml, src/color-picker/type.ts, src/guide/__test__/__snapshots__/demo.test.js.snap, src/guide/__test__/demo.test.js
https://github.com/TDesignOteam/tdesign-api/pull/457
背景：ColorPicker在popup组件中，垂直方向位置计算错误
- feat(ColorPicker): 新增 `usePopup`、`visible`、`autoClose`、`style` 与 `customStyle` 等属性，新增 `close` 事件
=> feat(ColorPicker): support use-popup props

src/progress/progress.less
fix #3282
- fix(Progress): 修复在 `skyline` 中标签右侧间距错误
=> fix(Progress): adapt to skyline render

src/calendar/README.en-US.md, src/calendar/README.md, src/calendar/__test__/__snapshots__/demo.test.js.snap, src/calendar/__test__/__snapshots__/index.test.js.snap, src/calendar/__test__/demo.test.js, src/calendar/_example/calendar.json, src/calendar/_example/calendar.wxml, src/calendar/_example/local-text/index.js, src/calendar/_example/local-text/index.json, src/calendar/_example/local-text/index.wxml, src/calendar/calendar.ts, src/calendar/calendar.wxs, src/calendar/props.ts, src/calendar/template.wxml, src/calendar/type.ts, src/common/shared/calendar/index.ts
https://github.com/TDesignOteam/tdesign-api/pull/463
- feat(Calendar): 新增 `localText` 属性，支持组件国际化
=> feat(Calendar): support local-text props

CHANGELOG.md, package.json
=> chore: publish v1.8.0

src/progress/README.en-US.md, src/progress/README.md, src/progress/progress.less
fix #3296 
- feat(Progress): 新增环形进度条相关的  `css vars`
=> feat(progress): enable circle label css variable

src/sticky/sticky.wxml
=> perf(sticky): set the style

src/color-picker/README.en-US.md, src/color-picker/README.md, src/color-picker/color-picker.less, src/color-picker/color-picker.ts, src/color-picker/color-picker.wxml
fix #3290 
https://github.com/TDesignOteam/tdesign-api/pull/481
- feat(ColorPicker): 新增 `header` 和 `footer` 插槽，仅在 `usePopup` 为 `true` 时有效
=> feat(ColorPicker): add header and footer slots

src/dropdown-item/dropdown-item.less, src/dropdown-item/dropdown-item.ts, src/dropdown-item/dropdown-item.wxml, src/dropdown-menu/README.en-US.md, src/dropdown-menu/README.md, src/dropdown-menu/__test__/__snapshots__/index.test.js.snap
fix #3288 
fix #3307 
- fix(DropdownMenuItem): 修复默认插槽无效，并补充 `footer` 具名插槽
=> feat(DropdownMenuItem): support footer slot

src/tab-bar-item/tab-bar-item.less, src/tab-bar/__test__/__snapshots__/demo.test.js.snap, src/tab-bar/_example/badge/index.wxml, src/tab-bar/_example/badge/index.wxss, src/tab-bar/_example/sub/index.wxml, src/tab-bar/_example/tab-bar.wxml
fix #3337 
- fix(TabBar): 修复文本 + 徽标使用场景时，文本被挤压问题
=> fix(TabBar): set display to contents

example/pages/home/home.json, src/cell/_example/skyline/cell.json, src/cell/_example/skyline/cell.wxml, src/col/_example/skyline/col.json, src/col/_example/skyline/col.wxml, src/count-down/_example/skyline/count-down.json, src/count-down/_example/skyline/count-down.wxml, src/date-time-picker/_example/skyline/date-time-picker.json, src/date-time-picker/_example/skyline/date-time-picker.wxml, src/drawer/_example/skyline/drawer.json, src/drawer/_example/skyline/drawer.wxml, src/empty/_example/skyline/empty.json, src/empty/_example/skyline/empty.wxml, src/image-viewer/_example/skyline/image-viewer.json, src/image-viewer/_example/skyline/image-viewer.wxml, src/image/_example/skyline/image.json, src/image/_example/skyline/image.wxml, src/overlay/_example/skyline/overlay.json, src/overlay/_example/skyline/overlay.wxml, src/picker/_example/skyline/picker.json, src/picker/_example/skyline/picker.wxml, src/popup/_example/popup.json, src/popup/_example/skyline/popup.json, src/popup/_example/skyline/popup.wxml, src/skeleton/_example/skyline/skeleton.json, src/skeleton/_example/skyline/skeleton.wxml, src/swiper/_example/skyline/swiper.json, src/swiper/_example/skyline/swiper.wxml, src/tab-bar/_example/skyline/tab-bar.json, src/tab-bar/_example/tab-bar.json
- chore(example): enable scroll
=> chore(example): enable scroll

src/rate/rate.ts, src/rate/rate.wxml
fix #3270 
- fix(Rate): 修复禁用态下组件无法向上冒泡的问题
=> fix(Rate): support upward bubbling

src/picker/picker.less
fix #3316 
- fix(Picker): 在 `Skyline` 模式下样式异常
=> fix(picker): abnormal style in skyline mode

.github/workflows/pr-compressed-size.yml
更换回原版 `compressed-size-action` , 可避免多次评论消息骚扰
=> chore: compressed-size-action

site/pages/used.vue
- docs: fix used page font-color in dark mode
=> docs: fix dark mode font color

src/notice-bar/notice-bar.less, src/notice-bar/notice-bar.ts
#2993
复现代码片段（from @gangchn）： 
https://developers.weixin.qq.com/s/Xa6qbymc7yVS
- fix(NoticeBar): 修复重复进入页面时出现非预期动画
=> fix(NoticeBar): fix abnormal scrolling

src/calendar/README.md
=> docs(Calendar): update

src/dialog/index.ts
fix #3356
- fix(Dialog): 部分参数类型申明缺失
=> fix(dialog): some parameter type declarations are missing

src/icon/icon.ts
fix #3369
- fix(Icon): 补充异常捕获，修复开发工具控制台报错
=> fix(Icon): supplementary exception catching

src/guide/_example/guide.wxml, src/guide/content.wxml, src/guide/guide.less, src/guide/guide.ts, src/guide/guide.wxml
fix #3368 
- fix(Guide): 修复 `hideSkip` 属性无效
=> fix(Guide): fix the hideSkip attribute being invalid

src/calendar/README.en-US.md, src/calendar/README.md, src/calendar/__test__/__snapshots__/demo.test.js.snap, src/calendar/_example/switch-mode/index.js, src/calendar/_example/switch-mode/index.wxml, src/calendar/calendar.ts, src/calendar/props.ts, src/calendar/type.ts
fix #3378
fix #3380
- feat(Calendar): 新增 `panel-change`  事件，切换月或年时触发（`switch-mode` 不为 `none` 时有效）
=> feat(Calendar): support panel-change event

src/color-picker/color-picker.ts
fix #3384 
- fix(ColorPicker): 修复 `alpha` 滑轨精度丢失的问题
=> fix(color-picker): 修复 alpha 精度丢失问题

src/avatar/avatar.ts, src/avatar/avatar.wxml, src/avatar/avatar.wxs
fix #3375 
- feat(Avatar): `size` 属性支持 `rpx` 单位
=> feat(Avatar): the size attr supports rpx units

src/calendar/template.wxml
fix #3391 
fix #3345 
- fix(Calendar): 修复使用 `glass-easel` 渲染框架后，组件年月日起不显示
=> chore(Calendar): add a reference to the calendar.wxs file

src/message/message.interface.ts
fix #3409
- fix(Message): `link` 参数类型申明缺失的问题
=> fix(message): link parameter type declaration is missing

src/date-time-picker/__test__/__snapshots__/index.test.js.snap, src/picker-item/picker-item.less, src/picker-item/picker-item.wxml, src/picker/__test__/__snapshots__/index.test.js.snap
fix #3405
- fix(Picker): 修复 `PickerItem` 项 `label` 超出未省略问题
=> fix(PickerItem): optimize label text style

src/pull-down-refresh/__test__/__snapshots__/demo.test.js.snap, src/pull-down-refresh/__test__/__virtualHostSnapshot__/demo.test.js.snap, src/pull-down-refresh/_example/base/index.wxml, src/pull-down-refresh/_example/base/index.wxss, src/tabs/__test__/__snapshots__/demo.test.js.snap, src/tabs/_example/size/index.wxss, src/tabs/_example/theme/index.wxml, src/tabs/_example/with-content/index.wxml, src/tabs/_example/with-content/index.wxss, src/tabs/tabs.less, src/tabs/tabs.wxml
=> fix(Tabs): fix the badge activation color error

src/tab-bar/tab-bar.ts
- fix(TabBar): 修复子项数量大于 3 时子项未按预期调整内边距
=> fix(Tabbar): fix style error

src/search/README.en-US.md, src/search/README.md, src/search/props.ts, src/search/search.ts, src/search/search.wxml, src/search/type.ts
- feat(Search): 新增 `readonly` 和 `clearTrigger` 属性
=> feat(search): add readonly & clear-trigger props

src/calendar/_example/calendar.wxs
fix #3441
- fix(Calendar): 修复月份/日期前补 `0` 计算错误
=> fix(calendar): the example logic judgment is incorrect

src/guide/guide.ts
=> chore: supplementary content of pr 3416

src/image/image.ts
fix #3440
- fix(Image): 未正确触发组件数据更新的问题
=> fix(image): component data update is not triggered correctly

src/common/style/theme/_components.less, src/picker/picker.less
fix #3447
- fix(Picker): 规避 Skyline render 下深/浅模式透明色渲染不一致问题
=> fix(picker): update transparent color handling for light and dark modes

src/stepper/README.en-US.md, src/stepper/README.md
=> docs(stepper): add focus event

src/stepper/README.en-US.md, src/stepper/README.md, src/stepper/props.ts, src/stepper/type.ts
=> docs(Stepper): sync api doc

src/input/README.en-US.md, src/input/README.md, src/input/input.ts, src/input/input.wxml, src/input/props.ts, src/input/type.ts
- fix(Input): 增加allowInputOverMax属性
=> feat(input): support allowInputOverMax props

src/action-sheet/action-sheet.wxml, src/avatar/avatar.wxml, src/badge/badge.wxml, src/calendar/_example/base/index.wxml, src/calendar/_example/custom-range/index.wxml, src/calendar/_example/custom-text/index.wxml, src/calendar/_example/local-text/index.wxml, src/calendar/_example/multiple/index.wxml, src/calendar/_example/range/index.wxml, src/calendar/_example/switch-mode/index.wxml, src/calendar/calendar.wxml, src/calendar/template.wxml, src/count-down/count-down.wxml, src/dialog/dialog.wxml, src/dropdown-item/dropdown-item.wxml, src/indexes/indexes.wxml, src/input/input.wxml, src/message-item/message-item.wxml, src/progress/progress.wxml, src/search/search.wxml, src/swiper/swiper.wxml, src/textarea/textarea.wxml, src/tree-select/tree-select.wxml, src/upload/upload.wxml
wxs模块命名为关键字this，现修改为_this
- chore: wxs this change to _this
=> chore: wxs this change to _this

src/picker/_example/area/index.js
=> fix(picker): regional selection example shows data exception

src/input/README.en-US.md, src/input/README.md, src/radio/README.en-US.md, src/radio/README.md, src/textarea/README.en-US.md, src/textarea/README.md
=> docs: label the new features of version 1.8.6

src/link/link.ts, src/link/link.wxml
- feat(Link): 支持 `disabled` 动态变更
=> feat(Link): support disabled dynamic changes

src/radio/radio.ts
=> fix(Radio): fix style error when laying out horizontally

src/date-time-picker/__test__/index.test.js, src/picker-item/picker-item.ts
fix #2277
背景： 快速滑动的时候会有重影
- fix(Picker): 修复子项快速滑动时的重影问题
=> fix: fix jitter problem of Picker

src/common/style/theme/_dark.less, src/common/style/theme/_light.less
- 补充 `--td-brand-color-x` 系列色版，与其他端保持一致
=> chore(theme): add theme color palette

src/step-item/step-item.wxml
- fix(t-step-item): 移除title和content多余的尖括号
=> fix(t-step-item): 移除title和content多余的尖括号

src/tabs/tabs.less, src/tabs/tabs.ts, src/tabs/tabs.wxml, src/tabs/tabs.wxs
fix #3524 
背景：初始track从左至右闪过显得突兀
解决方案：初始track直接定位到准确位置，同时setTrack方法避免频繁重复setData
- fix(Tabs): 优化指示器初始显示
=> fix(Tabs): 初始快速定位track位置以及避免多次重复setData

package.json
=> chore: publish v1.8.8-beta

src/picker/README.en-US.md, src/picker/README.md, src/picker/type.ts
fix #3538 
https://github.com/TDesignOteam/tdesign-api/pull/579
- fix(Picker): 修复 `API` 文档错误，`confirmBtn` 和 `cancelBtn` 属性仅支持 `string` 和 `boolean` 类型
=> docs(Picker): fix api docs

src/cascader/cascader.ts
修复https://github.com/Tencent/tdesign-miniprogram/issues/2747
- fix(Cascader): 允许 `children` 为空数组，便于支持数据异步场景
=> fix(cascader): 修复cascader支持lazy

src/color-picker/README.md, src/slider/README.md, src/swipe-cell/README.md, src/upload/README.md
=> docs(Upload): add FAQ

src/radio-group/radio-group.ts
fix #3557
- fix(RadioGroup): 修复无法在 `form` 中获取数据的问题
=> fix: 修复radio-group无法在form里面获取数据问题

src/common/style/theme/_components.less, src/switch/README.en-US.md, src/switch/README.md, src/switch/switch.less, src/switch/switch.wxml
fix #3556 
- fix(Switch): 修复深色模式下禁用态背景色错误
=> fix(Switch): fixed disabled style error in dark mode

src/date-time-picker/README.en-US.md, src/date-time-picker/README.md, src/date-time-picker/__test__/__snapshots__/demo.test.js.snap, src/date-time-picker/_example/year-month-date/index.js, src/date-time-picker/_example/year-month-date/index.wxml, src/date-time-picker/date-time-picker.ts, src/date-time-picker/props.ts, src/date-time-picker/type.ts
fix #3492 
- feat(DateTimePicker): 支持 `showWeek` 属性
=> feat(DateTimePicker): support showWeek props

src/dialog/_example/command/index.js, src/dialog/dialog.ts
fix #3571
- feat(Dialog): 命令式调用返回触发器数据
=> feat(dialog): the imperative call returns the trigger

src/steps/steps.ts
fix #3583
- fix(Steps): 修复 `theme` 和 `sequence` 属性值动态更新后组件未重新渲染的问题
=> fix(steps): update observers to watch multiple properties

src/picker-item/picker-item.ts, src/picker-item/picker-item.wxml, src/picker/picker.ts
fix #3575 
- fix(Picker): 修复 `keys` 属性无效的问题
=> fix(Picker): solve the problem of invalid keys attribute

src/date-time-picker/__test__/__snapshots__/demo.test.js.snap, src/date-time-picker/__test__/__snapshots__/index.test.js.snap, src/date-time-picker/_example/year-month-date/index.js, src/date-time-picker/_example/year-month-date/index.wxml, src/date-time-picker/date-time-picker.ts
- fix(DateTimePicker):  修复 `start` 和 `end` 属性默认值错误，以系统当前时间为基准
=> fix(DateTimePicker): fix the start and end date default value calculation error

src/pull-down-refresh/pull-down-refresh.ts
fix #3589
- fix(PullDownRefresh): 动态设置容器最大高度错误的问题
=> fix(pull-down-refresh): dynamically set container maximum height error

src/action-sheet/README.en-US.md, src/action-sheet/README.md
Change visible and default-visible props from required to optional in both Chinese and English documentation.
将 ActionSheet 组件的 `visible` 和 `default-visible` 属性从必需改为非必需。
由于这些属性已有默认值且支持指令式调用，标记为必需属性不准确且可能造成开发者困惑。此修改仅涉及文档更新，不影响组件功能实现。
- docs(action-sheet): update visible props requirement
=> docs(action-sheet): update visible props requirement

script/gulpfile.base.js
- #3555： 修复打包产物中部分 wxml 文件未被压缩
=> fix: fixed the issue that some files were not compressed

src/tree-select/README.en-US.md, src/tree-select/README.md, src/tree-select/props.ts, src/tree-select/tree-select.ts, src/tree-select/tree-select.wxml, src/tree-select/type.ts
fix #3596 
fix #3597 
- fix(TreeSelect): 修复多选场景下跨分支点选时选中值不完整
=> fix(TreeSelect): fixed multiple selection error

src/divider/README.en-US.md, src/divider/README.md, src/divider/divider.less
- feat(Divider): 丰富 `css vars`，支持自定义分割线高度
=> chore(Divider): enrich css vars

src/dropdown-item/dropdown-item.ts
#3611
- fix(DropdownItem): 动态修改 `disabled` 属性样式未改变的问题
=> fix(dropdown-item): dynamically modify disabled attribute style has not changed

src/dropdown-menu/__test__/__snapshots__/index.test.js.snap, src/input/__test__/__snapshots__/demo.test.js.snap, src/input/_example/suffix/index.wxml, src/input/input.wxml
fix #1639
- feat(Input):  新增 `extra` 插槽
=> feat: input新增extra插槽

src/icon/icon.less
=> fix(Icon): update font file links

src/message/__test__/__snapshots__/demo.test.js.snap, src/message/_example/base/index.wxml
=> fix(Demo): fix demo

src/dropdown-item/dropdown-item.less
fix #3634
- fix(DropdownItem): 修复高度塌陷的问题
=> fix(dropdown-item): remove height property for popup host

src/dialog/index.ts
fix #1558
- fix(Dialog): 修复命令式调用时`wxml` 模版中组件属性不生效
=> fix(Dialog): 命令式调用dialog导致wxml中传入的属性不生效问题

script/gulpfile.base.js
fix #3647 
- fix: 修复 1.9.0 导致的组件类型丢失问题
=> fix: roll back commit 220464f

src/slider/__test__/__snapshots__/demo.test.js.snap, src/slider/_example/max/index.js, src/slider/_example/max/index.wxml, src/slider/_example/max/index.wxss, src/slider/_example/slider.json, src/slider/_example/slider.wxml, src/slider/slider.ts
fix #3651
- fix(Slider): 修复设置 `min` 值后 `marks` 刻度对应位置错误的问题
=> fix(slider): refactor position calculation for value and marks

src/common/shared/color-picker/color.ts, src/common/shared/color-picker/gradient.ts, src/date-time-picker/date-time-picker.ts
fix #3646 
- fix(DateTimePicker): 修复勾选 SWC 编译脚本文件时组件功能异常
- fix(ColorPicker): 修复勾选 SWC 编译脚本文件时组件功能异常
=> fix: swc mode compilation component exception

src/side-bar/_example/base/index.js, src/side-bar/_example/custom/index.js, src/side-bar/_example/with-icon/index.js
fix #2180 
- fix(sidebar): 修复demo中sidebar快速滚动时定位不准问题
=> fix(side-bar): incorrect positioning during fast scrolling in the example

src/calendar/calendar.ts
fix #3673
- fix(Calendar): 修复当 `switchMode !== 'none'` 时，重置空值后选中的状态未更新的问题
=> fix(calendar): streamline month calculation and update logic in switch mode

src/cascader/README.md
=> docs(Cascader): update docs

src/upload/README.en-US.md, src/upload/README.md, src/upload/props.ts, src/upload/type.ts, src/upload/upload.ts
fix #3534
- feat(Upload): 新增 `preview` 属性，用于关闭/开启图片预览
=> feat(Upload): support preview prop

src/rate/rate.ts
#2987
fix #2987 
- fix(Rate): 修复点选全星时弹框不显示
=> fix(rate): 点击全星时也显示弹框

src/date-time-picker/__test__/__snapshots__/index.test.js.snap, src/date-time-picker/date-time-picker.wxml, src/picker-item/picker-item.ts, src/picker-item/picker-item.wxml, src/picker/__test__/__snapshots__/index.test.js.snap, src/picker/picker.ts
=> feat(Picker): support click selection

.github/workflows/pkg-pr-new.yml
=> ci: fix pkg-pr-new

CHANGELOG.md, changelogs/CHANGELOG-0.x.md
=> docs: supplementary content of #3730

src/collapse-panel/collapse-panel.less
fix #3728
- fix(CollapsePanel): 修复部分 `css` 变量无效的问题
=> fix(collapse-panel): some css variables are invalid

.github/workflows/ci.yml
持续集成测试develop 分支，合并 pr更新 develop 分支，跑一遍 多平台，多 node 版本 build
=> ci: continuous testing of develop branch build, multi platform, multi node versions

site/docs/getting-started.en-US.md, site/docs/getting-started.md, src/upload/upload.ts, src/upload/upload.wxml
fix #3716
- feat(Upload): 支持视频预览
=> feat(upload): support video preview

src/common/utils.wxs
fix #3743 
- feat(Icon): 自定义 `icon`名称支持使用下划线
=> 修复icon名称不支持下划线的问题

site/plugins/changelog-to-json/index.ts
=> fix: change the log output path to the _site folder (#3747)

README.md
=> docs: add deepwiki link

src/calendar/calendar-header.wxml, src/calendar/template.wxml
fix #3778 
#3377 
- fix(Calendar): 修复因 `class` 关键字导致在 `Mpx` 框架中编译报错
=> fix(Calendar): renaming the class keyword

src/calendar/calendar.ts
- fix(Calendar): 修复 `value` 更新后翻页模式日历面板数据不更新的问题
=> fix(Calendar): calendar data is not updated after value is updated

src/navbar/navbar.ts
from https://github.com/Tencent/tdesign-miniprogram/issues/3787#issuecomment-3086063018
- perf(navbar): improve handling of menu button bounding client rect changes
=> perf(navbar): improve handling of menu button bounding client rect changes

src/navbar/navbar.less
=> chore(Navbar): supplement the default value of --td-navbar-center-width

CHANGELOG.md, package.json
=> chore: publish v1.10.0

site/docs/overview.en-US.md, site/docs/overview.md
=> docs(overview): supplement qrcode component content

script/gulpfile.base.js
=> chore(build): remove d.ts for example

src/upload/README.md
=> docs(Upload): update FAQ

src/skeleton/skeleton.less
fix #3834
- feat(Skeleton): 骨架屏动画`animation-delay` 属性修改为 `0s`
=> chore(Skeleton): remove animation-delay

package.json, site/main.ts, site/shims-vue.d.ts
=> chore: @tdesign/site-components instead of tdesign-site-components

README.md
https://pkg.pr.new/~/Tencent/tdesign-miniprogram
=> docs: add pkg.pr.new badge

package.json
=> chore: update packageManager to pnpm@9.15.9

packages/tdesign-miniprogram-site/plugins/plugin-tdoc/component.vue
=> revert live url

packages/components/pull-down-refresh/pull-down-refresh.wxml
fix #3895
- fix(PullDownRefresh): 修复 `t-class-loading` 配置不生效的问题
=> fix(pull-down-refresh): t-class-loading configuration does not take effect

.npmrc, package.json, packages/components/package.json, script/gulpfile.base.js
- 修复编译脚本中，判断是否组件的条件错误
- 更新过滤文件
=> fix(build): update compilation script

packages/components/qrcode/__test__/__snapshots__/demo.test.js.snap, packages/components/qrcode/_example/level/index.wxml, packages/components/qrcode/components/qrcode-canvas/qrcode-canvas.ts
fix: #3884
问题描述：二维码中间的icon位置有偏离，和挖出的空间没有完全匹配，导致出现了多余白色的现象
解决方案：修改的 icon 绘制的代码，调整了绘制参数。同时发现内部字符拼写问题、demo 中 level 的示例问题（示例链接较短，切换 level 从M到Q时，没有变化，对比了PC端，情况相同，所以换了较长的链接保证显示效果），在此一并修复。
修复前：
修复后：
=> fix(qrcode): 修复中心二维码位置偏移 (#3884)

packages/tdesign-miniprogram-chat/site/plugins/plugin-tdoc/md-to-vue.ts, packages/tdesign-miniprogram-chat/site/plugins/plugin-tdoc/transforms.ts, packages/tdesign-miniprogram/site/plugins/plugin-tdoc/md-to-vue.ts
=> fix(site): fixed the issue of rendering failure of design guide docs

packages/tdesign-miniprogram-chat/site/package.json, packages/tdesign-miniprogram/site/package.json
=> chore(deps): remove tdesign-site-components

packages/components/tab-bar/tab-bar.less
fix #3924
方案：组件根添加 `pointer-events: auto`，确保元素正常响应点击事件。 Skyline 下，组件样式暂无异常，position 定位无需调整。
测试代码片段：https://developers.weixin.qq.com/s/HkOhwfmH8C3o
参考文档： https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html#_1-tabBar-%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E5%85%BC%E5%AE%B9
- fix(TabBar): 修复在 `Skyline` 渲染引擎下， `change` 事件无效的问题
=> fix(TabBar): change event is invalid under skyline

packages/components/textarea/README.en-US.md, packages/components/textarea/README.md, packages/components/textarea/textarea.less, packages/tdesign-miniprogram/site/scripts/generate-css-vars.mjs
fix #3935 
- feat(Textarea): 组件 `CSS Vars` 新增 `--td-textarea-padding`
=> style(Textarea): support --td-textarea-padding

packages/tdesign-miniprogram/site/package.json
fix #3098，by https://github.com/Tencent/tdesign/pull/685
=> chore(site): update devDependencies

packages/components/qrcode/components/qrcode-canvas/qrcode-canvas.wxml, packages/components/qrcode/components/qrcode-status/qrcode-status.wxml, packages/components/qrcode/qrcode.ts, packages/components/qrcode/qrcode.wxml
fix #3955 
- fix(QRCode): 新增外部样式类 `t-class-canvas`
=> feat(QRCode): add t-class-canvas

packages/components/slider/slider.ts
fix #3933 
- fix(Slider): 修复动态更新 `value` 无效的问题
=> fix(Slider): fix the problem of invalid value update
