src/steps/README.md
src/steps/step-item-props.ts
src/steps/step-item.wxml
src/steps/type.ts

feat(steps): support slot icon

---

src/back-top/back-top.less
src/back-top/back-top.ts
src/back-top/back-top.wxml

fix(backtop): correct classname

---

src/tabs/tab-panel.ts
src/tabs/tab-panel.wxml
src/tabs/tabs.ts
src/tabs/tabs.wxml

fix(tabs): recover tab-item track

---

.gitignore
src/radio-group/radio-group.ts
src/radio-group/radio-group.wxml
src/radio/radio.less
src/radio/radio.ts
src/radio/radio.wxml

fix(radio):  correct classname

---

example/pages/tabs/tabs.less
example/pages/tabs/tabs.wxml
src/tabs/tabs.less
src/tabs/tabs.ts
src/tabs/tabs.wxml

Tabs:
- 添加初始样式，之前的实现只在 example 中通过 externalClass 添加
- 优化代码，避免报错

refactor(tabs): add initial style and optimize code

---

src/message/index.ts

修复：当 message 组件未引入时，应该使用 `reject` 而不是 `console.warn` 来输出错误信息
close #67

fix(message): complete error message when instance is not found

---

src/button/button.less

当 `"style"="v2"`, 微信小程序会有以下自带样式, 使得按钮 large size 的宽度显示不正常(如无法占满父组件等)
```css
button:not([size=mini]) {
margin-left: auto;
margin-right: auto;
width: 184px;
}
```
通过为 `t-size-l` 设置 `width: auto;` 修复

fix(button): large size width error

---

src/dialog/dialog.less

fix(dialog): calc button width correctly

---

example/pages/avatar/avatar.less
example/pages/avatar/avatar.ts
example/pages/avatar/avatar.wxml
src/avatar/README.md
src/avatar/avatar-group-props.ts
src/avatar/avatar-group.less
src/avatar/avatar-group.ts
src/avatar/avatar-group.wxml
src/avatar/avatar-group.wxs
src/avatar/avatar.less
src/avatar/avatar.wxml
src/avatar/avatar.wxs
src/avatar/props.ts
src/avatar/type.ts

fix issue #107：新增默认头像自带样式，无需再次添加

fix(avatar): add avatar default css

---

example/pages/dialog/dialog.ts
example/pages/dialog/dialog.wxml
src/dialog/README.md
src/dialog/dialog.ts
src/dialog/index.ts

Dialog:
- visible 改成受控属性
- 修复 Dialog.action 展示错误的问题
resolve #31

fix(dialog): visible property now is undercontrol

---

example/pages/radio/radio.wxml
src/radio-group/radio-group.ts
src/radio-group/radio-group.wxml
src/radio/README.md
src/radio/props.ts
src/radio/radio-group-props.ts
src/radio/radio.ts
src/radio/radio.wxml
src/radio/type.ts

fix(radio): turn into controlled component

---

example/pages/rate/rate.wxml
src/rate/README.md
src/rate/props.ts
src/rate/rate.ts
src/rate/type.ts

refactor(rate): turn into under controlled component

---

src/input/README.md
src/input/input.ts
src/input/input.wxml
src/input/props.ts
src/input/type.ts

Input:
- 因为双向绑定和受控冲突，目前还是未受控的
- 属性变更：
- `name` -> `label`

refactor(input): turn into controlled component

---

example/pages/slider/slider.ts
example/pages/slider/slider.wxml
src/slider/README.md
src/slider/props.ts
src/slider/slider.ts
src/slider/slider.wxml
src/slider/type.ts

refactor(slider): turn into controlled component

---

example/pages/count-down/count-down.less
example/pages/count-down/count-down.wxml
src/count-down/README.md
src/count-down/count-down.less
src/count-down/count-down.ts
src/count-down/count-down.wxml
src/count-down/props.ts
src/count-down/type.ts

Countdown:
- 新增属性：`size` \ `theme` \ `splitWithUnit`
- 完善基础样式，不需要额外写样式

refactor(countdown): add new property and complete default style

---

example/pages/stepper/stepper.wxml
src/stepper/README.md

fix: stepper使用标题时,cell的slot改为right-icon

---

example/pages/input/input.wxml
src/input/README.md
src/input/input.wxml

Fix: 修复input组件前缀丢失的问题&添加input组件文档示例

---

src/icon/README.md
src/icon/icon.ts
src/icon/icon.wxml

Icon: 移除 click 事件。
> 因为 click 就是透传的 tap 事件，不定义该事件用户也能用 tap 事件。

refactor(icon): remove useless event

---

example/pages/button/button.less
example/pages/button/button.wxml
src/button/README.md
src/button/button.less
src/button/button.ts
src/button/button.wxml

Button：
- 重构 shape 的实现，新增支持 rectangle、circle 类型
- 修复 shape = round 样式不对的问题
- 支持纯图标按钮
resolve #102 #108

refactor(button): resolve few problems

---

example/pages/toast/toast.ts
src/toast/toast.ts

API调用，多次调用时，对于后续未传入的参数，会重复使用之前传入的参数值的问题。修改为，对未传入的参数使用默认值。
fix #225

fix: [toast] API调用，多次调用时，对于后续未传入的参数，会重复使用之前传入的参数值的问题。修改为，对未传入的参数使用默认值。

---

example/pages/dialog/dialog.ts
src/dialog/index.ts

Dialog: 修复调用时没重置默认值的问题
resolve #232

fix(dialog): resolve issue #232

---

src/upload/upload.ts

Upload：修复在 iOS 上无法选择的问题
resolve #238

fix(upload): enable to select media on iOS

---

src/button/README.md
src/button/props.ts
src/button/type.ts

Button
- 修改shape属性默认值为rectangle

fix(button): use correct default value

---

src/swipe-cell/swipe-cell.ts

QQ 小程序的在 attached 中对 createSelectorQuery 的调用需放在 wx.nextTick 中

fix(swipe-cell): use createSelectorQuery in nextTick when attached

---

src/swiper/swiper.ts

QQ 小程序在 attached 中对 createSelectorQuery 的调用需放置在 wx.nextTick 中

fix(swiper): use createSelectorQuery in nextTick when attached

---

src/swipe-cell/swipe-cell.wxs

QQ 小程序编译 wxs 时使用函数默认参数值会报错；这里修改为兼容的语法；

fix(swipe-cell): use more compatible syntax

---

example/app.json
example/pages/fab/fab.ts
example/pages/fab/fab.wxml
example/pages/home/data/form.ts
src/common/template/button.wxml
src/fab/README.md
src/fab/fab.json
src/fab/fab.less
src/fab/fab.ts
src/fab/fab.wxml
src/fab/props.ts
src/fab/type.ts

feat(fab): add new component

---

src/textarea/README.md
src/textarea/textarea.less
src/textarea/textarea.ts
src/textarea/textarea.wxml

fix(textarea): add label slot

---

example/app.json
example/pages/steps/steps.wxml
src/steps/steps.less

fix(steps): use t-step-item as substep name

---

src/loading/README.md
src/loading/loading.ts
src/loading/loading.wxml
src/loading/props.ts
src/loading/type.ts

无
增加新属性：inheritColor
- feat(loading): 新增支持 inheritColor，加载标志的颜色继承外部

feat(loading): support inherit color

---

src/toast/toast.less
src/toast/toast.wxml

无
Toast 在 loading 的状态下，标志的颜色是蓝色的，应该是白色
- fix(toast): 更正 loading 标志的颜色

fix(toast): correct loading color

---

example/app.json
example/pages/home/data/display.ts
example/pages/image-viewer/image-viewer.json
example/pages/image-viewer/image-viewer.less
example/pages/image-viewer/image-viewer.ts
example/pages/image-viewer/image-viewer.wxml
example/project.config.json
src/image-viewer/README.md
src/image-viewer/image-viewer.json
src/image-viewer/image-viewer.less
src/image-viewer/image-viewer.ts
src/image-viewer/image-viewer.wxml
src/image-viewer/props.ts
src/image-viewer/type.ts

feat(image-viewer): add image-viewer component

---

src/steps/README.md
src/steps/_example/steps.less
src/steps/_example/steps.ts
src/steps/_example/steps.wxml
src/steps/step-item.less
src/steps/step-item.ts
src/steps/step-item.wxml
src/steps/steps.ts

https://github.com/Tencent/tdesign-miniprogram/issues/398
需求：steps组件中选中和未选中的点支持自定义样式
解决方案： 在原有slot基础上，进行完善，并丰富外部样式
- fix(steps): complete icon slot && enrich externalClasses

fix(steps): complete icon slot && enrich externalClasses

---

src/tab-bar/tab-bar-item.ts

- 无
- 问题：app实例上有包含循环引用时，由于setData会序列化整个app实例导致报错
- 解决方案：把setData app实例改为直接赋值，顺便减少setData计算量
-  fix(tab-bar-item): fix the problem of SetData serialization error when this contains the current instance, optimize SetData, and delete irrelevant rendering data

fix: remove component instance on setData

---

src/toast/README.md
src/toast/_example/toast.ts
src/toast/_example/toast.wxml
src/toast/index.ts
src/toast/toast.ts

✅ 新特性提交
✅ 文档改进
✅ 演示代码改进
resolve #509 
- feat(toast): toast 支持手动关闭
✅ 文档已补充或无须补充
✅ 代码演示已提供或无须提供
✅ TypeScript 定义已补充或无须补充
✅ Changelog 已提供或无须提供

feat(toast): toast 支持手动关闭

---

src/dialog/dialog.wxml
src/navbar/navbar.less
src/navbar/navbar.ts

1. `navbar`有一个CSS变量的拼写错误
2. `dialog`组件，在取消按钮传递对象作为props时，会使用确定按钮的参数
```js
Component({
data: {
cancelBtn: { content: '取消' },
confirmBtn: { content: '确定', disabled: true },
},
})
```
```jsx
<t-dialog confirm-btn="{{ confirmBtn }}" cancel-btn="{{ cancelBtn }}"></t-dialog>
```
- fix(navbar): 修复变量名 `--capsule-wight` 为 `--capsule-width` 的拼写错误
- fix(dialog): 修复取消按钮传递Object显示不正确的问题

修复navbar变量名的错误，修复dialog取消按钮无法传递Object的问题

---

src/textarea/README.md
src/textarea/textarea.ts
src/textarea/textarea.wxml

#523 
背景：`textarea` 组件 `external-classes` 下的 `t-class-placeholder` 无效
方案：移除 `t-class-placeholder`，建议用户使用 `t-textarea__placeholder` 的Class选择器，直接覆盖组件内部样式。
- fix(textarea): remove t-class-placeholder

fix(textarea): remove t-class-placeholder

---

src/dialog/dialog.wxml
src/mixins/transition.ts
src/overlay/overlay.less
src/popup/popup.less

无
修复 Dialog 展示时过渡动画
- fix(Dialog): 修复无法展示的问题以及过渡动画

fix(dialog): add dialog transition

---

src/drawer/README.md
src/drawer/drawer.wxml
src/drawer/props.ts
src/drawer/type.ts

无
由于目前的设计，是不支持 placement = top || bottom 的
因此，移除这两个类型的支持。传入 right 时为 right 否则为 left
- fix(Drawer): 调整 `placement` 属性，只支持 `left` 和 `right`

fix(drawer): placement remove top and bottom

---

example/app.json
src/picker/README.md
src/picker/_example/base/index.js
src/picker/_example/base/index.json
src/picker/_example/base/index.wxml
src/picker/_example/base/index.wxss
src/picker/_example/picker.json
src/picker/_example/picker.ts
src/picker/_example/picker.wxml

docs(picker): update code sample

---

src/loading/loading.wxml

fix #618
fix(loading): 修复text为空时，实际大小与视觉大小不一致问题
https://github.com/Tencent/tdesign-miniprogram/issues/618
- fix(Loading): 修复 `text` 为空时仍渲染非空节点的问题

fix(loading): 修复text为空时，实际大小与视觉大小不一致问题

---

example/app.json
src/skeleton/README.md
src/skeleton/_example/animation/index.js
src/skeleton/_example/animation/index.json
src/skeleton/_example/animation/index.wxml
src/skeleton/_example/animation/index.wxss
src/skeleton/_example/cell-group/index.js
src/skeleton/_example/cell-group/index.json
src/skeleton/_example/cell-group/index.wxml
src/skeleton/_example/cell-group/index.wxss
src/skeleton/_example/grid/index.js
src/skeleton/_example/grid/index.json
src/skeleton/_example/grid/index.wxml
src/skeleton/_example/image-group/index.js
src/skeleton/_example/image-group/index.json
src/skeleton/_example/image-group/index.wxml
src/skeleton/_example/image-group/index.wxss
src/skeleton/_example/skeleton.json
src/skeleton/_example/skeleton.less
src/skeleton/_example/skeleton.ts
src/skeleton/_example/skeleton.wxml
src/skeleton/_example/theme/index.js
src/skeleton/_example/theme/index.json
src/skeleton/_example/theme/index.wxml
src/skeleton/props.ts
src/skeleton/skeleton.less
src/skeleton/skeleton.ts
src/skeleton/skeleton.wxml
src/skeleton/skeleton.wxs
src/skeleton/type.ts

- feat(Skeleton): 属性 theme 移除 avatar-text；新增 avatar、image、paragraph
- feat(Skeleton):  外部样式类移除 t-class-avatar、t-class-image、t-class-text；新增 t-class-col
- fix(Skeleton): 属性 rowCol 移除默认值 `[1, 1, 1, { width: '70%' }]`
- docs(Skeleton): 更新示例代码

feat(Skeleton): theme support five base type

---

src/dropdown-menu/dropdown-item.wxml

fix #677 
修复点击遮罩层不触发关闭的问题
- fix(DropdownMenu): 修复 `closeOnClickOverlay` 不生效的问题

fix(dropdown-menu): enable close on click overlay

---

src/sticky/README.md
src/sticky/_example/base/index.js
src/sticky/_example/base/index.json
src/sticky/_example/base/index.wxml
src/sticky/_example/base/index.wxss
src/sticky/_example/container/index.js
src/sticky/_example/container/index.json
src/sticky/_example/container/index.wxml
src/sticky/_example/container/index.wxss
src/sticky/_example/offset/index.js
src/sticky/_example/offset/index.json
src/sticky/_example/offset/index.wxml
src/sticky/_example/offset/index.wxss
src/sticky/_example/sticky.json
src/sticky/_example/sticky.less
src/sticky/_example/sticky.ts
src/sticky/_example/sticky.wxml

docs(sticky): update code sample

---

src/sticky/index.ts
src/sticky/sticky.ts
src/tabs/README.md
src/tabs/__test__/__snapshots__/demo.test.js.snap
src/tabs/_example/base/index.js
src/tabs/_example/base/index.wxml
src/tabs/props.ts
src/tabs/tabs.json
src/tabs/tabs.less
src/tabs/tabs.ts
src/tabs/tabs.wxml
src/tabs/type.ts

#718 
- feat(Tabs): 新增 sticky 属性
- feat(Tabs): 新增 stickyProps 属性透传至 Sticky 组件
- feat(Tabs): 新增 CSS Variable 调整选项卡背景色
- feat(Tabs): 新增 scroll 事件

feat(tabs): support sticky

---

src/loading/README.md
src/loading/__test__/indx.test.js

test(Loading): add unit test

---

package.json
src/image-viewer/_example/base/index.js
src/image-viewer/image-viewer.less
src/image-viewer/image-viewer.ts
src/image-viewer/image-viewer.wxml

#778 
方案：图片宽高都小于屏幕宽高时，按照图片原始宽高显示，否则判断图片宽高比，按长边显示，确保图片完整显示。（mode固定为 aspectFit ）
- fix(ImageViewer): 修复图片宽高都小于屏幕宽高时的拉伸问题
- feat(ImageViewer): 更新 `demo` 示例图片

fix(ImageViewer): fix the scale problem of imageViewer

---

src/footer/README.md
src/footer/__test__/__snapshots__/index.test.js.snap
src/footer/__test__/index.test.js

https://github.com/Tencent/tdesign-miniprogram/issues/701
完善 footer 测试

test(footer): add unit test

---

package.json
src/common/utils.ts
src/notice-bar/notice-bar.ts

#813 
原因：common/utils.js 中的 requestAnimationFrame 函数重名
解决方案：将 common/utils.js 中的 requestAnimationFrame 函数更名为  getAnimationFrame
- fix(NoticeBar): 解决函数同名导致控制台报错

fix: resolve function with the same name

---

src/notice-bar/README.md
src/notice-bar/__test__/__snapshots__/index.test.js.snap
src/notice-bar/__test__/index.test.js
src/notice-bar/notice-bar.ts
src/notice-bar/props.ts
src/notice-bar/type.ts

test: add unit test for notice-bar

---

src/upload/README.md
src/upload/_example/messageFile/index.js
src/upload/_example/messageFile/index.json
src/upload/_example/messageFile/index.wxml
src/upload/_example/upload.json
src/upload/_example/upload.wxml
src/upload/props.ts
src/upload/type.ts
src/upload/upload.ts

fix #745
新增 source，默认值为 media，可选值：media/messageFile
使用 messageFile 时，则调用 `wx.chooseMessageFile` 读取媒体文件
- feat(Upload): 新增 source 属性，支持从聊天会话中读取文件

feat(upload): add source property

---

script/gulpfile.base.js
site/docs/getting-started.md

gulpfile.base.js修改declaration生成dts
[#679]
`build`的时候生成`d.ts`
更新了快速开始页面增加了配置`tsconfig.json`的配置

fix(gulpfie.base.js): 生成dts 

---

src/icon/icon.less

`speak` 属性用于指定文本是否用于听觉媒体，CSS3中弃用，该属性不支持主要浏览器，对无障碍支持度不太友好，小程序中无法识别该属性，故直接移除。
- fix(Icon): 移除 `CSS` 属性 `speak`

style(icon): remove the css property speak

---

src/dialog/index.ts
src/message/index.ts

#893 
- fix(Dialog): 函数式`Dialog.close()` 关闭窗体支持自定义  `selector`
- fix(Message): 函数式`Dialog.hide()` 关闭窗体支持自定义  `selector`

fix(Dialog&&Message): command line close supports custom selectors

---

src/steps/step-item.ts

fix #884
由于将保存父子关系保存到 data 里，导致内存溢出。
这个信息不会在 WXML 中使用，因此将数据移出 data 即可。
- fix(Steps): 修复内存溢出的问题

fix(steps): resolve memory overflow problem

---

src/skeleton/README.md
src/skeleton/__test__/__snapshots__/demo.test.js.snap
src/skeleton/__test__/__snapshots__/index.test.js.snap
src/skeleton/_example/animation/index.js
src/skeleton/_example/animation/index.wxml
src/skeleton/_example/animation/index.wxss
src/skeleton/_example/cell-group/index.js
src/skeleton/_example/cell-group/index.wxml
src/skeleton/_example/grid/index.js
src/skeleton/_example/grid/index.wxml
src/skeleton/_example/grid/index.wxss
src/skeleton/_example/image-group/index.js
src/skeleton/_example/skeleton.wxml
src/skeleton/_example/theme/index.js
src/skeleton/_example/theme/index.wxml
src/skeleton/_example/theme/index.wxss
src/skeleton/skeleton.less
src/skeleton/skeleton.ts
src/skeleton/skeleton.wxs

- feat(Skeleton): 视觉升级
- feat(Skeleton): 新增 CSS Variables， 用于调整骨架屏背景颜色、行间距等

style(Skeleton): using new style

---

src/textarea/README.md
src/textarea/__test__/__snapshots__/demo.test.js.snap
src/textarea/__test__/__snapshots__/index.test.js.snap
src/textarea/__test__/demo.test.js
src/textarea/__test__/index.test.js
src/textarea/_example/autosize/index.wxml
src/textarea/_example/custom/index.js
src/textarea/_example/custom/index.json
src/textarea/_example/custom/index.wxml
src/textarea/_example/custom/index.wxss
src/textarea/_example/disabled/index.wxml
src/textarea/_example/maxcharacter/index.wxml
src/textarea/_example/maxlength/index.wxml
src/textarea/_example/textarea.json
src/textarea/_example/textarea.wxml
src/textarea/props.ts
src/textarea/textarea.less
src/textarea/textarea.ts
src/textarea/textarea.wxml
src/textarea/type.ts

- fix(Textarea): maxlength 默认值变更为 -1
- feat(Textarea): 新增 placeholderStyle、fixed 、bordered、 indicator 等属性
- feat(Textarea): 新增 CSS Variables， 用于调整文本框背景、输入文本颜色
- feat(Textarea): 外部样式类新增  t-class-indicator

feat(Textarea): enrich attributes

---

src/calendar/README.en-US.md
src/calendar/README.md
src/calendar/__test__/__snapshots__/demo.test.js.snap
src/calendar/__test__/demo.test.js
src/calendar/__test__/index.test.js
src/calendar/_example/base/index.wxml
src/calendar/_example/calendar.json
src/calendar/_example/calendar.wxml
src/calendar/_example/custom-button/index.js
src/calendar/_example/custom-button/index.json
src/calendar/_example/custom-button/index.wxml
src/calendar/_example/custom-button/index.wxss
src/calendar/calendar.ts
src/calendar/calendar.wxml
src/calendar/props.ts
src/calendar/type.ts

fix #1108
修复 confirm-btn = null 时仍显示按钮的问题
- fix(Calendar): 修复 confirm-btn = null 时仍显示按钮的问题
- feat(Calendar): 新增 change 事件，在不显示确认按钮时使用
- break(Calendar): 事件返回参数改成时间戳，保持和 value 一致

fix(calendar): enable without confirm button

---

src/calendar/__test__/__snapshots__/index.test.js.snap
src/date-time-picker/__test__/__snapshots__/index.test.js.snap
src/dialog/__test__/__snapshots__/index.test.js.snap
src/picker/__test__/__snapshots__/index.test.js.snap
src/popup/popup.wxml

fix #1081
由于修复滚动穿透导致的 popup 无法滚动。
由于小程序的限制，没法限制滚动穿透。
- fix(Popup): 修复 Popup 以及底层依赖 Popup 的组件无法滚动的问题

fix(popup): remove catch touch-move

---

src/grid/README.md
src/grid/grid-item-props.ts
src/grid/grid-item.wxml
src/grid/type.ts

#1101
- feat(Grid): 新增 iconProps 属性

feat(Grid): support iconProps:

---

src/calendar/__test__/__snapshots__/index.test.js.snap
src/cell/__test__/__snapshots__/index.test.js.snap
src/collapse/__test__/__snapshots__/index.test.js.snap
src/common/src/instantiationDecorator.ts
src/icon/icon.wxml
src/image/__test__/__snapshots__/index.test.js.snap
src/input/__test__/__snapshots__/index.test.js.snap
src/notice-bar/__test__/__snapshots__/index.test.js.snap
src/pull-down-refresh/__test__/__snapshots__/demo.test.js.snap
src/search/__test__/__snapshots__/index.test.js.snap
src/stepper/__test__/__snapshots__/index.test.js.snap

无
底层给所有组件支持 `aria-hidden`、`aria-label`、`aria-role` 三个属性。
后续需要增加的话，再直接扩展。
目前是增加了 property 的定义，每个组件仍需在 WXML 使用才能支持使用。
- feat: 底层给所有组件增加 `aria-*` 属性
- feat(Icon): 新增支持 `aira-*` 属性

feat: support aria property for all component

---

src/search/__test__/__snapshots__/index.test.js.snap
src/search/search.wxml

fix #1061 
录屏更新：
安卓：https://share.weiyun.com/gkCUNeA7
- feat(Search): 支持无障碍访问

Aria search

---

src/radio-group/radio-group.wxml
src/radio/radio.less
src/radio/radio.wxml

fix #1026
- fix(Radio): 支持无障碍访问
https://share.weiyun.com/knCyrY5z

fix(radio): 修复朗读问题. (#1026)

---

src/image-viewer/__test__/__snapshots__/index.test.js.snap
src/image/__test__/__snapshots__/demo.test.js.snap
src/image/__test__/__snapshots__/index.test.js.snap
src/image/_example/base/index.wxml
src/image/image.wxml

fix #1030 
1. image 增加 `aria-hidden` 和 `aria-label` (已用示例测试过，在组件上添加 `aria-label` 即可)
2. icon 增加 `aria-role` 和 `aria-label`
3. 其中”加载中“需要 t-loading 组件提供
ios 录屏
https://user-images.githubusercontent.com/44194929/204703044-b741bf4c-58b1-4c32-b8f9-264775659b40.mov
- feat(Image): 支持无障碍访问

feat(image): support aria

---

src/navbar/__test__/__snapshots__/demo.test.js.snap
src/navbar/_example/back-home/index.wxml
src/navbar/_example/img/index.wxml
src/navbar/navbar.wxml

fix #1020
Navbar导航栏增加对无障碍的支持，返回按钮现在可以被正确识别出来
- fix(NavBar): 支持无障碍访问
演示链接： https://share.weiyun.com/mWp8QPBq

[NavBar] 无障碍支持

---

src/common/src/index.ts
src/common/src/useId.ts
src/grid/__test__/__snapshots__/index.test.js.snap
src/grid/grid-item.ts
src/grid/grid-item.wxml

fix #1025 
1. grid-item 增加 `aria-label` 和 `aria-role` (默认 `button`)
ios 录屏
https://user-images.githubusercontent.com/44194929/205233256-c95d6066-a9e3-4612-b82d-7d14a2913fb7.mov
- feat(Grid): 无障碍支持

feat(grid): support aria

---

src/calendar/calendar.ts
src/calendar/calendar.wxml

fix #1194
修复日历按钮传入 text 不生效的问题
- fix(Calendar): 修复按钮传入 text 不生效，以及不支持响应式的问题
- break(Calendar): 按钮的插槽变更成和文档一致：`confirm-btn`

fix(calendar): handle button correctly

---

src/back-top/back-top.wxml

fix #1181 
https://share.weiyun.com/866BC4OP
- feat(BackTop): 支持无障碍访问

feat(back-top): support aria

---

src/collapse/__test__/__snapshots__/index.test.js.snap
src/collapse/__test__/index.test.js
src/collapse/collapse-panel.wxml

fix #1055
- cell 的 a11y 不确定合入时间，因此先在 header 外层包裹一个 view 元素，增加 bind:tap 和 aria 属性
- wrapper 增加 aria-hidden 属性
- feat(Collapse): 支持无障碍访问
iOS:
https://user-images.githubusercontent.com/5051221/207517871-55fbe6f3-9d4c-4ee6-b2ef-6fee8bcd2214.mp4
Android:
https://user-images.githubusercontent.com/5051221/207523110-d874fc5b-ee41-4ab1-b47b-b593848ef7bd.mp4
- Android 录屏第一次点击 collapse 后，焦点跳到了“网页视图”，可能是华为读屏模式的问题，试了下 weui 小程序也会有同样的问题。

feat(collapse): 无障碍支持

---

src/swipe-cell/README.en-US.md
src/swipe-cell/README.md
src/swipe-cell/__test__/__snapshots__/demo.test.js.snap
src/swipe-cell/__test__/demo.test.js
src/swipe-cell/_example/double/index.js
src/swipe-cell/_example/double/index.json
src/swipe-cell/_example/double/index.wxml
src/swipe-cell/_example/double/index.wxss
src/swipe-cell/_example/icon/index.js
src/swipe-cell/_example/icon/index.json
src/swipe-cell/_example/icon/index.wxml
src/swipe-cell/_example/icon/index.wxss
src/swipe-cell/_example/left/index.wxml
src/swipe-cell/_example/right/index.wxml
src/swipe-cell/_example/swipe-cell.json
src/swipe-cell/_example/swipe-cell.less
src/swipe-cell/_example/swipe-cell.wxml
src/swipe-cell/swipe-cell.json
src/swipe-cell/swipe-cell.less
src/swipe-cell/swipe-cell.wxml

- feat(SwipeCell): 属性 right 和 left 支持使用 icon
- break(SwipeCell): 调整 DOM

feat(SwipeCell): support icon

---

src/overlay/__test__/__snapshots__/demo.test.js.snap
src/overlay/_example/base/index.wxml
src/overlay/_example/overlay.wxml
src/overlay/overlay.less

无
支持 CSS Variables
- feat(Overlay): 支持 CSS Variables，可自定义主题

feat(overlay): support css variables

---

src/textarea/textarea.less
src/textarea/textarea.ts
src/textarea/textarea.wxml

#1266 
#1268 
- fix(Textarea): 支持 value 变更时更新字符长度
- fix(Textarea): 修复 less 变量使用错误

fix(textarea): support responsive update of value

---

src/side-bar-item/side-bar-item.wxml

fix #1320 
https://user-images.githubusercontent.com/17818509/210031466-f5adbd95-c63e-401c-9622-38339fcc47f1.mp4
https://user-images.githubusercontent.com/17818509/210031476-95010fa8-42f2-40e1-9a1b-42d5038b6ec4.mp4

feat(treeselect): 读屏优化

---

src/cell/__test__/__snapshots__/demo.test.js.snap
src/cell/__test__/__snapshots__/index.test.js.snap
src/cell/_example/multiple/index.wxml
src/cell/cell.wxml
src/collapse/__test__/__snapshots__/index.test.js.snap

fix #1031 
- **cell** 每行焦点分散问题，每行应统一获得焦点 => **cell** 组件默认设置`aria-role=button`
- ~~**cell** 右侧若是开关则朗读相应的 **role** => **cell** 组件向上暴露的 **aria-role** 属性、**aria-checked** 属性~~ 
cell 和 switch 组件一起使用时，暂不考虑行焦点问题 @syxysszyw 
- 每行可自定义朗读内容 => **cell** 组件向上暴露的 **aria-label** 属性
- feat(Cell): 支持无障碍访问
https://share.weiyun.com/V7CYP1DA

feat(cell): 增加无障碍支持

---

src/checkbox/checkbox.less
src/checkbox/checkbox.wxml
src/dropdown-menu/dropdown-item.wxml
src/dropdown-menu/dropdown-menu.ts
src/dropdown-menu/dropdown-menu.wxml
src/radio/radio.less
src/radio/radio.wxml

fix #1047
给dropdown-menu增加了对应的label，将item的文字以及icon合并，一个item激活时，其他item暂时隐藏。
dropdown-item的选项增加tabindex以实现展开时快速聚焦。
- feat(DropdownMenu): 支持无障碍访问
https://user-images.githubusercontent.com/44339196/209605571-14508a81-b3b8-4a2d-9d49-d80ef7c8d4ce.mp4
https://user-images.githubusercontent.com/44339196/209605592-069fd362-64a5-4842-9f7f-4b289e8fa52a.mp4

feat(dropdown): dropdown-menu无障碍支持

---

src/slider/slider.less
src/slider/slider.wxml

fix #1048 
- fix(Slider): 支持无障碍访问
1. 全局扫描: 
https://codesign.qq.com/s/1DWk9J7LWo0GnMm
2. 操作
https://codesign.qq.com/s/a4Jd0NPAXJjAMkb

fix(slider): 无障碍支持. (#1048)

---

src/button/__test__/__snapshots__/demo.test.js.snap
src/button/_example/icon-btn/index.wxml
src/button/_example/icon-btn/index.wxss
src/button/button.less
src/button/button.ts
src/button/button.wxml
src/calendar/__test__/__snapshots__/index.test.js.snap
src/calendar/calendar.less
src/common/style/mixins/_cursor.less
src/common/style/mixins/_index.less
src/common/template/button.wxml
src/sticky/__test__/__snapshots__/index.test.js.snap

fix #1291 补充问题
- feat(Button): 新增部分 CSS Variables
- fix(Dialog): 修复 Dialog 中，confirmBtn 和 cancelBtn 属性为 Object 时，ghost 和 shape 属性不生效问题

feat(Button): add some css variables

---

src/avatar/README.en-US.md
src/avatar/README.md
src/avatar/__test__/__snapshots__/demo.test.js.snap
src/avatar/__test__/index.test.js
src/avatar/_example/action/index.wxml
src/avatar/avatar-group.less
src/avatar/avatar-group.ts
src/avatar/avatar-group.wxml
src/avatar/avatar.less
src/avatar/avatar.ts
src/avatar/avatar.wxml
src/avatar/avatar.wxs
src/avatar/props.ts
src/avatar/type.ts

无
修复错误逻辑，移除冗余代码
- break(Avatar): 优化类名，符合 BEM 规范

fix(avatar): optimize code

---

src/calendar/README.en-US.md
src/calendar/README.md
src/calendar/__test__/__snapshots__/demo.test.js.snap
src/calendar/__test__/__snapshots__/index.test.js.snap
src/calendar/_example/base/index.js
src/calendar/_example/base/index.wxml
src/calendar/_example/custom-button/index.wxss
src/calendar/_example/custom-range/index.js
src/calendar/_example/multiple/index.js
src/calendar/_example/range/index.js
src/calendar/calendar.ts
src/calendar/calendar.wxml
src/calendar/props.ts
src/calendar/type.ts

fix #1310
新增 auto-close 属性，以及 close 事件
- feat(Calendar): 新增 auto-close 属性，以及 close 事件

feat(calendar): support auto-close property and close event

---

src/textarea/__test__/__snapshots__/demo.test.js.snap
src/textarea/_example/base/index.wxml
src/textarea/_example/base/index.wxss
src/textarea/_example/card/index.wxml
src/textarea/_example/card/index.wxss
src/textarea/_example/custom/index.js
src/textarea/_example/custom/index.wxml
src/textarea/_example/custom/index.wxss
src/textarea/_example/disabled/index.wxml
src/textarea/_example/disabled/index.wxss
src/textarea/_example/label/index.wxml
src/textarea/_example/label/index.wxss
src/textarea/_example/maxcharacter/index.wxml
src/textarea/_example/maxcharacter/index.wxss
src/textarea/_example/maxlength/index.wxml
src/textarea/_example/maxlength/index.wxss
src/textarea/_example/textarea.less
src/textarea/_example/textarea.wxml
src/textarea/textarea.less

背景：通过 customStyle 修改父容器高度后，由于 textarea 高度固定不能自适应容器高度，导致指示器位置不正确
方案： textarea 修改为自适应父容器高度，同时因为 autoSize 状态下文本框 style.height 为20px，这里为了保持与之一致，设置`min-height: 20px`
- fix(Textarea): 支持自适应父容器高度

fix(Textarea): support adaptive parent container height

---

src/button/__test__/__snapshots__/demo.test.js.snap
src/button/_example/shape/index.wxml
src/button/button.less
src/button/button.ts
src/calendar/__test__/__snapshots__/index.test.js.snap
src/sticky/__test__/__snapshots__/index.test.js.snap

背景： 当使用 shape = ‘round'或‘circle’ 时，border样式不正确
截图：
最终效果：
- ffix(Button): 修复 `shape = 'round'` 或 `‘circle’` 时，`border`样式错误

fix(Button): fix style errors when using shape attribute

---

src/date-time-picker/__test__/__snapshots__/index.test.js.snap
src/date-time-picker/date-time-picker.less
src/date-time-picker/date-time-picker.wxml
src/picker-item/picker-item.less
src/picker-item/picker-item.ts
src/picker-item/picker-item.wxml
src/picker/__test__/__snapshots__/index.test.js.snap
src/picker/picker.less

fix #1447 
fix #1479
优化 picker 布局，解决换行，宽度不够的问题
- fix(Picker): 修复样式、优化布局以及交互体验

feat(picker): upate ux

---

example/app.json
src/side-bar-item/props.ts
src/side-bar-item/side-bar-item.json
src/side-bar-item/side-bar-item.less
src/side-bar-item/side-bar-item.ts
src/side-bar-item/side-bar-item.wxml
src/side-bar-item/type.ts
src/side-bar/README.en-US.md
src/side-bar/README.md
src/side-bar/__test__/__snapshots__/demo.test.js.snap
src/side-bar/__test__/demo.test.js
src/side-bar/_example/side-bar.wxml
src/side-bar/_example/with-icon/index.js
src/side-bar/_example/with-icon/index.json
src/side-bar/_example/with-icon/index.wxml
src/side-bar/_example/with-icon/index.wxss

无
支持传入图标
- feat(SideBar): 支持传入 Icon

feat(sidebar): finish support icon

---

example/project.config.json
src/button/button.less
src/checkbox/checkbox.less

fix #1291 二轮走查补充问题中 文本按钮点击态背景色不正确
最新视觉： https://codesign.woa.com/app/design/kv8398dMMM9nKeg/wRap9x8d7ND9r4g/inspect
- fix(Checkbox):  修复 `--td-checkbox-icon-size` 对未选中态复选框不生效问题
- feat(Button): 支持点击态边框颜色 css variable

feat(Checkbox&&Button): enrich css variable

---

src/side-bar/__test__/__snapshots__/demo.test.js.snap
src/side-bar/_example/base/index.js
src/side-bar/_example/custom/index.js
src/side-bar/_example/switch/index.js
src/side-bar/_example/with-icon/index.js

fix #1255 
ios 录屏
- feat(Sidebar): 支持无障碍访问

feat(sidebar): support aria

---

src/drawer/drawer.wxml

fix #1057 
ios 录屏
- feat(Drawer): 支持无障碍访问

feat(drawer): support aria

---

jest.virtualHost.config.js
script/test/snapshotResolver.js
src/avatar/__test__/__snapshots__/index.test.js.snap
src/avatar/__test__/__virtualHostSnapshot__/demo.test.js.snap
src/avatar/__test__/__virtualHostSnapshot__/index.test.js.snap
src/avatar/__test__/index.test.js

test: update jest.virtualHost.config.js

---

src/image/__test__/__snapshots__/demo.test.js.snap
src/image/_example/status/index.wxml

fix(image): update slot demo

---

src/dropdown-item/dropdown-item.less

fix #1613 
- fix(DropdownMenu): 修复下拉菜单遮罩层无法点击

fix:修复下拉菜单遮罩层无法点击的问题

---

src/count-down/README.md
src/count-down/__test__/__snapshots__/demo.test.js.snap
src/count-down/__test__/__virtualHostSnapshot__/demo.test.js.snap
src/count-down/_example/base/index.wxml
src/count-down/_example/base/index.wxss
src/count-down/_example/size/index.wxml
src/count-down/count-down.less
src/count-down/count-down.wxml
src/count-down/type.ts

- break(CountDown): `theme` 属性移除 `hightlight`
- fix(CountDown): 修复默认风格下时间单位分割的问题

chore(CountDown): remove hightlight theme

---

site/site.config.mjs
src/checkbox/README.md
src/divider/README.md
src/divider/_example/divider.wxml
src/side-bar/README.md
src/sticky/README.md

fix: update sidebar of the site

---

site/plugin-tdoc/md-to-vue.ts
site/plugin-tdoc/transforms.ts

相关pr： https://github.com/Tencent/tdesign-common/pull/1160
- fix: 修复官网部分组件设计指南文档不显示
- feat: 更新设计指南文档

docs(common): update design docs

---

src/notice-bar/README.en-US.md
src/notice-bar/README.md
src/notice-bar/__test__/__snapshots__/demo.test.js.snap
src/notice-bar/__test__/__snapshots__/index.test.js.snap
src/notice-bar/__test__/__virtualHostSnapshot__/demo.test.js.snap
src/notice-bar/__test__/__virtualHostSnapshot__/index.test.js.snap
src/notice-bar/__test__/index.test.js
src/notice-bar/_example/customization/index.wxml
src/notice-bar/_example/customization/index.wxss
src/notice-bar/_example/event/index.wxml
src/notice-bar/_example/event/index.wxss
src/notice-bar/notice-bar.less
src/notice-bar/notice-bar.ts
src/notice-bar/notice-bar.wxml
src/notice-bar/props.ts
src/notice-bar/type.ts

- break(NoticeBar):  `extra` 属性更名为 `operation`
- fix(NoticeBar): 修复主题图标不正确
- fix(NoticeBar): 更新示例文档

chore(NoticeBar): extra attribute is renamed to operation

---

src/action-sheet/README.en-US.md
src/action-sheet/README.md
src/action-sheet/action-sheet.ts
src/action-sheet/type.ts

无
补充 close 事件，增加 trigger 参数
- fix(ActionSheet): 补充 close 事件，增加 trigger 参数

fix(action-sheet): add close event

---

src/drawer/README.en-US.md
src/drawer/README.md
src/drawer/drawer.ts
src/drawer/props.ts
src/drawer/type.ts

无
修复 close 事件不生效的问题
- fix(drawer): 修复 close 事件不生效的问题

fix(drawer): resolve close event

---

src/picker-item/picker-item.ts
src/picker-item/picker-item.wxml
src/picker/README.en-US.md
src/picker/README.md
src/picker/_example/base/index.wxml
src/picker/picker.ts
src/picker/props.ts
src/picker/type.ts

- feat(Picker): 新增支持 keys 属性
- doc(Picker): 文档中移除 render-label、columns 还不支持的属性

feat(picker): support keys property

---

src/common/utils.ts
src/upload/__test__/index.test.js
src/upload/upload.ts

fix #1569
修复 sizelimit 不支持对象传参的问题
- fix(Upload): 修复 sizelimit 不支持对象传参的问题
- fix(Upload): 修复 sizelimit 默认单位和文档不一致的问题，从 `B` 改成 `KB`

fix(upload): make size-limit support object

---

src/pull-down-refresh/pull-down-refresh.wxml

feat #1071
fix #1071
* 在刷新组件添加 aria-live="polite"实现实施区域状态改变时焦点移动
- feat(pull-down-refresh): 无障碍支持
Android:
https://user-images.githubusercontent.com/92632534/208288584-dfc4323d-fc27-43fc-86b4-9b520d5eaaf0.mp4
downrefresh.mp4)

feat(pull-down-refresh): 无障碍支持

---

src/col/col.wxml
src/common/utils.wxs

fix #1701 
row 组件和 col 组件的属性值要支持 string 类型
解决方案：修改 cls 方法，支持传入 number 类型
- fix(Layout): row 组件和 col 组件的属性值支持 string 类型

fix: cls函数支持传入数值类型

---

src/button/button.ts
src/button/button.wxml
src/calendar/__test__/__snapshots__/index.test.js.snap

fix #1797 
button 组件的 disableb 属性对控制 tap 无效问题
解决方案：catchtap 事件要触发，才能阻止事件冒泡
- fix(Button): 修复 disabled = true 仍触发 tap 事件的问题

修复 button 组件 disableb 对控制 tap 无效问题

---

src/message/message.ts

fix #1855 
- fix(Message): 处理 `loop` 产生的控制台告警
- fix(Message): 修复 `marquee = true` 时，滚动动画错误

fix(Message): resolve marquee

---

src/button/button.wxml
src/calendar/__test__/__virtualHostSnapshot__/index.test.js.snap
src/cascader/__test__/__virtualHostSnapshot__/demo.test.js.snap
src/date-time-picker/__test__/__virtualHostSnapshot__/index.test.js.snap
src/switch/__test__/__virtualHostSnapshot__/demo.test.js.snap

修复[button] type="submit"时，disabled未生效
fix #1848 
fix(Button): 修复 type= submit 时，disabled 未生效的问题

fix(button): 修复[button] type="submit"时，disabled未生效

---

src/row/row.less

添加row的flex布局，垂直居中
fix #1851
原有样式（垂直没有居中）：
改进后样式：
如果说之前使用组件的时候改过col或者row的样式可以全局检查一遍
- fix(Row): 增加默认样式实现垂直居中

style(row): row垂直居中样式

---

src/grid-item/grid-item.less

修复column>=4个时，`--td-grid-item-image-width`和`--td-grid-item-text-font-size`是无效的
增加4个新值
```css
--td-grid-item-image-small-width
--td-grid-item-image-middle-width
--td-grid-item-text-small-font-size
--td-grid-item-text-middle-font-size
```
fix #1829 
- feat(Grid): 补充 CSS Variables 以修改不同列数下的图片尺寸和文字大小

fix(grid): 修复column>=4个时，--td-grid-item-image-width和--td-grid-item-text-font-size是无效的

---

src/common/style/utilities/_index.less
src/rate/__test__/__snapshots__/demo.test.js.snap
src/rate/_example/special/index.wxml
src/rate/rate.less
src/rate/rate.ts
src/rate/rate.wxml

fix #1050 
- feat(Rate): 支持无障碍访问
【腾讯 CoDesign】TD-微信小程序-Rate-iOS-02...
https://codesign.qq.com/s/7VXl9ONEOYj8WRA

fix(rate): 评分组件支持无障碍滑动

---

src/common/style/_variables.less
src/image-viewer/README.en-US.md
src/image-viewer/README.md
src/image-viewer/image-viewer.less
src/image-viewer/image-viewer.ts
src/image-viewer/image-viewer.wxml
src/image-viewer/props.ts
src/image-viewer/type.ts

fix #1904 
开启自定义导航栏的时候，imageviewer 的顶部按钮会被遮挡，因此新增属性 usingCustomNavigation 用于调整 imageViewer 的顶部位置。
- feat(ImageViewer): 新增 usingCustomNavigation 属性，处理使用自定义导航栏时被遮挡的问题

fix(image-viewer): add using-custom-navation property

---

src/picker/README.en-US.md
src/picker/README.md
src/picker/props.ts
src/picker/type.ts

fix #1838 
无
- docs(Picker): 完善文档，增加 TS 定义的关联链接。

docs(picker): enrich api detail

---

src/tabs/tabs.ts
src/tabs/tabs.wxml
src/tabs/tabs.wxs

fix #1745 
fix #1750 
滚动 scrollview 之后，导致 track 的定位计算错误
- fix(Tabs): 修复 track 位置计算错误的问题

fix(tabs): resolve track position

---

src/date-time-picker/README.en-US.md
src/date-time-picker/README.md
src/date-time-picker/__test__/__snapshots__/demo.test.js.snap
src/date-time-picker/__test__/demo.test.js
src/date-time-picker/_example/date-time-picker.json
src/date-time-picker/_example/date-time-picker.wxml
src/date-time-picker/_example/steps/index.js
src/date-time-picker/_example/steps/index.json
src/date-time-picker/_example/steps/index.wxml
src/date-time-picker/_example/steps/index.wxss
src/date-time-picker/date-time-picker.ts
src/date-time-picker/props.ts
src/date-time-picker/type.ts

fix #1789
新增 steps 属性，用于调整时间间隔步数
- feat(DateTimePicker): 新增 steps 属性，用于调整时间间隔步数

feat(datetime-picker): support steps property

---

src/step-item/props.ts
src/step-item/step-item.less
src/step-item/step-item.ts
src/step-item/step-item.wxml
src/step-item/type.ts
src/steps/README.en-US.md
src/steps/README.md
src/steps/props.ts
src/steps/steps.less
src/steps/steps.ts
src/steps/steps.wxml
src/steps/type.ts

fix #1672
修复icon插槽的问题
- fix(Steps): 修复 icon 插槽无法使用的问题
- feat(Steps): 新增 sequence 属性，支持逆序展示

feat(steps): add sequence property

---

src/textarea/README.md
src/textarea/__test__/__snapshots__/demo.test.js.snap
src/textarea/__test__/__snapshots__/index.test.js.snap
src/textarea/__test__/__virtualHostSnapshot__/demo.test.js.snap
src/textarea/__test__/__virtualHostSnapshot__/index.test.js.snap
src/textarea/_example/autosize/index.js
src/textarea/_example/autosize/index.wxml
src/textarea/props.ts
src/textarea/textarea.wxml
src/textarea/textarea.wxs
src/textarea/type.ts

背景：autosize 控制最大最小行数
方案：autosize 支持传入对象，如 { maxHeight: 120, minHeight: 20 }，以此控制最大最小行数
- feat(Textarea):  属性 autoSize 支持控制最大最小高度

feat(Textarea): support max/min height

---

src/sticky/README.md
src/sticky/__test__/index.test.js
src/sticky/sticky.less
src/sticky/sticky.ts
src/sticky/sticky.wxml

fix #2006
其他说明：sticky 组件外层的 margin 和 padding在锁定状态下会出现内容溢出问题，视图是从上到下、从左到右渲染，所以看上去右边距消失了。 这里，我们新提供了一个外部样式类 `t-class-content`，可以通过这个类直接给sticky组件的content内容边距。
```html
<t-sticky t-class-content="class-content">
<t-button size="large" theme="primary" t-class="external-class">基础吸顶</t-button>
</t-sticky>
```
```css
.class-content {
margin: 0 30rpx;
}
```
- fix(Sticky): 解决 fixed 定位时宽度错误
- feat(Sticky): 补充外部样式类`t-class-content`

fix(Sticky): resolved width problem

---

src/search/README.md
src/search/__test__/__snapshots__/index.test.js.snap
src/search/__test__/__virtualHostSnapshot__/index.test.js.snap
src/search/props.ts
src/search/search.wxml
src/search/type.ts

fix #2063 
- feat(Search): 新增 `cursor-spacing` 属性

feat(Search): support cursor-spacing attr

---

src/checkbox-group/checkbox-group.wxml
src/checkbox-group/props.ts
src/checkbox-group/type.ts
src/checkbox/README.en-US.md
src/checkbox/README.md
src/checkbox/__test__/__snapshots__/demo.test.js.snap
src/checkbox/__test__/__virtualHostSnapshot__/demo.test.js.snap
src/checkbox/_example/base/index.wxml

- fix #2032 
- feat(CheckboxGroup): 新增 borderless 属性

feat(checkbox-group): add borderless property

---

src/calendar/__test__/__snapshots__/index.test.js.snap
src/date-time-picker/__test__/__snapshots__/index.test.js.snap
src/dialog/__test__/__snapshots__/index.test.js.snap
src/dropdown-menu/__test__/__snapshots__/index.test.js.snap
src/picker/__test__/__snapshots__/index.test.js.snap
src/popup/popup.wxml

fix #2142
fix #2083 
fix #2026
因为增加 a11y 的属性，导致在 Android 的机器上，打开 Popup 会自动聚焦到第一个可聚焦的元素上。
- fix(Popup): 解决自动聚焦的问题

fix(popup): resolve auto focus

---

src/swiper/README.md

fix #2248
无
- docs(Swiper): 补充外部样式类信息

docs(swiper): add external class

---

src/input/README.en-US.md
src/input/README.md
src/input/__test__/__snapshots__/index.test.js.snap
src/input/input.less
src/input/input.wxml

- fix(Input): 修复 `t-class-label` 外部样式类无法修改 `label` 宽度
- feat(Input): 新增  `--td-input-label-max-width` 和 `--td-input-label-min-width` 两个样式变量

fix(Input): resolved t-class-label invalid

---

src/loading/README.en-US.md
src/loading/README.md
src/loading/loading.less

新增 CSS Variable
- feat(Loading): 新增 CSS Variable 用于调整加载提示文案颜色

feat(loading): add css variable for text color

---

src/radio-group/radio-group.wxml
src/radio-group/type.ts
src/radio/README.en-US.md
src/radio/README.md
src/radio/props.ts
src/radio/radio.ts
src/radio/type.ts

- fix #2287 
- feat(Radio): 新增 `readonly` 属性

feat(radio): enable readonly

---

src/dropdown-menu/README.en-US.md
src/dropdown-menu/README.md
src/dropdown-menu/dropdown-menu.ts

fix #2260 
- feat(DropdownMenu): 新增 `open` 和 `close` 事件

feat(dropdown-menu): enable events open and close

---

src/tabs/__test__/__snapshots__/demo.test.js.snap
src/tabs/__test__/__virtualHostSnapshot__/demo.test.js.snap
src/tabs/_example/base/index.wxml

现在[tabs文档](https://tdesign.tencent.com/miniprogram/components/tabs)里【基础选项卡】的第3个示例代码存在相同的value。这会导致：
1. 右侧的预览中，无法点击第3行第4个“上限四字”tab；
2. 有人(比如我...)把这段代码复制到本地后，会发现点击不了tab；

docs(tabs): correct tabs example have same value

---

src/image/__test__/__snapshots__/index.test.js.snap
src/image/image.ts

- fix(Image):  优化组件内部函数重复执行的问题

perf(image): method duplicate execute

---

src/side-bar-item/side-bar-item.less

fix #2430
#2430
激活项的prefix与suffix元素会遮挡其兄弟项的点击热区，prefix与suffix设置为pointer-events:none;将点击事件传递给下层。
- fix(SideBar): 修复子项激活态时 `prefix`与`suffix` 内容遮挡相邻项的点击热区问题

fix(side-bar-item): 修复激活项的兄弟项点击热区部分丢失的问题

---

example/components/trd-privacy/privacy.js
example/components/trd-privacy/privacy.json
example/components/trd-privacy/privacy.wxml
example/components/trd-privacy/privacy.wxss
example/pages/home/home.json
example/pages/home/home.less
example/pages/home/home.ts
example/pages/home/home.wxml

TDesign组件库示例增加服务声明
<div style="display: flex">
</div>

feat: add trd-privacy component for example

---

src/calendar/calendar.less

fix #2382
问题：use-popup 设置为false情况，日历样式存在兼容问题
解决方案：组件自适应父容器宽
- fix(Calendar): 修复 `use-popup` 为 `false` 时，组件未适应父容器宽度的问题

fix(calendar): calendar组件自适应父容器宽

---

src/notice-bar/README.en-US.md
src/notice-bar/README.md
src/notice-bar/notice-bar.ts
src/notice-bar/notice-bar.wxml

fix #2370 
- feat(NoticeBar): 新增 `change` 事件，仅在 `direction` 为 `vertical` 时有效

feat(notice-bar): enable event change

---

src/common/utils.ts
src/input/input.ts

- https://github.com/Tencent/tdesign-miniprogram/issues/2103
- https://github.com/Tencent/tdesign-miniprogram/pull/2108
- https://github.com/Tencent/tdesign-miniprogram/issues/2368
- 需求背景
之前的历史问题（<https://github.com/Tencent/tdesign-miniprogram/issues/2103>、<https://github.com/Tencent/tdesign-miniprogram/pull/2108>）的处理方式有误,导致出现了新的问题：<https://github.com/Tencent/tdesign-miniprogram/issues/2368>
- 解决方案
1、历史问题主要是null、undefined没有===严格判断，而是采用==和!等去判断空值，导致把0算进去了。因此用value !== null && value !== undefined 改成严格判断
2、去掉排除类型对长度设置的条件限制。
- 自测示例
- fix(Input): 修复 `type` 为 `digit`、`number`时，`maxlength` 和 `maxcharacter` 属性无效的问题

fix(inputMaxCount): 解决设置最大长度时类型为number、digit不生效问题

---

src/checkbox-group/checkbox-group.ts
src/checkbox/README.en-US.md
src/checkbox/README.md
src/checkbox/checkbox.ts

- [x ] 日常 bug 修复
fix #2395 
- feat(Checkbox):  `change` 事件新增参数 `context`，返回当前点击项内容
- [√ ] 文档已补充或无须补充
- [√ ] 代码演示已提供或无须提供
- [√ ] TypeScript 定义已补充或无须补充
- [√ ] Changelog 已提供或无须提供

fix: 修复checkbox onchange时无dateset数据

---

src/badge/__test__/__snapshots__/demo.test.js.snap
src/badge/__test__/index.test.js
src/badge/_example/base/index.wxml
src/badge/_example/size/index.wxml
src/badge/_example/theme/index.wxml
src/badge/badge.less
src/badge/badge.wxs
src/tab-bar-item/tab-bar-item.less

fix #2416
问题：tabbar红色气泡遮住了底部图标
解决方案：修改tab-bar-item xx-badge-class的样式
修复前：
修复后：
修复tabbar红色气泡遮住了底部图标
- fix(tabbar): 修复tabbar红色气泡遮住了底部图标

fix(tabbar): 修复tabbar红色气泡遮住了底部图标

---

CHANGELOG.md
package.json

chore: publish v1.2.6

---

src/textarea/README.en-US.md
src/textarea/README.md
src/textarea/__test__/index.test.js
src/textarea/textarea.ts

fix #2532 
- feat(Textarea): `change` 事件支持 `cursor` 参数返回

feat(textarea): change event supports cursor parameter return

---

src/tabs/tabs.ts

#2516 
showBottomLine为true或者false时，内容居中逻辑保持一致
- fix(tabs): showBottomLine为false时,内容自动向中间滑动

fix(tabs): showBottomLine为false时,内容自动向中间滑动

---

site/plugin-tdoc/md-to-vue.ts

设计指南更新为 `_common/docs/mobile/design` 路径，后期子仓库 `_common/docs/miniprogram` 文件夹可直接移除

chore: update design path

---

src/image-viewer/image-viewer.ts

使用者提出issue,反馈ImageViewer 图片预览没有设置宽高限制的情况下，图片被截断了,特此修复了公共组件中对纵图处理不当导致图片被裁剪的问题
#2560 
**需求背景**：使用者提出issue,反馈ImageViewer 图片预览没有设置宽高限制的情况下，图片被截断了
**问题定位**：经过通过对多种图片，尤其是该issue中的图片的测试验证发现，该公共组件中对纵图的处理方式不当，导致纵图的宽不能很好的显示而被裁剪。
**解决方案**：优化纵图宽高计算逻辑，使纵图优雅完好的显示。

fix(image.viewer.ts): 修复ImageViewer公共组件对纵图处理不当导致图片被裁剪的问题

---

src/cell/README.md
src/cell/__test__/__snapshots__/index.test.js.snap
src/cell/cell.ts
src/cell/cell.wxml
src/cell/props.ts
src/cell/type.ts
src/collapse/__test__/__snapshots__/index.test.js.snap

fix #2506
- feat(Cell): `leftIcon`、 `rightIcon` 和 `arrow` 属性 `Object` 类型

feat(Cell): leftIcon and rightIcon attributes support object type

---

src/cascader/README.en-US.md
src/cascader/README.md
src/cascader/__test__/__snapshots__/demo.test.js.snap
src/cascader/_example/keys/index.wxml
src/cascader/cascader.ts
src/cascader/cascader.wxml
src/cascader/props.ts
src/cascader/type.ts

https://github.com/TDesignOteam/tdesign-api/pull/231
- feat(Cascader): 新增 `placeholder` 属性，支持自定义未选中时的提示文案

feat(Cascader): add placeholder attr

---

src/slider/__test__/index.test.js
src/slider/slider.ts

修复 slider 在多点触控时无法滑动的问题
fix #2604
https://github.com/Tencent/tdesign-miniprogram/issues/2604
- fix(Slider): 修复 slider 在多点触控时无法滑动的问题 

fix(Slider): 修复 slider 在多点触控时无法滑动的问题

---

src/navbar/__test__/__snapshots__/index.test.js.snap
src/navbar/navbar.ts

fix #2624 
- fix(Navbar): `px` 转 `rpx` 换算错误

fix(navbar): px to rpx conversion error

---

src/avatar/__test__/__snapshots__/demo.test.js.snap
src/avatar/_example/badge-avatar/index.wxml
src/tabs/__test__/__snapshots__/demo.test.js.snap
src/tabs/_example/with-badge/index.wxml

- 处理 Avatar、Tabs 组件示例中徽标位置不对的问题
视觉稿：

fix(Demo): update demo

---

src/check-tag/check-tag.less
src/check-tag/check-tag.ts
src/check-tag/check-tag.wxml
src/check-tag/props.ts
src/tag/README.en-US.md
src/tag/README.md

fix #2364 
不知出于什么考量废弃 `shape` 和 `closable` 属性，经过自测可以实现需求
- feat(CheckTag): 新增 `shape` 和 `closable` 属性

feat(check-tag): enable props shape and closable

---

src/image/README.en-US.md
src/image/README.md
src/image/image.ts
src/image/image.wxml
src/image/props.ts
src/image/type.ts

fix #2638 
- feat(Image): 新增 `t-id` 属性

feat(Image): add props tId

---

src/check-tag/props.ts
src/check-tag/type.ts
src/tag/README.en-US.md
src/tag/README.md
src/tag/props.ts
src/tag/type.ts

https://github.com/TDesignOteam/tdesign-api/pull/260

feat(tag): sync api

---

src/checkbox-group/checkbox-group.ts
src/checkbox-group/checkbox-group.wxml

fix #2726 
- fix(CheckboxGroup): `options` 对象中 `value` 不支持 `number` 类型

fix(checkbox-group): value in options object does not support number type

---

src/navbar/__test__/__snapshots__/index.test.js.snap
src/navbar/_example/back-home/index.wxss
src/navbar/_example/img/index.wxss
src/navbar/_example/left-title/index.wxss
src/navbar/_example/search/index.wxss
src/navbar/_example/skyline/navbar.less
src/navbar/_example/skyline/navbar.wxml
src/navbar/navbar.less
src/navbar/navbar.ts

在不同尺寸设备中右侧胶囊大小均一致，为适配右侧胶囊大小，Navbar 组件恢复使用 px 单位，垂直方向上（容器高度、字体大小、上下边距）也建议改用 px。
- fix(Navbar):  为适配右侧胶囊尺寸，恢复使用 `px` 单位

chore(Navbar): revert to using px units

---

src/tabs/tabs.wxml

fix the issue with the tabs component under Skyline
fix #2786
https://github.com/Tencent/tdesign-miniprogram/issues/2786
- tabs 组件依赖小程序内置的 `scroll-view` 组件，而在 Skyline 渲染模式下 `scroll-view` 组件需要增加 `type` 属性才可以正常运作， 这里加上了 `type="list"`。
- 关于 scroll-view 在 skyline 的属性参见：['说明文档'](https://developers.weixin.qq.com/miniprogram/dev/component/scroll-view.html#Skyline-%E7%89%B9%E6%9C%89%E5%B1%9E%E6%80%A7)
- fix(Tabs): 修复在 Skyline 模式下组件不能正常使用的问题 ...

fix(tabs): 修复在 Skyline 模式下组件不能正常使用的问题

---

src/tabs/__test__/__snapshots__/demo.test.js.snap
src/tabs/__test__/__virtualHostSnapshot__/demo.test.js.snap
src/tabs/_example/base/index.wxml

Fix(Demo-Tabs): 更正一处文案错误“上限三字”

---

src/icon/icon.less

fix #2797 
问题背景：
1. 1.4.0版本name传入链接时必须指定size，否则自定义图片的icon不能正常显示
2. 如果icon组件是其他组件（如cell）的子组件，且需要定义icon为图片时，给其传值就只能传object
需求：像1.3.x版本一样。支持直接给icon传图片链接，也能正常显示
问题分析：icon组件的size属性默认为inherit本身是比较合适的，1.4.0版中icon组件为适配skyline将1em变更为100%，由一个具体宽高值变成需要依赖父容器宽高，带来的问题就是图片资源必须要指定宽高（通过传入size属性、覆盖组件样式等方式处理）。
最终方案：和设计师讨论之后，决定将图片资源的默认宽高取 40rpx， 继续保留icon组件的size属性默认值为inherit。
- fix(Icon): 补充图片资源宽高

fix(Icon): supplementary image width and height

---

jest.config.js
src/action-sheet/_example/align/index.js
src/index.ts
src/toast/_example/base/index.js

目前 package.json 中 main [指定的入口文件并不存在。实际上，在小程序中，我们都是明确地指定要引用的组件文件，而不是默认地引用main属性指向的文件，所以这个属性的作用有限。当然也不排除，部分场景的小程序npm包必须指定main，详见[NPM](https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html)
补充入口文件，对 plugin 组件来说可以简化引入，
```js
import Toast from 'tdesign-miniprogram/toast/index'
// 简化 
import { Toast } from 'tdesign-miniprogram';
```

chore: added npm package entry file

---

site/docs/custom-theme.md
site/docs/dark-mode.md
site/site.config.mjs

docs: add dark mode guide

---

src/check-tag/props.ts

fix #2870
https://github.com/Tencent/tdesign-miniprogram/blob/92e38d0df796dec8cb3f58c768c5fc031d64c7cb/src/common/src/instantiationDecorator.ts#L126
原因分析有以下几点：
- 受到受控和非受控能力影响
- 受控属性优先级大于非受控属性。checked > defaultChecked
- 属性值类型会被强转为指定的属性类型。如a的实际值会被转为false 
```js  
properties: {
a: {
type: Boolean,
value: undefined
}
}
```
- fix(CheckTag):  更正组件内部 `checked`属性类型

fix(CheckTag): fix checked attribute type error

---

src/overlay/props.ts
src/picker/__test__/__snapshots__/index.test.js.snap

fix #2885
在微信小程序中，properties 属性的优先级要高于 behaviors 中的同名属性。
当组件使用了behaviors时，behaviors中定义的属性和方法会被合并到组件中。如果组件本身已经定义了与behaviors中同名的属性或方法，那么组件自身的属性或方法会覆盖behaviors中的同名属性或方法。因此，properties中的visible属性优先级高于behaviors的visible，导致遮罩失效。
- fix(Overlay): 修复遮罩失效

fix(Overlay): resolved visible attr is invalid

---

src/pull-down-refresh/README.en-US.md
src/pull-down-refresh/README.md
src/pull-down-refresh/props.ts
src/pull-down-refresh/pull-down-refresh.ts
src/pull-down-refresh/type.ts
src/swipe-cell/README.en-US.md
src/swipe-cell/README.md
src/swipe-cell/props.ts
src/swipe-cell/swipe-cell.wxs
src/swipe-cell/type.ts

fix #2804
新增 `dragstart` 和 `dragend` 事件，在拖拽过程中禁用下拉刷新
- feat(SwipeCell): 新增 `dragstart` 和 `dragend` 事件
- feat(PullDownRefresh): 新增 `disabled` 属性

feat(swipe-cell): support dragstart and dragend events

---

src/input/__test__/__snapshots__/index.test.js.snap
src/input/__test__/index.test.js
src/input/input.wxml

fix #2937 
背景： wxif + bindtouchstart，点击该事件后dom销毁，当前页面上的其他bindtap事件无效， bindtouchstart事件正常。代码片段：https://developers.weixin.qq.com/s/noGD5mmY76Sc
原因：根本原因是 touchstart 阶段就删除了节点，导致 touchend 没触发
解决方案：两个方向：1.不删除节点（wxif改用hidden）；2.改用tap/touchend 删除节点
方案效果对比：ios
render|方案| 事件效果| 交互效果
--|-- | -- | -- 
webview|-|正常|input内容清除，保持聚焦状态，软键盘不收起
skyline|-|失效|input内容清除，软键盘收起
webview|wxif改用hidden|正常|input内容清除，软键盘收起
skyline|wxif改用hidden|正常|input内容清除，软键盘收起
webview|改用tap|正常|input内容清除，软键盘收起
skyline|改用tap|正常|input内容清除，软键盘收起
webview|改用touchend|正常|input内容清除，软键盘收起
skyline|改用touchend|正常|input内容清除，软键盘收起
在 #1702 中，为达到"清空内容时，软键盘不收起"的交互效果，从 tap 改用 touchstart，当前为了保证skyline render环境下的正常使用和交互效果一致，重新改用 tap，webview环境下的交互效果会变更为“清空内容时，软键盘收起”。
- fix(Input): 修复Skyline下点击清除图标时页面上 `bindtap` 无效

fix(Input): fallback to using tap event

---

script/generate-css-vars.js
src/popup/README.en-US.md
src/popup/README.md
src/popup/__test__/__snapshots__/demo.test.js.snap
src/popup/_example/base/index.wxml
src/popup/popup.less

fix #3028
- feat(Popup): 新增 `--td-popup-close-btn-color`

feat(Popup): update css vars

---

src/cell-group/cell-group.ts

reset lastChild in cell group when a child is unlinked
fix #3052
#3052 
在cell group中有cell被移除时重新计算lastChild来更新border的显示和隐藏
- fix(CellGroup): 修复子项移除时，最后一项下边框显示错误

fix(cell): reset lastChild in cell group when a child is unlinked

---

src/slider/README.md
src/slider/slider.ts

fix #3083 
每次手动调用init都会触发存在bus中的renderLine(defaultValue)，导致dot位置被重置到defaultValue的位置。
通过在init中加入了一个flag检查来解决这个问题，检查是否已经初始化过，如果已经初始化就直接return。
- fix(slider): fix incorrect dot pos caused by repeated manual init

feat(slider): fix incorrect dot pos caused by repeated init

---

src/toast/_example/skyline/toast.wxml
src/toast/_example/toast.wxml

无
Demo 中 t-toast 页存在错别字：弹窗可“现实”遮罩，应为“弹窗可显示遮罩”。

fix(t-toast demo): 错别字“弹窗可‘现实’遮罩”

---

src/collapse-panel/collapse-panel.ts

父级 `collapse` 默认值为`true` ，所以只在 `collapse-panel` 设置 `false` 无效
- fix(collapse): 修复collapse-panel设置expand-icon不生效及支持动态设置diabled

fix(collapse-panel): expandIcon does not take effect

---

src/common/wechat.ts
src/tab-panel/props.ts
src/tab-panel/type.ts
src/tabs/README.en-US.md
src/tabs/README.md
src/tabs/tabs.ts

相关api pr：https://github.com/TDesignOteam/tdesign-api/pull/412
在一开始使用 hidden 隐藏，而 attached 会继续触发，导致无法正确获取布局 width ，最终 tracker 无法正确显示。
- fix(Tabs): 使用 `hidden` 隐藏后显示仍能够正常显示指示器；移除文档中未实现的 `destroyOnHide` 属性

fix(Tabs): enable hidden on the beginning

---

src/avatar-group/avatar-group.json
src/avatar-group/avatar-group.less
src/avatar-group/avatar-group.ts
src/avatar-group/avatar-group.wxml
src/avatar-group/props.ts
src/avatar-group/type.ts
src/avatar/README.en-US.md
src/avatar/README.md
src/avatar/__test__/__snapshots__/demo.test.js.snap
src/avatar/__test__/index.test.js
src/avatar/_example/action/index.js
src/avatar/_example/action/index.wxml
src/avatar/_example/avatar.wxml
src/avatar/avatar.json
src/avatar/avatar.less
src/avatar/avatar.ts
src/avatar/avatar.wxml
src/avatar/avatar.wxs
src/avatar/props.ts
src/avatar/type.ts
src/common/common.ts
src/common/style/_variables.less
src/common/style/theme/_font.less
src/result/result.less
src/swipe-cell/swipe-cell.less

fix #3088
https://github.com/TDesignOteam/tdesign-api/pull/411
https://github.com/Tencent/tdesign-mobile-vue/pull/1571
- fix(AvatarGroup): 修复 `size` 属性无效的问题，优化 `zIndex` 处理
- feat(AvatarGroup): 新增 `shape` 属性，新增 `collapsed-item-click` 事件

fix(AvatarGroup): fixed size attribute being invalid

---

src/image-viewer/__test__/__snapshots__/index.test.js.snap
src/image/README.en-US.md
src/image/README.md
src/image/__test__/__snapshots__/index.test.js.snap
src/image/image.less
src/image/image.ts
src/image/image.wxml

- [*] 日常 bug 修复
fix #3107
- fix(Image): 修复图片在 `loading` 态时，加载错位

docs(image): loading时图片加载错位

---

src/progress/progress.ts
src/progress/progress.wxml

- fix(Progress): 修复环形进度条首次加载时，`strokeWidth` 线宽延迟显示的问题

fix(progress): 移除getInnerDiameter() 并改使用heightBar

---

src/badge/README.md
src/badge/__test__/__snapshots__/demo.test.js.snap
src/badge/_example/theme/index.wxml
src/badge/_example/theme/index.wxss
src/badge/badge.less
src/badge/badge.ts
src/badge/badge.wxml

fix #3130 
Duplicate of #3136 
- fix(Badge):  `ribbon` 类型徽标改用伪元素实现

chore(Badge): use pseudo-element instead

---

src/cascader/cascader.ts

fix #2902
- fix(Cascader): 修复 `value` 动态变更时，`options ` 选项内容未更新的问题

fix(Cascader): 修复value动态变更时，options选项内容未更新的问题

---

src/image-viewer/image-viewer.wxml

- 日常 bug 修复
1、背景：当前页面可以滑动时候，如果使用了image-viewer组件来预览图片，在image-viewer组件层滑动，会出现滚动穿透
2、方案：禁止滚动穿透
- fix(ImageViewer): 修复滚动穿透问题
- 本条 PR 不需要纳入 Changelog

fix(ImageViewer): 修复滚动穿透问题

---

script/test/setup.js
src/common/utils.ts
src/common/version.ts
src/common/wechat.ts
src/fab/draggable/draggable.ts
src/fab/fab.ts
src/image-viewer/image-viewer.ts
src/image/__test__/index.test.js
src/image/image.ts
src/indexes/indexes.ts
src/mixins/theme-change.ts
src/mixins/using-custom-navbar.ts
src/navbar/__test__/__snapshots__/index.test.js.snap
src/navbar/navbar.ts
src/progress/progress.ts
src/pull-down-refresh/pull-down-refresh.ts

fix #3162
- chore: 更新部分不在维护的 wx 接口，并兼容低版本

chore: upgrade wx api

---

src/tabs/tabs.less
src/tabs/tabs.wxml

fix #3169 
表现：scroll-view组件，相同代码在 webview 和 skyline 下表现不一致
可能原因：skyline 实现与 webview 不一致
最小复现片段：https://developers.weixin.qq.com/s/CbNx7OmP7yUE
- fix(Tabs): 修复在 skyline 中无法滚动的问题

fix(Tabs): fixed the problem of not being able to scroll under skyline

---

src/collapse-panel/collapse-panel.less
src/collapse-panel/collapse-panel.ts
src/collapse-panel/collapse-panel.wxml
src/collapse/README.en-US.md
src/collapse/README.md
src/collapse/__test__/__snapshots__/demo.test.js.snap
src/collapse/__test__/__snapshots__/index.test.js.snap
src/collapse/_example/collapse.wxml
src/collapse/_example/theme/index.wxml

fix #3181
- fix(Collapse): 修复禁用+面板展开场景下面板展开态不正确，并处理多个样式问题

fix(Collapse): fix panel disabled style error

---

CHANGELOG.md
package.json

chore: publish v1.6.2

---

src/button/button.less

- fix(Button): 修复深色模式的默认幽灵按钮的边框色错误

fix(Button): fix style for ghost + default

---

src/input/README.en-US.md
src/input/README.md
src/input/__test__/__snapshots__/demo.test.js.snap
src/input/_example/special/index.js
src/input/_example/special/index.wxml
src/input/input.ts
src/input/props.ts
src/input/type.ts

https://github.com/TDesignOteam/tdesign-api/pull/446
- feat(Input): 支持 `format` 属性

feat(Input): support format props

---

src/common/utils.wxs
src/icon/icon.wxml

fix #3212 
- fix(Icon): 修复使用图片链接时偶发性出现字体图标的问题

fix(Icon): check whether the naming is correct

---

src/fab/README.en-US.md
src/fab/README.md

fix #3208
- docs(Fab): 文档补充 `FAQ` 部分

docs(Fab): add FAQ

---

CHANGELOG.md
package.json

chore: publish v1.7.1

---

src/navbar/__test__/__snapshots__/index.test.js.snap
src/navbar/navbar.less
src/navbar/navbar.ts

fix #3302
问题点：
1. getRect方法耗时较长，真机约600ms，会导致navbar位置长时间不准确，所以先设置默认值，再异步获取
2. 部分安卓机型中（已在Magic6/7中复现，可能荣耀Magic系列均能复现🤔），仍存在精度问题，导致翻译功能完成后标题区域仍然隐藏，暂使用 Math.round() 取整规避
- fix(Navbar): 修复 `getRect` 耗时过长导致 `navbar` 位置不准确问题，并兼容部分机型因精度问题导致的翻译功能完成后标题仍然隐藏的问题

fix(Navbar): Fixed getRect caused navbar position to be inaccurate

---

src/dropdown-menu/README.en-US.md
src/dropdown-menu/README.md
src/dropdown-menu/__test__/__snapshots__/index.test.js.snap
src/dropdown-menu/dropdown-menu.less
src/dropdown-menu/dropdown-menu.wxml

fix #3336 
需求背景：针对 #3336 问题，新增 t-dropdown-menu__item--x 类名，通过在页面上覆盖该 class 类名，达到重写 label 样式，请注意样式隔离问题
- fix(DropdownMenu): 修复部分 `css vars` 命名错误

fix(DropdownMenu): fix some CSS variable naming errors

---

src/cascader/README.en-US.md
src/cascader/README.md
src/cascader/_example/cascader.json
src/cascader/_example/cascader.wxml
src/cascader/_example/check-strictly/index.js
src/cascader/_example/check-strictly/index.json
src/cascader/_example/check-strictly/index.wxml
src/cascader/_example/check-strictly/index.wxss
src/cascader/cascader.ts
src/cascader/props.ts
src/cascader/type.ts

fix #3284
#3284
api变更: https://github.com/TDesignOteam/tdesign-api/pull/486
- feature(cascader): 新增 checkStrictly 属性，父子节点选中状态不再关联，可各自选中或取消

feat(cascader): 新增 checkStrictly 属性，父子节点选中状态不再关联，可各自选中或取消

---

src/popup/popup.wxs

fix #3312 
- fix(Popup): 在 `Skyline` 模式下控制台报错

fix(popup): the console reports an error in skyline mode

---

src/fab/README.en-US.md
src/fab/README.md
src/fab/__test__/__snapshots__/demo.test.js.snap
src/fab/_example/draggable/index.js
src/fab/_example/draggable/index.wxml
src/fab/fab.ts
src/fab/template/draggable.wxml

fix #3374
- feat(Fab): 新增 `dragStart` 和 `dragEnd` 事件

feat(Fab): add dragstart and dragend events

---

src/pull-down-refresh/README.en-US.md
src/pull-down-refresh/README.md
src/pull-down-refresh/__test__/__snapshots__/demo.test.js.snap
src/pull-down-refresh/_example/base/index.wxml
src/pull-down-refresh/props.ts
src/pull-down-refresh/pull-down-refresh.less
src/pull-down-refresh/pull-down-refresh.ts
src/pull-down-refresh/pull-down-refresh.wxml
src/pull-down-refresh/type.ts

t-pull-down-refresh的高度原来是100vh，当与t-navbar同用时会有问题，导致底部被遮挡，现增加using-custom-navbar属性以解决这个高度差
相关api pr：https://github.com/TDesignOteam/tdesign-api/pull/498
- fix(PullDownRefresh): 新增 `usingCustomNavbar` 属性，修复与 `Navbar` 同用遮挡底部问题

fix(PullDownRefresh): added usingCustomNavbar property to resolve conflicts when used with t-navbar

---

src/side-bar/side-bar.less
src/tree-select/README.en-US.md
src/tree-select/README.md
src/tree-select/tree-select.ts
src/tree-select/tree-select.wxml

https://github.com/TDesignOteam/tdesign-api/pull/499
- fix(TreeSelect): 修复 `value` 为空数组时组件未渲染，同时补齐外部样式类

feat(TreeSelect): enrich external classes

---

src/tree-select/tree-select.ts
src/tree-select/tree-select.wxml

背景：来自内部业务需求，用于 search + TreeSelect 场景。 customValue 优先级高于 value，与value的区别在于 value 为空数组场景。 
1. value 为 空数组时，默认取每列索引0为选中项
2. 使用 customValue 时，选中值完全由 customValue 决定，这就意味着 customValue 为空数组时，不会有选中项
- feat(TreeSelect): 新增 `customValue` 属性，自定义选中值，用于弥补 `value` 为空数组场景

feat(TreeSelect): support customValue props

---

src/guide/README.en-US.md
src/guide/README.md
src/guide/content.wxml
src/guide/guide.ts
src/guide/guide.wxml
src/guide/props.ts
src/guide/type.ts

fix #h3368
关联pr #3371 
https://github.com/TDesignOteam/tdesign-api/pull/502
- fix(Guide): 修正返回按钮出现时机，并新增 `hideBack` 属性

feat(Guide): support hideButton props

---

src/avatar/avatar.wxml
src/button/button.wxml
src/calendar/template.wxml
src/collapse/__test__/__snapshots__/index.test.js.snap
src/common/template/badge.wxml
src/common/template/button.wxml
src/common/template/icon.wxml
src/common/template/image.wxml
src/dialog/dialog.ts
src/dialog/dialog.wxml
src/dropdown-menu/__test__/__snapshots__/index.test.js.snap
src/empty/empty.wxml
src/fab/fab.ts
src/grid-item/grid-item.wxml
src/input/__test__/__snapshots__/index.test.js.snap
src/message/__test__/__snapshots__/index.test.js.snap
src/notice-bar/__test__/__snapshots__/index.test.js.snap
src/progress/progress.wxml
src/result/result.wxml
src/side-bar-item/side-bar-item.wxml
src/swipe-cell/swipe-cell.wxml
src/swiper/index.wxs
src/swiper/swiper.wxml
src/tabs/tabs.wxml
src/tag/tag.wxml

fix #3377 
背景： Mpx + tdesign-miniprogram 编译报错
原因：tdesign-miniprogram 中， class 是外部样式类， 用于处理开启组件虚拟节点场景问题。 Mpx 会把 class  作为关键字处理，导致编译报错。
方案：对 class 关键字进行移除 or 重命名。
1. button 模版中，涉及到（dialog、calendar）单元测试，保留class，并将其重命名为 rootClass。
2. 其他template模版，对 class 进行移除处理，如有需要，请改用 tClass。
- other(Mpx): 修复在 `Mpx` 框架中编译报错问题

chore(Mpx): compatible with Mpx framework

---

src/stepper/__test__/__snapshots__/index.test.js.snap
src/stepper/stepper.wxml

fix #3452
背景： #3452，仅在 iOS上可复现
方案： 移除图标上的类名（color inherit）
原因：不详
- fix(Stepper): 修复 `Skyline` 中增加和减少按钮动态更新时禁用态样式错误

fix(Stepper): fixed style errors in skyline

---

src/radio-group/props.ts
src/radio-group/radio-group.ts
src/radio-group/type.ts
src/radio/README.en-US.md
src/radio/README.md
src/radio/props.ts
src/radio/radio.ts
src/radio/type.ts

- fix(RadioGroup):增加readonly属性

feat(radiogroup): support readonly props

---

src/cell-group/props.ts
src/cell-group/type.ts
src/cell/README.en-US.md
src/cell/README.md
src/cell/__test__/__snapshots__/demo.test.js.snap
src/cell/__test__/__snapshots__/index.test.js.snap
src/cell/_example/base/index.wxml
src/cell/_example/multiple/index.wxml
src/cell/cell.less
src/cell/cell.wxml
src/cell/props.ts
src/cell/type.ts
src/collapse/__test__/__snapshots__/index.test.js.snap

https://github.com/TDesignOteam/tdesign-api/pull/529
- fix(Cell): 修复部分样式错误，并更新 `align` 属性描述

fix(Cell): fix component style errors

---

CHANGELOG.md
package.json

chore: publish v1.8.6

---

src/guide/guide.ts

fix #3448 
fix #3467 
背景： 组件定位错误
方案：避免使用 bottom 方位定位
- fix(Guide): 修复多个场景组件定位错误

fix(Guide): fixed component positioning errors in multiple scenarios

---

src/toast/README.en-US.md
src/toast/README.md
src/toast/index.ts
src/toast/type.ts

Toast 组件已提供 theme: warning，但 TypeScript 类型缺失。
解决方案：
补充完整组件 ToastType 类型声明并同步 README 文档。
- fix(toast): 新增 warning 主题类型
- [x ] 代码演示已提供或无须提供

fix(toast): 新增 warning 主题类型

---

src/tab-panel/props.ts
src/tab-panel/tab-panel.ts
src/tab-panel/tab-panel.wxml
src/tab-panel/type.ts
src/tabs/README.en-US.md
src/tabs/README.md
src/tabs/props.ts
src/tabs/tabs.ts
src/tabs/type.ts

https://github.com/TDesignOteam/tdesign-api/pull/517
- feat(Tabs):  新增 `bottomLineMode` 属性；`TabPanel` 新增 `lazy` 属性

feat: tabs 新增 bottomLineMode；TabPanel 新增 lazy 属性

---

src/drawer/drawer.less
src/overlay/overlay.wxml
src/popup/_example/base/index.wxss
src/popup/popup.less
src/popup/popup.wxs

fix #3569
- fix(Popup): 当 `placement` 为 `'left' | 'right'` 配合 `usingCustomNavbar` 时，容器高度溢出的问题

fix(popup): deal with container height overflow

---

src/common/utils.wxs
src/upload/README.en-US.md
src/upload/README.md
src/upload/__test__/__snapshots__/demo.test.js.snap
src/upload/_example/multiple/index.js
src/upload/_example/multiple/index.wxml
src/upload/props.ts
src/upload/type.ts
src/upload/upload.wxml

fix #3602
https://github.com/TDesignOteam/tdesign-api/pull/609
- feat(Upload): 组件新增 `addBtn` 和 `removeBtn` 属性，并支持在文件中设置单个图片的 `removeBtn` 属性

feat(Upload): support addBtn and removeBtn props

---

src/action-sheet/show.ts

在当前实现中，`ActionSheetItem` 接口同时在 `src/action-sheet/show.ts` 和 `src/action-sheet/type.ts` 文件中定义，这导致了类型定义与文档中提供的不一致:
https://github.com/Tencent/tdesign-miniprogram/blob/962fe6ee3b69ee927873ee831f098588f93775da/src/action-sheet/show.ts#L3-L9
https://github.com/Tencent/tdesign-miniprogram/blob/81700eb2de2b5c87786dc133d349c3c838963053/src/action-sheet/type.ts#L108-L114
- 从 `src/action-sheet/show.ts` 文件中移除了 `ActionSheetItem` 接口的定义
- 改为从 `type.ts` 文件中导入 `ActionSheetItem` 接口并重新导出
- 保持了接口的功能和使用方式不变

fix(action-sheet): fix inconsistency between type definition and documentation

---

src/cascader/README.en-US.md
src/cascader/README.md
src/cascader/cascader.wxml
src/input/README.en-US.md
src/input/README.md
src/input/__test__/__snapshots__/demo.test.js.snap
src/input/_example/suffix/index.wxml
src/input/_example/suffix/index.wxss

fix #3615
https://github.com/TDesignOteam/tdesign-api/pull/613
Cascader：新增 `header` 插槽，用于自定义内容头部
其他： 补充 #3614 API 文档，更新 input 示例
- feat(Cascader）：新增 `header` 插槽，用于自定义内容头部

feat: supplementary slots

---

script/update-icons.js

chore(update-icons): sync update icon/icon.less

---

src/color-picker/__test__/__snapshots__/demo.test.js.snap
src/color-picker/_example/format/index.js
src/color-picker/_example/format/index.wxml
src/color-picker/_example/format/index.wxss

chore: color-picker example adapts to dark mode

---

src/pull-down-refresh/pull-down-refresh.ts

#2387
fix #2387
- fix(PullDownRefresh): 修复配置 `scroll-into-view` 不生效问题

fix(PullDownRefresh): 修复配置scroll-into-view不生效问题

---

src/link/link.ts

[navigator](https://developers.weixin.qq.com/miniprogram/dev/component/navigator.html) 的 `open-type="navigate"` 时，也可以通过指定 `app-id` 或者 `short-link` 跳转到其他小程序。目前只检查了 `url` 参数，会造成需要跳转到小程序的 `link` 的样式为 `disabled`。
增加检查 `navigatorProps` 中的 `appId` 和 `shortLink` 参数。
- fix(Link): 修复在 `navigatorProps` 中只指定 `appId` 或者 `shortLink` 且 `target="miniProgram"` 时样式为禁用状态的问题

fix(link): disabled style condition judgment is missing

---

src/toast/_example/toast.less
src/toast/_example/toast.wxml
src/toast/toast.less

fix #3707
skyline 不支持 fit-content，改用 flex 布局
- fix(Toast): 使用 `flex` 替换 `fit-content`，兼容 `skyline` 场景

fix(Toast): fit-content is not supported under skyline

---

script/gulpfile.base.js

问题： 
TD旧版本（1.8.5）引用后编译正常，无此错误。
控制台报错信息：
app.less引用 @import '/miniprogram_npm/tdesign-miniprogram/common/style/theme/_index.wxss';
编译后出现语法错误：[ WXSS 文件编译错误] 
SyntaxError: media definitions require block statements after any features in D:\xx\miniprogram\miniprogram_npm\tdesign-miniprogram\common\style\theme\_index.wxss on line 1, column 37:(env: Windows,mp,1.06.2506102; lib: 3.7.12)
原因：
1. 媒体查询规则破坏
2. 结尾多处缺少分号
改动点：
新增 gulp-clean-css 压缩规则（1. 避免破坏 @media 规则；强制保留末尾分号）
- fix(build): 修复 `1.9.0` 版本在 `Windows` 环境下 `WXSS` 文件编译错误

chore: add css file compression rules

---

src/fab/README.md
src/indexes/README.md

docs: add FAQ

---

.vscode/settings.json
src/picker/README.md
src/picker/_example/picker.wxml

docs: update picker docs

---

src/indexes/README.en-US.md
src/indexes/README.md
src/indexes/__test__/__snapshots__/demo.test.js.snap
src/indexes/_example/base/index.js
src/indexes/_example/base/index.wxml
src/indexes/indexes.ts
src/indexes/indexes.wxml
src/indexes/props.ts
src/indexes/type.ts

fix #2295 
https://github.com/TDesignOteam/tdesign-api/pull/660
- feat(Indexes): 新增 `current` 属性，支持非受控模式，用于自定义索引列表激活项

feat(Indexes): support current prop

---

src/common/style/theme/_components.less
src/switch/switch.less
src/switch/switch.wxml

https://github.com/Tencent/tdesign-mobile-react/pull/687
- fix(Switch): 修复 `loading` 颜色、`dot` 滑块禁用态/深色模式背景色错误

fix(Switch): fixed multiple color value errors

---

src/mixins/transition.ts
src/transition/__test__/index.test.js

#3567 
#1219 
#2798 
需求背景：在 A 页面点击 ActionSheet 选项跳转到 B 页面，返回 A 页面后，安卓设备上点击 ActionSheet 无响应。以及偶现Toast已隐藏，但是页面无法点击。测试中发现ActionSheet和Toast的overlay未正常消失，导致后续点击失效。主要原因中是在动画执行过程中，transitionend 事件绑定的onTransitionEnd 方法偶现未触发。
解决方案：增加兜底逻辑，确保动画结束后 overlay必然消失。
- fix(actionsheet): 页面跳转返回后再点击不显示问题
- fix(toast)：修复toast已隐藏，页面无法点击问题

fix(ActionSheet): 页面跳转返回后再点击不显示问题

---

src/textarea/README.en-US.md
src/textarea/README.md
src/textarea/__test__/__snapshots__/index.test.js.snap
src/textarea/props.ts
src/textarea/textarea.wxml
src/textarea/type.ts

fix #3824
https://github.com/TDesignOteam/tdesign-api/pull/689
- feat(Textarea): 新增 `cursorColor` 属性，仅在 `Skyline` 下有效

feat(Textarea): support cursorColor prop

---

script/generate-css-vars.js
src/common/style/_variables.less
src/image-viewer/README.en-US.md
src/image-viewer/README.md
src/image-viewer/image-viewer.less
src/image-viewer/image-viewer.wxml
src/image-viewer/props.ts
src/image-viewer/type.ts
src/overlay/README.en-US.md
src/overlay/README.md
src/overlay/overlay.less
src/toast/README.en-US.md
src/toast/README.md
src/toast/toast.less

fix #3842 
https://github.com/TDesignOteam/tdesign-api/pull/694
https://github.com/Tencent/tdesign-common/pull/2245
解决方案：移除 backgroundColor 属性默认值，改用 design token。token 使用 @mask-active (已和设计同学确认✅）
- fix(ImageViewer): 移除 `backgroundColor` 属性默认值，导航背景色固定为 `#000`，遮罩背景色使用 `@mask-active`

fix(ImageViewer): correct the default value of the backgroundColor

---

site/docs/overview.md

将下图所示概览页的“Guide 按钮”更正为“Guide 引导”

fix(docs): 更正 overview 错误文案

---

src/date-time-picker/date-time-picker.ts

fix #3860
当组件开启 `show-week` 且 `start="{{nowTime()}}"` 时，「日」列表界面与未开启 `show-week` 的「日」列表界面不一致：
1. 开启 `show-week` 时「日」列显示了 `nowTime()` 之前的日期，关闭 `show-week` 后则消失。
2. 开启 `show-week` 时，steps 步长设置对「日」不生效，关闭则正常。
应该是在 `getOptionByType(type: string)` 函数中，`if (type === 'date' && showWeek)` 直接返回了 `getDaysOfWeekInMonth(this.date)` 的结果，忽视了 `start`、`end` 和 `steps` 值。
https://github.com/Tencent/tdesign-miniprogram/blob/b3bdc825a060f65fb61e48384ba54c7f666b220a/src/date-time-picker/date-time-picker.ts#L104-L121
我这里把上述函数代码改成以下代码就可以了：
```JavaScript
getDaysOfWeekInMonth(date: Dayjs, type: string): Array<{ value: string; label: string }> {
const { locale, steps, dayjsLocale } = this.data;
const startOfMonth = date.startOf('month');
const minEdge = this.getOptionEdge('min', type);
const maxEdge = …
```

fix(DateTimePicker): 修复在 showWeek 模式下日列表未正确排除 start、end、且 steps 步长不生效的 Bug

---

packages/components/swiper/README.en-US.md
packages/components/swiper/README.md
packages/components/swiper/swiper.ts
packages/components/swiper/swiper.wxml

fix #3883
https://github.com/TDesignOteam/tdesign-api/pull/708
- feat(Swiper): 新增 `animationfinish` 事件

feat(Swiper): add animationfinish event

---

packages/components/step-item/step-item.less

https://github.com/Tencent/tdesign-common/pull/2269
1. title 和 description 间距为 4px
2. 子项之间间距 8px
- fix(StepItem): 修复 `title` 和 `description` 之间的间距错误

fix(steps): fix the spacing error between title and description

---

packages/components/picker-item/picker-item.json
packages/components/picker-item/picker-item.less
packages/components/picker-item/picker-item.ts
packages/components/picker-item/picker-item.wxml
packages/components/picker-item/type.ts
packages/components/picker/README.en-US.md
packages/components/picker/README.md
packages/components/picker/__test__/__snapshots__/demo.test.js.snap
packages/components/picker/_example/base/index.js
packages/components/picker/props.ts
packages/components/picker/type.ts

fix #3891
https://github.com/TDesignOteam/tdesign-api/pull/717
其他：
问题： skyline 下出现，key 不唯一带来的控制台告警。
原因/方案：wx:key="index“ 的设置并不能确保在数据列表改变时触发渲染层重新排序， wx:key 必须具备唯一性。本次将 wx:key 调整为 value，只能解决列表中存在 value 字段且唯一的场景出现的控制台告警，一旦传入的列表没有 value 字段，也会出现控制台告警。ActionSheet 、Cascader 等支持传入列表项的组件应该都有该类问题，或者这里需要重新制定规则，补充 id 属性（必须），并将 id 作为唯一键使用⚠️
- feat(PickerItem):  子项支持 `icon` 属性

feat(PickerItem): add icon prop
