Tencent/tdesign-miniprogram

src/grid/grid-item.wxml

fix(grid):Update grid-item.wxml

---

package.json
src/steps/README.md

fix(steps): resolve demo mistake

---

src/tag/README.md

feat(tag): complete demo

---

src/common/common.ts
src/textarea/README.md
src/textarea/props.ts
src/textarea/type.ts

feat(textarea): add externalClasses

---

src/stepper/README.md
src/stepper/props.ts
src/stepper/type.ts

feat(stepper): complete document

---

src/radio/README.md

fix(site): correct radio demo

---

site/app.vue

feat: official website add search

---

site/index.html
site/package.json

feat: website add horizon

---

src/tab-bar/tab-bar-item.less
src/tab-bar/tab-bar-item.wxml

fix(tabbar): optimize code

---

src/loading/loading.less
src/loading/loading.ts
src/loading/loading.wxml

fix(loading): correct classname

---

site/docs/getting-started.md

docs: upadte getting-started document

---

src/input/input.wxml
src/input/props.ts
src/input/type.ts

移除废弃属性：`auto-focus`
具体可以关注小程序文档。
resolve #47

refactor(input): remove deprecated property

---

src/steps/step-item.ts
src/steps/step-item.wxml
src/steps/steps.ts
src/steps/steps.wxml
src/steps/styles/_index.less
src/steps/styles/_mixin.less
src/steps/styles/_var.less

Steps 修改：
- 规范化ClassName，满足 BEM 规范
- 优化less的写法，使用 less variable

feat(steps): optimize classname and less

---

package.json
src/dialog/dialog.less
src/dialog/dialog.ts
src/dialog/dialog.wxml

fix(dialog): optimize code

---

src/avatar/README.md
src/avatar/avatar-group.ts

- 补充 avatar-group externalClasses, 使 t-class 生效
- 更新 avatar-group 示例

fix: avatar-group externalClasses

---

src/picker/picker-column.less

修复：官网上 DataTimePicker 渲染异常。
resolve #76 #75

fix(data-time-picker): resolve preview error

---

src/date-time-picker/date-time-picker.ts
tsconfig.json

修复：开发时执行 `npm start` 会抛异常：
```
Cannot find module：`dayjs`
```

fix(dev): resolve error when exec npm start

---

site/docs/getting-started.md

docs: update getting started document

---

src/popup/popup.ts

fix(popup): correct event param

---

src/checkbox/checkbox.wxml

Checkbox：content 和 label 支持 slot
resolve #74

fix(checkbox): support label and content slot

---

.husky/commit-msg
.husky/pre-commit
.husky/prepare-commit-msg
commitlint.config.js
package.json

新增 commitlint，规范化 commit message

refactor: normalize commit message

---

src/cell/README.md
src/cell/cell.ts
src/cell/cell.wxml
src/cell/props.ts
src/cell/type.ts
src/common/common.ts

Cell：
- 修正文档中 API 的错误
- 规范话使用 prefix
resolve #101

fix(cell): correct document & use prefix

---

example/pages/popup/popup.ts

fix(popup): use param correctly

---

src/tab-bar/props.ts
src/tab-bar/tab-bar-item.less
src/tab-bar/tab-bar-item.ts
src/tab-bar/tab-bar-item.wxml
src/tab-bar/type.ts

Tabbar: 新增 split 属性控制是否展示分割线
resolve #86

feat(tabbar): add property to control split line

---

example/pages/tag/tag.ts
example/pages/tag/tag.wxml
src/tag/README.md
src/tag/check-tag-props.ts
src/tag/check-tag.ts
src/tag/check-tag.wxml
src/tag/props.ts
src/tag/styles/_index.less
src/tag/tag.wxml
src/tag/type.ts

Tag:
**breaking changes**
- `variant` 属性变更:
- `plain` -> `outline`
- `mixed` -> `light-outline`
**feature**
- check-tag 新增支持 defaultChecked 非受控属性
**bug fix**
- check-tag 完善 change 事件
- tag 无法正常使用 icon 的问题

fix(tag): support controlled property: checked

---

example/pages/input/input.ts
example/pages/input/input.wxml
src/input/README.md
src/input/input.wxml

feat(input): support two way bindings

---

example/pages/badge/badge.less
src/badge/badge.less
src/badge/badge.wxml
src/badge/badge.wxs

fix(badge): fix badge basic style

---

src/search/search.ts

fix(search): fix blur and focus params

---

example/pages/button/button.wxml
src/button/button.less
src/button/button.ts
src/button/button.wxml

Button：修复 disabled 时仍会触发 tap 事件的问题

fix(button): support disabled property correctly

---

example/pages/switch/switch.ts
example/pages/switch/switch.wxml
src/switch/README.md
src/switch/props.ts
src/switch/switch.ts
src/switch/type.ts

refactor(switch): support uncontrolled property: defaultValue

---

example/pages/steps/steps.ts
example/pages/steps/steps.wxml
src/steps/README.md
src/steps/props.ts
src/steps/steps.ts
src/steps/type.ts

refactor(steps): turn into controlled component

---

example/pages/search/search.ts
example/pages/search/search.wxml
src/search/README.md
src/search/props.ts
src/search/search.ts
src/search/search.wxml
src/search/type.ts

Search:
- 支持受控
- 属性变更：
- `actionText` -> `action`
- `keyword` -> `value`

refactor(search): turn into controlled component

---

example/pages/tab-bar/tab-bar.wxml
src/tab-bar/README.md
src/tab-bar/props.ts
src/tab-bar/tab-bar-item-props.ts
src/tab-bar/tab-bar.ts
src/tab-bar/type.ts

refactor(tabbar): turn into under controlled component

---

example/pages/stepper/stepper.ts
example/pages/stepper/stepper.wxml
src/stepper/README.md
src/stepper/props.ts
src/stepper/stepper.ts
src/stepper/type.ts

refactor(stepper): turn into under controlled component

---

example/pages/tabs/tabs.wxml
src/tabs/README.md
src/tabs/props.ts
src/tabs/tab-panel-props.ts
src/tabs/tabs.ts
src/tabs/type.ts

refactor(tabs): turn into under controlled component

---

src/common/src/instantiationDecorator.ts
src/upload/README.md
src/upload/props.ts
src/upload/type.ts
src/upload/upload.ts

Upload:
- 支持非受控
- 升级使用新 API ：`wx.chooseMedia`

refactor(upload): support uncontrolled and update api

---

example/pages/textarea/textarea.wxml
src/textarea/README.md
src/textarea/props.ts
src/textarea/textarea.wxml
src/textarea/type.ts

Textarea:
- 属性变更：`name` -> `label`

refactor(textarea): replace name property with label

---

example/pages/cell/cell.less
example/pages/cell/cell.wxml
src/cell/cell.less

fix(cell): complete default style

---

example/pages/divider/divider.less
example/pages/divider/divider.wxml
src/divider/divider.less
src/divider/divider.ts
src/divider/divider.wxml

fix(divider): complete default style

---

src/dialog/README.md
src/dialog/dialog.ts
src/dialog/dialog.wxml
src/dialog/type.ts

Dialog: 增加一个外部样式类：t-class-content
resolve #115

feat(dialog): add new external class

---

example/pages/steps/steps.wxml
src/steps/step-item.ts
src/steps/step-item.wxml
src/steps/steps.ts
src/steps/styles/_mixin.less
src/steps/styles/_var.less

Steps: 
- 视觉更新
- 修复视觉问题： 可操作状态不区分是否完成
- 
resolve #136

fix(steps): upgrade component style

---

src/rate/README.md

feat: update rate's readme.md and add demo

---

src/tab-bar/props.ts

fix(tab-bar): resolve value not work

---

example/pages/popup/popup.less
example/pages/popup/popup.wxml
src/popup/popup.wxml

fix(popup): fix popup default slot

---

src/image/image.ts

记录image组件传入的src防止在src相同时重复更新导致一直处于update状态

fix:记录image组件传入的src防止在src相同时重复更新

---

src/tag/tag.ts
src/tag/tag.wxml

feat(tag): add external classes for tag

---

example/components/demo-block/index.wxml
example/pages/back-top/back-top.less
example/pages/back-top/back-top.wxml
example/pages/indexes/indexes.less
example/pages/indexes/indexes.wxml
example/pages/loading/loading.less
example/pages/loading/loading.wxml

Indexs(demo):
- 修改demo中对Button组件的使用
Loading(demo):
- 修改demo中对Button组件的使用
Back-top(demo):
- 修改demo中对Button组件的使用
demo-block(demo component):
- 修改demo-block中对Button组件的使用

fix(page-demo): fix the usage of button in multiple pages

---

.prettierrc.yml
package.json
src/popup/popup.less

Toast: 修复 z-index 低于 Popup 的问题
resolve #226

fix(toast): increase the z-index value to over popup

---

src/message/message.less
src/popup/popup.less
src/toast/toast.less

Message: 提升 z-index 从 5000 到 15000
Popup: 提升 z-index 从 1500 到 11500
Toast: 提升 z-index 从 2000 到 12000
resolve #227

refactor: increase z-index value

---

src/toast/index.ts
src/toast/toast.ts
tsconfig.json

Toast: 修复调用时没重置默认值的问题
resolve #225

fix(toast): resolve issue #225

---

src/common/template/button.wxml
src/dialog/dialog.less
src/dialog/dialog.wxml

Dialog:
- 修复 Dialog 内 Button 样式错误

fix(dialog): correct button style

---

src/common/common.ts
src/tag/README.md
src/tag/check-tag-props.ts
src/tag/props.ts
src/tag/type.ts

docs(tag): changes for document of tag component

---

example/pages/rate/rate.ts
example/pages/rate/rate.wxml
src/rate/README.md
src/rate/rate.wxml

fix(skip): fix: 修复rate组件评分为0无法点击的问题

---

src/avatar/avatar.less
src/avatar/avatar.wxml
src/dialog/dialog.less
src/dialog/dialog.wxml
src/input/input.less
src/textarea/textarea.less
src/textarea/textarea.wxml

Input：
- 修复组件中选择器使用不规范问题
Dialog：
-  修复组件中选择器使用不规范问题
Textarea:
-  修复组件中选择器使用不规范问题
Avater:
-  修复组件中选择器使用不规范问题

fix: resolve warning from invalid css selector

---

example/pages/upload/upload.ts
example/pages/upload/upload.wxml
src/upload/upload.ts

fix(upload): support uploading images and videos at the same time

---

src/button-group/button-group.ts
src/button/button.ts
src/common/version.ts

fix(button): solve the problem of console ERROR  under version 2.9.5

---

src/button/button.wxml

Button: 修复 type 属性没正确实现的问题
resolve #253 
resolve #251

fix(button): correct implementation of type

---

src/input/input.ts

fix(input): enable to get value by form

---

src/checkbox/checkbox.ts
src/radio/radio.ts
src/switch/switch.ts

给Switch、Checkbox、Radio等组件使用内置 behaviors

fix: use built-in behaviors for multiple components

---

src/button/README.md
src/button/button.wxml
src/button/props.ts
src/button/type.ts

feat(button): add new prop customDataset

---

example/pages/button/button.less
example/pages/button/button.wxml
src/button/README.md
src/button/button.less
src/button/button.ts
src/button/button.wxml

-Button
icon和文本间距：l——8px，m——4px，s——4px
loading和文本间距：l——8px，m——4px，s——4px

fix(button): add space for icon and text

---

src/image/README.md
src/image/image.less
src/image/image.wxml
src/image/props.ts
src/image/type.ts

add shape property, change property name of loadFailed to error

feat(image): update api

---

src/image/README.md
src/image/image.wxml
src/image/props.ts

Image: 属性 `lazy-load` 变更为 `lazy`

fix(image): remove duplicated property

---

example/pages/loading/loading.wxml
src/loading/loading.ts

Loading：默认loading改为展示，支持`<t-loading /> `能直接展示

fix(loading): change default show to true

---

src/textarea/textarea.ts
src/textarea/textarea.wxml

Textarea
- 修复与Form联用时，无法通过name获取value的问题

fix(textarea): enable to get value by form

---

src/upload/README.md
src/upload/props.ts
src/upload/type.ts
src/upload/upload-info.json
src/upload/upload.json
src/upload/upload.wxml

Image: 底层使用 `t-image` ，并支持 `image-props`  属性透传至 `t-image`

feat(upload): using t-image and support image-props

---

src/search/search.ts

- Search
submit事件返回数据结构与API文档对齐

fix(search): submit event is aligned with the API document

---

example/pages/rate/rate.wxml

fix(skip): fix: rate组件示例修改颜色默认值

---

example/pages/input/input.ts
example/pages/input/input.wxml
src/input/input.ts
test/utils/getDemoPath.js

Input: 修复设置 clearable ，点击不清除内容的问题
resolve #290

fix(input): enable to clear

---

src/message/message.ts

修改行为 233 行，qq 小程序的 message 弹框的显示动画需将 wrapTop 和 showAnimation 分开来设置。否则弹框不显示；
其余为格式自动修正；

fix(message): change setData order when showing message

---

example/pages/steps/steps.ts
example/pages/steps/steps.wxml
src/steps/README.md
src/steps/props.ts
src/steps/step-item-props.ts
src/steps/step-item.less
src/steps/step-item.ts
src/steps/step-item.wxml
src/steps/steps.ts
src/steps/type.ts

feat(steps): add child-step in vertical direction

---

example/app.json
example/pages/home/home.json

示例项目首页对自定义组件的引用在  QQ 小程序中的引入需在对应的页面的 usingComponents 中，否则编译出来的小程序报路径错误找不到组件；

fix(example): change the component path of home page

---

src/steps/step-item.ts

- steps
- 更新step状态判断函数
- 新增两种边界条件（1.secondStep存在，子步骤条为default时，其stepItem状态应为process；2.secondStep存在，子步骤条为finish且不为最后一个子步骤时，其stepItem状态应为proces）

perf(steps): update step-status mode && addboundary condition

---

src/tabs/tabs.wxml

Tabs: 属性 `label` 支持 slot
resolve #306

fix(tabs): support label slot

---

example/pages/home/data/ux.ts
example/pages/progress/progress.json
example/pages/progress/progress.less
example/pages/progress/progress.ts
example/pages/progress/progress.wxml
src/progress/README.md
src/progress/progress.less
src/progress/progress.ts
src/progress/progress.wxml
src/progress/props.ts
src/progress/type.ts
src/progress/utils.ts

feat(progress): update Progress component

---

example/pages/radio/radio.ts
example/pages/radio/radio.wxml
src/common/src/instantiationDecorator.ts
src/radio/README.md
src/radio/props.ts
src/radio/radio-group-props.ts
src/radio/type.ts

Radio:
- 更新文档
- 优化非受控用法，支持不传值时默认非受控
**before**
```html
<t-radio defaultChecked="{{false}}" />
```
**now**
```html
<t-radio />
```

fix(radio): resolve uncontrol usage & update document

---

src/dialog/dialog.ts

fix(dialog): complete close event params

---

src/textarea/textarea.wxml

- Textarea
支持adjust-position键盘推起

fix(textarea): support adjust-position

---

src/steps/README.md
src/steps/step-item.ts
src/steps/step-item.wxml

- Steps
1. 优化步骤条status的判断逻辑。 步骤条状态优先级：status > currentStatus > 子步骤影响，子步骤影响优先级： finish > error > process
2. 支持子步骤条传入自定义status
3. 更新README.md文档

fix(steps): support subStep status && fix README.md error

---

src/icon/README.md

docs(icon): update docs

---

example/pages/switch/switch.wxml
src/switch/props.ts

Switch: 修复无法使用的问题
resolve #360

fix(switch): repair not work

---

package.json
src/badge/index.ts
src/tag/type.ts

fix: remove compile errors

---

example/pages/action-sheet/constants.ts
src/action-sheet/action-sheet.ts
src/action-sheet/index.ts

Actionsheet: 修复 TypeScript 类型问题

fix(actionsheet): resolve types

---

example/pages/tabs/tabs.ts
example/pages/tabs/tabs.wxml
src/tabs/tabs.ts

feat(tabs): add onClick event

---

example/pages/drawer/drawer.ts
src/drawer/drawer.less
src/drawer/drawer.wxml

fix(drawer): fix props.items property

---

example/README.md
script/gulpfile.base.js

1. 在微信ide的模板场景中，源码里添加readme 项目介绍文档。
2. 在gulpfile中copy .md 文件到__example目录

在微信ide的模板场景中，源码里添加readme 项目介绍文档

---

example/pages/grid/grid.wxml
src/grid/grid-item.wxml

resolve #385 
添加默认 slot
- fix(grid): 补充默认 slot

fix(grid): add default slot

---

site/site.config.mjs
src/action-sheet/README.md

docs(site): fix actionsheet site configuration error

---

src/tag/README.md

fix(tag): update tag docs

---

src/button/button.wxml

无
无
- fix(button): 调整 default slot 的位置至最外层

fix(button): move default slot placement

---

example/pages/pull-down-refresh/pull-down-refresh.json
example/pages/pull-down-refresh/pull-down-refresh.less
example/pages/pull-down-refresh/pull-down-refresh.ts
example/pages/pull-down-refresh/pull-down-refresh.wxml
src/pull-down-refresh/README.md
src/pull-down-refresh/props.ts
src/pull-down-refresh/pull-down-refresh.less
src/pull-down-refresh/pull-down-refresh.ts
src/pull-down-refresh/pull-down-refresh.wxml
src/pull-down-refresh/type.ts

resolve #369 
移除冗余的 properties
- fix(PullDownRefresh): 修复无法使用的问题

fix(pull-down-refresh): enable to use

---

example/pages/date-time-picker/date-time-picker.wxml
src/date-time-picker/date-time-picker.ts
src/date-time-picker/date-time-picker.wxml
src/picker/picker-item.ts

resolve #406 
无
- fix(datetime-picker): 修复 defaultValue 不可用的问题
breakingChanges: value 改成受控

fix(datetime-picker): resolve default value

---

src/picker/picker-item.ts

resolve #355
Picker 滑动响应慢
- fix(picker): 优化滑动的响应速度

fix(picker): reduce transition duration

---

package.json

update tdesign-qq-miniprogram // 获取系统信息
- feat:更新QQ组件库version ...

feat: update npm version

---

src/tabs/README.md
src/tabs/tabs.wxml

resolve #416 
由于小程序的限制，暂时无法实现 label 的 slot。
解决方案：
- 移除代码中的错误实现
- 修正文档

fix(tabs): remove not work label slot

---

src/tab-bar/tab-bar-item.less
src/tab-bar/tab-bar.less

https://github.com/Tencent/tdesign-miniprogram/issues/411
- fix(tabbar): fix console warning && remove useless css

fix(tabbar): fix console warning && remove useless css

---

example/pages/avatar/avatar.less
src/avatar/README.md
src/avatar/avatar-group.wxml
src/avatar/avatar.less
src/avatar/avatar.wxs
src/avatar/type.ts

resolve #421
https://github.com/Tencent/tdesign-miniprogram/issues/421
icon 随头像尺寸相应改变
- fix(Avatar): fix icon and text's size

fix(avatar): fix icon and text's size

---

src/indexes/README.md

- [√] 演示代码改进
- [√ ] 本条 PR 不需要纳入 Changelog
- [√ ] 文档已补充或无须补充
- [√ ] 代码演示已提供或无须提供
- [√ ] TypeScript 定义已补充或无须补充
- [√ ] Changelog 已提供或无须提供

 docs: modify the README.md of the indexes component

---

src/action-sheet/action-sheet.less
src/image-viewer/image-viewer.less
src/image-viewer/image-viewer.wxml
src/picker/picker-item.less
src/steps/step-item.less
src/steps/steps.less

https://github.com/Tencent/tdesign-miniprogram/issues/430
- fix(steps&&image-viewer&&picker&&action-sheet): fix console warning && remove useless css

fix: fix multiple components by fix console warning && remove useless css

---

src/input/README.md
src/input/input.ts
src/input/input.wxml
src/input/props.ts
src/input/type.ts

resolve #359 
- 完善 `change` 事件，增加返回 `cursor` 和 `keyCode` 数据
- 增加 `keyboardheightchange` 事件，键盘高度发生变化的时候触发
- 增加占位符相关属性：`placehoderStyle` 和 `placeholderClass`
- 增加光标相关属性：`cursor`、`selection-start`、`selection-end`
- 增加 `hold-keyboard` 属性
- 增加安全键盘相关属性

feat(input): enrich props

---

src/button/button.ts
src/button/button.wxml

- feat(button): add bindchooseavatar props

feat(button): add bindchooseavatar props

---

src/input/README.md
src/upload/README.md

fix(input&upload): fix docs

---

src/empty/README.md
src/empty/_example/empty-page.less
src/empty/_example/empty-page.wxml
src/empty/_example/empty.less
src/empty/_example/empty.wxml

- fix(empty): demo align design

fix(empty): demo align design

---

src/progress/_example/progress.ts

- fix(progress): 修复交互示例中percentage值超出100的问题

fix(progress): [demo] control percentage value is in [0, 100]

---

src/sticky/sticky.ts
src/sticky/utils.ts

- fix(sticky): 添加获取page实例时null值判断

fix(sticky): add sticky null judge

---

src/action-sheet/README.md

docs(actionsheet): update readme

---

src/skeleton/README.md
src/skeleton/_example/skeleton.less
src/skeleton/_example/skeleton.wxml
src/skeleton/skeleton.less

- feat(skeleton): 添加skeleton组件基础默认样式

feat(skeleton): add default component style

---

src/dropdown-menu/dropdown-item.less
src/dropdown-menu/dropdown-item.wxml

无
下拉菜单的遮罩层位置不对
- fix(dropdown-menu): 修正遮罩层的位置，以及下拉菜单的高度

fix(dropdown-menu): move overlay to correct position

---

src/dropdown-menu/dropdown-menu.ts
src/dropdown-menu/dropdown-menu.wxml

null
下拉菜单选项的点击区域过于小，导致无法更方便地点击
- fix(dropdown-menu): 修复菜单选项点击区域过小的问题

fix(dropdown-menu): expand tap area

---

src/back-top/_example/back-top.ts
src/back-top/_example/back-top.wxml
src/back-top/back-top.ts

- fix(backtop): triggerevent 事件名用kebab case格式与文档对齐

feat: change trigger event name to kebab case

---

USED.md
package.json
site/plugin-tdoc/component.vue
site/plugin-tdoc/md-to-vue.ts

chore: 优化文档展示

---

src/collapse/collapse.ts
src/collapse/collapse.wxml

resolve #471 
- fix(collapse): 修复 t-class 外部样式类无法使用的问题

fix(collapse): correct external class

---

src/sticky/sticky.less
src/sticky/sticky.ts

resolve #463 
- fix(sticky): 修复吸顶后 tabs 无法滑动的问题

fix(sticky): resolve style problem

---

src/dropdown-menu/dropdown-item.ts
src/dropdown-menu/dropdown-menu.wxml

resolve #472 
- fix(dropdown-menu): 修复 label 无法实时更新的问题

fix(dropdown-menu): make label sync

---

script/gulpfile.base.js

build: add extra json to dist

---

src/tab-bar/tab-bar-item.wxml

- fix(tabbar): 补充缺失的 icon slot

fix(tabbar): add icon slot

---

src/tabs/README.md
src/tabs/tabs.less

resolve #479 
- fix(tabs): 修复在 popup 中使用时丢失 tab-nav 的问题

fix(tabs): used in popup

---

src/button/README.md
src/button/button.wxml
src/button/props.ts
src/button/type.ts

resolve #476 
- feat(button): 新增 `iconProps` 透传至 `icon`

feat(button): add icon-props

---

src/common/utils.ts
src/input/input.ts

resolve #493 
- fix(input): 修复 `max-character`不生效的问题

fix(input): enable max-characters

---

src/input/input.less
src/input/input.wxml

无
补充实现 prefix-icon 
- feat(input): 新增 `prefixIcon` 属性和插槽

feat(input): support prefix icon property and slot

---

src/pull-down-refresh/README.md
src/pull-down-refresh/_example/pull-down-refresh.json
src/pull-down-refresh/_example/pull-down-refresh.less
src/pull-down-refresh/pull-down-refresh.less
src/pull-down-refresh/pull-down-refresh.ts
src/pull-down-refresh/pull-down-refresh.wxml

resolve #450 
- fix(pulldownRefresh): 修复使用组件之后无法滚动的问题

refactor(pulldownRefresh): resolve scroll problem

---

src/.wechatide.ib.json

- [ x ] 其他
- [ x ] 本条 PR 不需要纳入 Changelog
- [ x ] 文档已补充或无须补充
- [ x ] 代码演示已提供或无须提供
- [ x ] TypeScript 定义已补充或无须补充
- [ x ] Changelog 已提供或无须提供

feat: 微信ide可视化配置更新

---

src/textarea/README.md
src/textarea/textarea.ts
src/textarea/textarea.wxml

https://github.com/Tencent/tdesign-miniprogram/issues/501
- feat(textarea): support cursor-spacing attribute

feat(textarea): support cursor-spacing attribute

---

qq/site/docs/getting-started.md
qq/site/plugin-tdoc/md-to-vue.ts

feat(qq/site): repalce some world dynamically in md

---

src/textarea/textarea.json

resolve #508 
- fix(textarea): 移除无用的组件依赖

fix(textarea): remove useless components

---

src/textarea/textarea.ts
src/textarea/textarea.wxml

https://github.com/Tencent/tdesign-miniprogram/issues/500
- fix(textarea): trigger word count on initialization

fix(textarea): trigger word count on initialization

---

src/checkbox/checkbox.ts

无
外部样式类无法使用；
经研究，是由于 styleIsolation 设置为 shared 导致的
- fix(checkbox): 修复外部样式类无法使用的问题

fix(checkbox): enable external class

---

src/dropdown-menu/dropdown-item.ts

fix #531 
- fix(dropdown-menu): 单选的情况下，选择之后直接关闭

fix(dropdown-menu): close after radio change

---

src/tab-bar/tab-bar-item.ts

fix #547 
- fix(tabbar): 修复具名插槽无法使用的问题

fix(tabbar): enable multiple slots

---

test/.wechatide.ib-back0627.json

feat: backup

---

src/dialog/README.md
src/dialog/props.ts
src/drawer/README.md
src/drawer/props.ts
src/dropdown-menu/README.md
src/dropdown-menu/props.ts
src/message/README.md
src/message/props.ts
src/popup/README.md
src/popup/props.ts

format component z-index
fix #503
- [✅  ] 日常 bug 修复
- [✅  ] 文档改进
- [✅  ] 组件样式/交互改进
https://github.com/Tencent/tdesign-miniprogram/issues/503
- Dialog: 修复默认层级问题
- DropdownMenu: 修复默认层级问题
- Drawer: 修复默认层级问题
- Message: 修复默认层级问题
- Popup: 修复默认层级问题
- [ ✅] 文档已补充或无须补充
- [ ✅] 代码演示已提供或无须提供
- [ ✅] TypeScript 定义已补充或无须补充
- [✅ ] Changelog 已提供或无须提供

refactor: format component z-index

---

src/fab/fab.wxml

fix #559 
- fix(fab): 修复 text 属性不生效的问题

fix(fab): enable text property

---

src/action-sheet/README.md
src/action-sheet/action-sheet.less
src/action-sheet/action-sheet.ts
src/action-sheet/action-sheet.wxml

add class config
fix #527
- 日常 bug 修复
- 新特性提交
- 文档改进
- 组件样式/交互改进
- feat(action-sheet): add class config
- ☑️文档已补充或无须补充
- ☑️代码演示已提供或无须提供
- ☑️TypeScript 定义已补充或无须补充
- ☑️Changelog 已提供或无须提供

feat(action-sheet): add class config

---

src/notice-bar/notice-bar.ts

#560 
解决方案：在ready阶段初始化组件
-fix(notice-bar): 修复公告不滚动问题

fix(notice-bar): fix scroll problem

---

src/dialog/dialog.wxml

fix #563 
- fix(Dialog): 修复点击遮罩层不会触发 close 事件的问题

fix(dialog): causes clicking on the overlay to trigger the close event

---

src/tabs/tabs.ts

#538 
解决方案：tabs选项卡不存在时，不触发changeIndex事件
- fix(tabs): 修复tabs选项卡不存在时滑动报错问题

fix(tabs): handling toggles without page faults

---

src/fab/fab.ts

需求背景：长文本遮挡
解决方案：监听text，text存在时修改buttonProps.shape值为round，实现文本自适应
- fix(fab): 支持文本自适应

fix(fab): support text adaptation

---

src/fab/fab.wxml

fix #513
移除无效的 class
- fix(fab): 移除无效的类名：`t-fab__button`

fix(fab): remove useless class

---

src/common/common.ts
src/upload/README.md
src/upload/props.ts
src/upload/type.ts

https://github.com/Tencent/tdesign-miniprogram/issues/549
由于小程序只会渲染 1 个插槽，因此定义的 deleteBtn 这样需要渲染多个的插槽是无法实现的。
所以，将这个无法实现的 API 移除掉。
- fix(upload): 移除 deleteBtn 属性

fix(upload): remove deleteBtn property

---

src/dropdown-menu/README.md
src/dropdown-menu/dropdown-menu.ts
src/dropdown-menu/dropdown-menu.wxml

#545 
增加 toggle 方法用于切换下拉菜单
- feat(dropdown-menu): 新增 toggle 示例方法，用于切换下拉菜单

feat(dropdown-menu): add toggle function

---

src/popup/README.md
src/popup/popup.json
src/popup/popup.less
src/popup/popup.ts
src/popup/popup.wxml
src/popup/props.ts
src/popup/type.ts

无
- 优化DOM，
- 优化代码，使用 overlay 组件，
- 使用 transition mixin
- 移除 transitionProps 属性
- 新增 duration 属性，控制动画过渡时间
- 新增 customStyle 透传样式至根节点
- 新增 overlayProps 属性，透传至 overlay 组件

refactor(popup): using transition mixin and overlay component

---

src/overlay/README.md
src/overlay/overlay.less
src/overlay/overlay.ts
src/overlay/overlay.wxml

无
新增 custom-style 属性透传样式至根元素
新增 custom-style 属性透传样式至根元素

feat(overlay): add custom style property

---

src/dropdown-menu/dropdown-item.less
src/dropdown-menu/dropdown-item.wxml
src/dropdown-menu/dropdown-menu.wxml
src/mixins/transition.ts

无
- fix(DropdownMenu): 优化按钮样式
- fix(DropdownMenu): 修复切换菜单时出现漂移的问题

fix(dropdown-menu): resolve popup animation

---

example/app.json
src/popup/README.md
src/popup/_example/popup.json
src/popup/_example/popup.less
src/popup/_example/popup.ts
src/popup/_example/popup.wxml
src/popup/_example/top/index.js
src/popup/_example/top/index.json
src/popup/_example/top/index.wxml
src/popup/_example/top/index.wxss

refactor(popup): upgrade demo

---

src/dropdown-menu/dropdown-item.less
src/overlay/overlay.ts
src/popup/popup.wxml
src/radio/radio.wxml

fix #598 
- fix(DropdownMenu): 修复下拉菜单无法展开的问题

fix(dropdown-menu): resolve invisible problem

---

src/picker/picker-item.ts

fix #611
pick 事件返回的 label 不正确
- fix(Picker): 修复 pick 事件返回的 label 不正确的问题

fix(picker): return correct label

---

src/picker/README.md
src/picker/picker.ts
src/picker/picker.wxml
src/picker/props.ts
src/picker/type.ts

fix #552 
- feat(Picker): 增加 `autoClose` 属性，点击确认、取消、遮罩层时自动关闭
- fix(Picker): `confirm-btn` 和 `cancel-btn` 增加 `boolean` 类型，值为 `true` 时使用默认文案

feat(picker): add auto close

---

src/dropdown-menu/dropdown-menu.wxml

fix #620 
层级添加错误，导致无法被遮盖
- fix(DropdownMenu): 移除冗余的 `z-index`

Fix/dropdown menu/z index

---

src/button/README.md
src/button/button.ts

- feat(Button): tap 事件返回值更新为 event 对象

docs(button): update docs

---

src/tabs/tab-panel.ts

fix #631 
当 tab-panel 的值为 0 时，不能切换 tab。
- fix(tabs): 修复值等于 0 时不能正常切换的问题

fix(tabs): enable value equal zero

---

src/picker/picker-item.ts

fix #542 
重复定义 options
- fix(Picker): 修复因重复定义 `options` 导致告警的问题

fix(picker): resolve warnings

---

src/sticky/sticky.ts

fix(sticky): update code structure

---

src/avatar/avatar-group.ts
src/avatar/avatar.ts
src/back-top/_example/back-top.ts
src/checkbox-group/checkbox-group.ts
src/checkbox/checkbox.ts
src/grid/grid-item.ts
src/grid/grid.ts
src/message/message.ts
src/navbar/navbar.ts
src/notice-bar/notice-bar.ts
src/picker/picker-item.ts
src/picker/picker.ts
src/radio-group/radio-group.ts
src/radio/radio.ts
src/swiper/swiper-item.ts
src/swiper/swiper-nav.ts
src/swiper/swiper.ts
src/tabs/tab-panel.ts
src/tabs/tabs.ts

fix: resolve typescript incorrect using

---

site/plugin-tdoc/md-to-vue.ts

chore: support windows

---

src/pull-down-refresh/pull-down-refresh.ts
src/pull-down-refresh/pull-down-refresh.wxml

https://github.com/Tencent/tdesign-miniprogram/issues/630
页面滚动事件传递到组件，所以如果PullDownRefresh上拉到底无法实现分页操作。
暴露scroll-view的触底事件的监听，通过scroll-view的触底监听实现分页。
- fix(PullDownRefresh): 触底监听实现分页

增加对scroll-view是否到底的事件监控。以处理滑动分页的问题。

---

src/button/_example/button.wxml
src/button/button.less

#643 
- fix(Button): 修复 `variant=outline`无效
- feat(Button):  `variant` 属性新增 `dashed`

fix(button): use correct variant

---

src/tab-bar/README.md
src/tab-bar/_example/badge/index.wxml
src/tab-bar/_example/custom/index.js
src/tab-bar/_example/custom/index.json
src/tab-bar/_example/custom/index.wxml
src/tab-bar/_example/custom/index.wxss
src/tab-bar/_example/tab-bar.json
src/tab-bar/_example/tab-bar.wxml
src/tab-bar/props.ts
src/tab-bar/tab-bar-item.less
src/tab-bar/tab-bar-item.ts
src/tab-bar/tab-bar-item.wxml
src/tab-bar/tab-bar.ts
src/tab-bar/tab-bar.wxml
src/tab-bar/type.ts

fix #645 
统一使用 CSS Variable 调整样式相关；移除 color 属性
- fix(Tabbar): 移除 color 属性，使用 CSS Variable 替代
- feat(Tabbar): 新增 CSS Variable 调整标签栏字体和图标颜色，具体查看文档
- docs(Tabbar): 新增自定义主题示例代码

fix(tabbar): remove color property add new css variable

---

.github/workflows/issue-help-wanted.temp.yml
.github/workflows/issue-mark-duplicate.temp.yml
.github/workflows/issue-reply.temp.yml

none
统一actions-cool，可以方便以后引入机器人和CI能力跟进

ci: update actions-cool

---

src/drawer/README.md
src/drawer/_example/base/index.json
src/drawer/_example/base/index.wxml
src/drawer/_example/base/index.wxss
src/drawer/_example/drawer.less
src/drawer/_example/icon-drawer/index.json
src/drawer/_example/icon-drawer/index.wxml
src/drawer/_example/icon-drawer/index.wxss
src/drawer/drawer.less

- feat(Drawer): 新增 CSS Variable 调整抽屉背景、列表项标题、列表项图标、列表项下边框颜色，具体查看文档

feat(drawer): add css variable

---

src/tab-bar/tab-bar-item.less
src/tab-bar/tab-bar.less

无
修复 CSS Variable 没有写 fallback 导致样式丢失的问题
- fix(Tabbar): 修复因 CSS Variables 没有写 fallback 导致样式丢失的问题
- fix(Tabbar): CSS Variables 命名规则由 `--t` 改成 `--td` 开头

fix(tabbar): add fallback to CSS variables

---

src/grid/grid-item.less
src/upload/upload.wxml

fix(upload): fix image style

---

src/stepper/README.md
src/stepper/_example/base/index.js
src/stepper/_example/base/index.json
src/stepper/_example/base/index.wxml
src/stepper/_example/input-width/index.js
src/stepper/_example/input-width/index.json
src/stepper/_example/input-width/index.wxml
src/stepper/_example/min-max/index.js
src/stepper/_example/min-max/index.json
src/stepper/_example/min-max/index.wxml
src/stepper/_example/other/index.js
src/stepper/_example/other/index.json
src/stepper/_example/other/index.wxml
src/stepper/_example/other/index.wxss
src/stepper/_example/status/index.js
src/stepper/_example/status/index.json
src/stepper/_example/status/index.wxml
src/stepper/_example/step/index.js
src/stepper/_example/step/index.json
src/stepper/_example/step/index.wxml
src/stepper/_example/stepper.json
src/stepper/_example/stepper.ts
src/stepper/_example/stepper.wxml

docs(Stepper): update code sample

---

src/button/README.md
src/button/button.json
src/button/button.less
src/button/button.ts
src/button/button.wxml
src/button/props.ts
src/button/type.ts

#672 
- fix(Button): 修复 loading 无效的问题
- feat(Button): 新增 loadingProps 属性透传至loading

feat(button): use t-loading && support loading-props

---

src/tab-bar/README.md

fix(tabbar): fix README error

---

src/tabs/README.md
src/tabs/tabs.less
src/tabs/tabs.ts

fix #681 
支持主题定制
- feat(Tabs): 新增 CSS Variables 调整字体、滑块颜色等，具体查看文档

feat(tabs): support css variables

---

src/toast/index.ts
src/toast/toast.less
src/toast/toast.ts
src/toast/toast.wxml

无
支持 duration 传入 0 的时候，toast 不消失
- feat(Toast): 支持 `duration` 传入 0 的时候，toast 不消失

feat(toast): support zero duration

---

src/dropdown-menu/dropdown-item.ts

无
修复树形选择时，点击单选仍自动关闭的问题。
- fix(DropdownMenu): 修复树形选择时，点击单选仍自动关闭的问题

fix(dropdown-menu): resolve single select correctly

---

src/cell/cell.wxml

fix #687
优化插槽的使用
- fix(Cell): 优化 slot 的渲染逻辑

fix(cell): resolve slot correctly

---

src/swipe-cell/README.md
src/swipe-cell/_example/left/index.js
src/swipe-cell/_example/left/index.json
src/swipe-cell/_example/left/index.wxml
src/swipe-cell/_example/left/index.wxss
src/swipe-cell/_example/right/index.js
src/swipe-cell/_example/right/index.json
src/swipe-cell/_example/right/index.wxml
src/swipe-cell/_example/right/index.wxss
src/swipe-cell/_example/swipe-cell.json
src/swipe-cell/_example/swipe-cell.wxml

docs(swipe-cell): update code sample

---

src/cell/README.md
src/cell/__test__/__snapshots__/demo.test.js.snap
src/cell/_example/multiple/index.wxml
src/cell/cell.less
src/cell/cell.ts
src/cell/cell.wxml

#696 
- fix(Cell): 修复 `image` 插槽无效问题
- feat(Cell): `external-classes` 新增 `t-class-left-icon`

fix(cell): add image slot && enrich external-classes

---

src/input/README.md
src/input/__test__/__snapshots__/demo.test.js.snap
src/input/_example/special/index.wxml
src/input/_example/special/index.wxss

fix(input): fix docs

---

jest.unit.config.js
src/checkbox/__test__/__snapshots__/demo.test.js.snap
src/checkbox/__test__/demo.test.js
src/dialog/__test__/__snapshots__/demo.test.js.snap
src/dialog/__test__/demo.test.js
src/message/__test__/__snapshots__/demo.test.js.snap
src/message/__test__/demo.test.js
src/popup/__test__/index.test.js
src/pull-down-refresh/__test__/__snapshots__/demo.test.js.snap
src/pull-down-refresh/__test__/demo.test.js
src/swipe-cell/__test__/__snapshots__/demo.test.js.snap
src/swipe-cell/__test__/demo.test.js
src/transition/__test__/index.test.js

feat: add demo test

---

src/back-top/README.md

docs(back-top): update readme

---

src/action-sheet/__test__/__snapshots__/demo.test.js.snap
src/action-sheet/__test__/demo.test.js
src/back-top/__test__/__snapshots__/demo.test.js.snap
src/back-top/__test__/demo.test.js
src/badge/__test__/__snapshots__/demo.test.js.snap
src/badge/__test__/demo.test.js
src/count-down/__test__/__snapshots__/demo.test.js.snap
src/count-down/__test__/demo.test.js
src/dropdown-menu/__test__/__snapshots__/demo.test.js.snap
src/dropdown-menu/__test__/demo.test.js
src/empty/__test__/__snapshots__/demo.test.js.snap
src/empty/__test__/demo.test.js
src/image-viewer/__test__/__snapshots__/demo.test.js.snap
src/image-viewer/__test__/demo.test.js
src/radio/__test__/__snapshots__/demo.test.js.snap
src/sticky/__test__/__snapshots__/demo.test.js.snap
src/sticky/__test__/demo.test.js
src/toast/__test__/__snapshots__/demo.test.js.snap
src/toast/__test__/demo.test.js

test: add demo test

---

src/tag/__test__/__snapshots__/demo.test.js.snap
src/tag/_example/checkable/index.wxml
src/tag/_example/closable/index.wxml
src/tag/_example/shape/index.wxml
src/tag/common/base.less

- fix(Tag): 改用 `display: inline-flex`，宽度自适应

fix(Tag): adjust style

---

src/button/__test__/index.test.js

完善 Button 测试用例
- feat(Button): 新增单元测试

test(button): add unit test

---

src/back-top/__test__/index.test.js
src/back-top/_example/back-top.ts

test(BackTop): add unit test

---

src/pull-down-refresh/pull-down-refresh.ts
src/pull-down-refresh/pull-down-refresh.wxml

fix #715
增加 scrollToTop 方法，手动滚动到顶部
- feat(PulldownRefresh): 新增 ScrollToTop 方法，手动调用滚动到顶部

feat(pulldown-refresh): add scroll top function

---

src/fab/README.md
src/fab/__test__/index.test.js

test(fab): add unit test

---

src/icon/README.md
src/icon/__test__/index.test.js

test(icon): add unit test

---

src/grid/grid-item.less

场景1： 垂直布局，align无效
场景2： 图片居中，文本居左
- fix(Grid): 修复垂直布局时间，align 无效

fix(grid): fix align

---

src/popup/README.md
src/popup/__test__/index.test.js
src/popup/popup.ts
src/popup/popup.wxml

test(popup): enrich unit test

---

src/progress/README.md
src/progress/__test__/index.test.js

test(Progress): add unit test

---

src/drawer/README.md
src/drawer/__test__/index.test.js

test(Drawer): add unit test

---

src/tag/README.md
src/tag/__test__/index.test.js
src/tag/check-tag-props.ts
src/tag/check-tag.ts
src/tag/check-tag.wxml
src/tag/tag.ts
src/tag/tag.wxml
src/tag/type.ts

- fix(Tag): 修复 disabled 为true时，closable 无效的问题
- fix(Tag): 修复 maxWidth 输入为字符时，宽度计算错误问题
- test(Tag): 完善单元测试

test(Tag): add unit test

---

src/checkbox/__test__/index.test.js
src/grid/README.md
src/grid/__test__/__snapshots__/index.test.js.snap
src/grid/__test__/index.js
src/grid/__test__/index.json
src/grid/__test__/index.test.js
src/grid/__test__/index.wxml
src/grid/grid-item.ts
src/grid/grid.ts
src/grid/props.ts
src/grid/type.ts

test(grid): add unit test

---

src/upload/upload.ts

fix #747 
fix #749 
- fix(Upload): 修复自定义上传没有关联成功/失败状态

fix(upload): 修复自定义上传没有关联成功/失败状态bug

---

src/swiper/swiper.ts

#753 
- fix(Swiper): 修复动态修改 `swiper-item` 时，视图响应不正确问题

fix(swiper): update view when swiper-item change

---

src/upload/README.md
src/upload/__test__/__snapshots__/demo.test.js.snap
src/upload/_example/multiple/index.js
src/upload/_example/multiple/index.wxml
src/upload/upload.ts
src/upload/upload.wxml

fix #748
文件上传失败之后，没有办法触发重新上传。
现在新增 click 事件，点击重新上传按钮时触发。
- feat(Upload): 新增 click 事件

feat(upload): add click event

---

src/tabs/tabs.less

fix(tabs): fix tabs vertical layout

---

src/badge/README.md
src/badge/__test__/index.test.js
src/badge/badge.wxml
src/badge/badge.wxs
test/utils/colors.js

- fix(badge): 修复showZero & offset 无单位情况

test(badge): add unit test

---

src/input/README.md
src/input/__test__/__snapshots__/index.test.js.snap
src/input/__test__/index.test.js
src/input/input.ts

test(Input): add unit test for input

---

src/textarea/README.md
src/textarea/__test__/__snapshots__/index.test.js.snap
src/textarea/__test__/index.test.js
src/textarea/textarea.ts

test(Textarea): add unit test for textarea

---

src/stepper/README.md
src/stepper/__test__/__snapshots__/index.test.js.snap
src/stepper/__test__/index.test.js
src/stepper/stepper.ts
src/stepper/stepper.wxml

test(Stepper): add unit test for stepper

---

src/result/README.md
src/result/__test__/index.test.js

#701
#701 
加入result的测试
加入result的测试

test(result): add test for result

---

src/back-top/__test__/index.test.js
src/progress/__test__/index.test.js
src/progress/progress.ts
src/progress/progress.wxml

- feat(Progress):  `strokeWidth` 支持字符类型
- feat(Progress): 更新测试用例
- feat(BackTop): 移除 `backTop`测试用例中的 `console`

feat(progress): strokeWidth support string type

---

src/rate/__test__/index.test.js

#701 
完善测试用例
- test(rate): 新增单元测试

test(rate): add unit test

---

src/drawer/__test__/index.test.js
src/popup/README.md
src/popup/popup.wxml
src/popup/props.ts

背景： `zIndex` 无效
- fix(Popup): 修复 `zIndex` 无效问题

fix(Popup): zIndex moved to root node && update docs

---

src/toast/README.en-US.md
src/toast/README.md
src/toast/toast.ts
src/toast/type.ts

feat(toast): add event

---

src/toast/__test__/index.test.js

test(toast): add unit test

---

src/tab-bar/_example/custom/index.wxss

fix(tabbar): update demo

---

src/steps/__test__/index.js
src/steps/__test__/index.json
src/steps/__test__/index.test.js
src/steps/__test__/index.wxml

#701 
完善单元测试
- test(Step): 新增单元测试

test(steps): add unit test

---

src/badge/__test__/index.test.js
src/divider/__test__/index.test.js
src/switch/README.md
src/switch/__test__/__snapshots__/index.test.js.snap
src/switch/__test__/index.test.js
src/switch/props.ts
src/switch/type.ts
test/utils/colors.js

test(switch): add unit test

---

src/empty/README.md
src/empty/__test__/index.test.js

test/empty
- test(Empty): 新增单元测试

test(empty): add unit empty

---

script/coverage-badge.js

fix #799 
修复生成测试覆盖率徽章脚本，不支持win32平台问题

fix(coverage-badge): coverage-badge脚本支持win32平台

---

src/skeleton/README.md
src/skeleton/__test__/__snapshots__/index.test.js.snap
src/skeleton/__test__/index.test.js

test(skeleton): add unit test

---

src/textarea/_example/textarea.json

fix(textarea): use the correct filename

---

src/dialog/README.md
src/dialog/dialog.wxml
src/dialog/props.ts
src/dialog/type.ts
src/overlay/overlay.ts
src/overlay/overlay.wxml
src/popup/popup.wxml

fix #787 
Dialog 增加 overlayProps 透传至 overlay 组件。
- feat(Dialog): 新增 overlayProps 属性透传至 Overlay 组件

feat(dialog): add overlayProps

---

src/image/__test__/__snapshots__/index.test.js.snap
src/image/__test__/index.test.js
src/image/image.ts
src/image/image.wxml

test(Image): add unit test

---

src/dialog/README.md
src/dialog/_example/button/index.js
src/dialog/_example/button/index.json
src/dialog/_example/button/index.wxml
src/dialog/_example/button/index.wxss
src/dialog/_example/dialog.json
src/dialog/_example/dialog.wxml
src/dialog/index.ts

fix #788 
增加示例代码展示对话框如何使用 open-type 按钮

fix(dialog): add open type demo

---

src/count-down/README.md
src/count-down/__test__/__snapshots__/index.test.js.snap
src/count-down/__test__/index.test.js

test(countDown): add unit test

---

src/collapse/__test__/__snapshots__/index.test.js.snap
src/collapse/__test__/index.js
src/collapse/__test__/index.json
src/collapse/__test__/index.test.js
src/collapse/__test__/index.wxml
src/collapse/collapse-panel-props.ts
src/collapse/collapse-panel.ts
src/collapse/collapse.ts
src/collapse/type.ts

test(collapse): add unit test

---

src/navbar/README.md
src/navbar/__test__/__snapshots__/index.test.js.snap
src/navbar/__test__/index.test.js
src/navbar/navbar.ts
src/navbar/navbar.wxml

test(navbar): add unit test

---

src/image-viewer/README.md
src/image-viewer/__test__/__snapshots__/index.test.js.snap
src/image-viewer/__test__/index.test.js

test(image-viewer): add unit test

---

src/tabs/tabs.ts

fix #793 
支持 tab panel 动态移除
- fix(tabs): 修复无法正常移除 tab panel 的问题

fix(tabs): enable to remove tab panel

---

src/cell/__test__/__snapshots__/index.test.js.snap
src/collapse/__test__/__snapshots__/index.test.js.snap
src/dialog/__test__/__snapshots__/demo.test.js.snap
src/dialog/__test__/demo.test.js
src/icon/README.md
src/icon/__test__/__snapshots__/demo.test.js.snap
src/icon/__test__/demo.test.js
src/icon/__test__/index.test.js
src/icon/_example/custom/index.wxml
src/icon/_example/custom/index.wxss
src/icon/_example/icon.json
src/icon/_example/icon.wxml
src/icon/_example/iconImage/index.js
src/icon/_example/iconImage/index.json
src/icon/_example/iconImage/index.wxml
src/icon/_example/iconImage/index.wxss
src/icon/icon.less
src/icon/icon.ts
src/icon/icon.wxml
src/image/__test__/__snapshots__/index.test.js.snap
src/input/__test__/__snapshots__/index.test.js.snap
src/notice-bar/__test__/__snapshots__/index.test.js.snap
src/stepper/__test__/__snapshots__/index.test.js.snap

#815 
- feat(Icon):  `name` 支持图片链接
- fix(Icon): `size` 不在支持 `middle`、`small`等关键字，默认单位 `px`

feat(Icon): name supports image types

---

src/dropdown-menu/dropdown-item.ts

fix #779 
- fix(DropdownMenu): 修复下拉菜单定位错误的问题

fix(dropdown-menu): resolve popup position correctly

---

src/pull-down-refresh/README.md
src/pull-down-refresh/__test__/index.test.js
src/pull-down-refresh/_example/pull-down-refresh.less
src/pull-down-refresh/_example/pull-down-refresh.wxml

- test(PullDownRefresh): 新增单元测试

test: add unit test for pull-down-refresh

---

src/tabs/README.en-US.md
src/tabs/README.md
src/tabs/props.ts
src/tabs/type.ts

fix(tabs): update props

---

src/tabs/__test__/__snapshots__/index.test.js.snap
src/tabs/tabs.less
src/tabs/tabs.wxml

#834 
- fix(Tabs): 修复垂直模式下内容区域绑定事件无效的问题

fix(Tabs): vertical content click event invalid

---

src/tabs/README.en-US.md
src/tabs/README.md
src/tabs/tabs.ts

fix #827 
change 和 click 事件返回 label 的值
- feat(Tabs): change 和 click 事件返回 label 的值

feat(tabs): enrich event params

---

src/action-sheet/README.md
src/action-sheet/__test__/index.test.js
src/action-sheet/action-sheet.ts
src/action-sheet/show.ts

- feat(ActionSheet): 新增单元测试
- fix(ActionSheet): 修复文档描述错误

feat(action-sheet): add unit test for action-sheet

---

src/fab/fab.less

背景： 页面有滚动条时，`Fab` 会随滚动条滚动而滚动
解决方案：使用固定定位 `position: fixed` ，相对视图
- fix(Fab): 修复悬浮按钮随页面滚动的问题

fix(Fab): fix fab scrolling problem

---

src/tab-bar/README.en-US.md
src/tab-bar/README.md
src/tab-bar/__test__/index.js
src/tab-bar/__test__/index.json
src/tab-bar/__test__/index.test.js
src/tab-bar/__test__/index.wxml
src/tab-bar/props.ts
src/tab-bar/tab-bar-item-props.ts
src/tab-bar/tab-bar-item.ts
src/tab-bar/tab-bar-item.wxml
src/tab-bar/tab-bar.ts
src/tab-bar/type.ts

无
- 完善单元测试
- 点击 subTabBar 选项时，返回的值从数组改成选项的值
- test(TabBar): 新增单元测试
- fix(TabBar): 点击 subTabBar 选项时，返回的值从数组改成选项的值
- fix(TabBar): 修复子选项激活时，父选项未展示激活的问题

test(tab-bar): add unit test

---

src/upload/README.md
src/upload/__test__/index.test.js
src/upload/upload.ts

test: add unit test for upload

---

src/dropdown-menu/README.md
src/dropdown-menu/__test__/index.js
src/dropdown-menu/__test__/index.json
src/dropdown-menu/__test__/index.test.js
src/dropdown-menu/__test__/index.wxml
src/dropdown-menu/dropdown-item.wxml
src/dropdown-menu/dropdown-menu.ts

无
- test(DropdownMenu): 新增单元测试

test(dropdown-menu): add unit test

---

src/slider/README.en-US.md
src/slider/README.md
src/slider/__test__/index.test.js
src/slider/props.ts
src/slider/slider.ts
src/slider/type.ts

暂无
如更新日志
- test(Slider): 新增单元测试
- feat(Slider): 属性 marks 支持动态响应
- fix(Slider): 修复 disabled 状态下点击报错的问题

test(slider): cover more case

---

src/picker/README.md
src/picker/__test__/__snapshots__/index.test.js.snap
src/picker/__test__/index.js
src/picker/__test__/index.json
src/picker/__test__/index.test.js
src/picker/__test__/index.wxml

test(picker): add unit test

---

src/input/README.md
src/input/__test__/index.test.js
src/progress/README.md
src/progress/__test__/index.test.js
src/progress/props.ts
src/progress/type.ts
src/textarea/README.md
src/textarea/__test__/index.test.js

test: improve test coverage for some components

---

src/toast/README.md
src/toast/__test__/index.test.js
src/toast/index.ts
src/toast/toast.less
src/toast/toast.ts
src/toast/toast.wxml

无
重构代码，使用 transition mixin 来实现动画；
完善测试用例，使测试覆盖率达标；
重构 DOM，更合理；
- fix(Toast): 重构 DOM 以及代码逻辑
- feat(Toast): 使用 Transition 实现淡入淡出动画

refactor(toast): using transition mixin and refactor dom

---

src/swipe-cell/README.md
src/swipe-cell/__test__/index.test.js

add unit test for swipeCell
- test(SwipeCell): 新增单元测试

test(component): add unit test for swipeCell

---

src/swiper/README.md
src/swiper/__test__/__snapshots__/index.test.js.snap
src/swiper/__test__/base/index.js
src/swiper/__test__/base/index.json
src/swiper/__test__/base/index.wxml
src/swiper/__test__/base/index.wxss
src/swiper/__test__/index.test.js
src/swiper/swiper-item.ts
src/swiper/swiper-nav.ts
src/swiper/swiper.ts

test: add unit test for swiper

---

src/tabs/__test__/__snapshots__/index.test.js.snap
src/tabs/tabs.less
src/tabs/tabs.wxml

#793
tabs 在嵌套使用时，比如 placement=left 的 tabs 里面嵌套了 placement=top 的 tabs。
此时 tabs 的样式会出问题，是因为样式的继承性。
本次 PR 则是为了解决这个问题
- fix(Tabs): 修复嵌套使用时样式错误的问题

fix(tabs): using correct style when nest

---

src/input/__test__/__snapshots__/index.test.js.snap
src/input/input.wxml

#873 
- fix(Input): 修复 `clearable` 的显示和隐藏问题

fix(Input): resolve the clearable property

---

src/tab-bar/tab-bar-item.less

fix #872
由于没有设置 CSS Variables 没有设置 fallback value，导致在读不到值的时候，颜色不正确。
- fix(Tabbar): 使用 fallback value 保证颜色展示正确

fix(tabbar): using fallback value

---

src/textarea/README.md

confirm-type | 右下角按钮含义
-- | --
send | 右下角按钮为“发送”
search | 右下角按钮为“搜索”
next | 右下角按钮为“下一个”
go | 右下角按钮为“前往”
done | 右下角按钮为“完成”
return | 右下角按钮为“换行”

docs(textarea): update docs

---

src/date-time-picker/__test__/__snapshots__/index.test.js.snap
src/date-time-picker/__test__/index.test.js
src/date-time-picker/date-time-picker.ts
src/date-time-picker/date-time-picker.wxml

fix #882
重新梳理了受控与非受控逻辑对于 picker 选项重置的影响
- fix(DateTimePicker): 修复选项重置错误的问题

fix(date-time-picker): reset columns correctly

---

src/calendar/__test__/__snapshots__/index.test.js.snap
src/pull-down-refresh/pull-down-refresh.less

fix #900 
修复高度无法适应容器的问题
- fix(PulldownRefresh): 修复高度无法自适应外容器的问题

fix(pulldown-refresh): set the adaptive height

---

src/tabs/tabs.less

fix #902
修复 placement = left 时， Nav 不可见且不居左的问题。
- fix(Tabs): 修复 placement = left 时， Nav 不可见且不居左的问题

fix(tabs): keep nav always visible when layout is vertical

---

src/tab-bar/tab-bar.ts

无
无
- fix(TabBar): 修复 item 不传 value 时无法自动生成备用值的问题

fix(tab-bar): resolve item without value

---

example/app.json
example/pages/home/data/form.ts
site/site.config.mjs
src/cascader/README.en-US.md
src/cascader/README.md
src/cascader/_example/base/data.js
src/cascader/_example/base/index.js
src/cascader/_example/base/index.json
src/cascader/_example/base/index.wxml
src/cascader/_example/cascader.js
src/cascader/_example/cascader.json
src/cascader/_example/cascader.wxml
src/cascader/cascader.json
src/cascader/cascader.less
src/cascader/cascader.ts
src/cascader/cascader.wxml
src/cascader/props.ts
src/cascader/type.ts
src/radio-group/props.ts
src/radio-group/radio-group.ts
src/radio-group/radio-group.wxml
src/radio-group/type.ts
src/radio/README.en-US.md
src/radio/README.md
src/radio/props.ts
src/radio/radio-group-props.ts
src/radio/radio.ts
src/radio/type.ts
src/swiper/swiper.ts

无
- feat(Cascader): 新增级联选择器
- feat(RadioGroup): 新增 align 和 icon 属性，当使用 options 渲染子项时有效

feat(cascader): add new component

---

src/input/_example/special/index.wxml

#922 
- fix(Input): 修复 `demo`中 `value` 属性拼写错误

fix(Input): use the correct props name

---

src/cascader/README.md

fix(cascader):modified wrong example in documentation

---

src/tab-bar/tab-bar.ts

fix(tab-bar): use correct initial value for backupValue

---

src/message/README.md
src/message/_example/custom-navigation/index.js
src/message/_example/custom-navigation/index.json
src/message/_example/custom-navigation/index.wxml
src/message/_example/custom-navigation/index.wxss
src/message/_example/message.json
src/message/_example/message.wxml

fix #931
新增示例演示如何在自定义导航栏时使用 message
- demo(Message): 新增示例演示如何在自定义导航栏时使用 message

docs(message): add demo for custom navigation

---

src/calendar/__test__/__snapshots__/index.test.js.snap
src/date-time-picker/__test__/__snapshots__/index.test.js.snap
src/dialog/__test__/__snapshots__/index.test.js.snap
src/picker/__test__/__snapshots__/index.test.js.snap
src/popup/popup.ts
src/popup/popup.wxml

fix #941
默认阻止 popup 内容区域的滑动穿透
- fix(Popup): 阻止内容区域滑动穿透

fix(popup): prevent scroll through on body

---

src/cascader/cascader.json

- fix(Cascader): 调整 `usingComponents` 中的绝对路径为相对路径

fix(cascader): use relative paths in usingComponents

---

src/textarea/_example/textarea.json
src/textarea/_example/textarea.wxml

- fix(Textarea): 修复 "带标题多行文本框" 示例不显示

fix(textarea): resolve example does not show

---

src/tabs/tabs.json

- fix(tabs): 修复在Tabs组件`usingComponents`中使用绝对路径导致`Component is not found`的问题

fix(tabs): use relative paths in usingComponents

---

src/tag/README.md
src/tag/check-tag.ts
src/tag/check-tag.wxml

- feat(Tag):  `checkTag` 支持外部样式类

feat(check-tag): support externalClass

---

src/radio/README.md
src/radio/radio.less
src/radio/radio.wxml

- fix(Radio): 移除 color 属性，使用 CSS Variable 替代
- feat(Radio): 新增 CSS Variable 调整文案、图标等颜色，具体查看文档

feat(Radio): remove color property && support CSS Variables

---

src/icon/icon.ts

- fix(Icon): 修复 customStyle 属性无效的问题

fix(Icon): resolve character concatenation error

---

src/radio-group/props.ts
src/radio-group/radio-group.ts
src/radio-group/radio-group.wxml
src/radio-group/type.ts
src/radio/README.en-US.md
src/radio/README.md

无
无
- feat(RadioGroup): 新增支持 keys 属性，使用 options 时有效
- fix(RadioGroup): 修复使用 options 时无法选中的问题

feat(radio): support keys

---

src/tabs/tab-panel.ts

fix #962
支持动态 label
- fix(Tabs): 修复动态 label 无法生效的问题

fix(tabs): resolve dynamic label

---

src/common/utils.wxs
src/tabs/__test__/__snapshots__/demo.test.js.snap
src/tabs/__test__/__snapshots__/index.test.js.snap
src/tabs/_example/with-badge/index.wxml
src/tabs/tabs.less
src/tabs/tabs.wxml

无
原有类名不是规范的 BEM，因此本次改动将涉及 classname 的破坏性改动。
- fix(Tabs): 调整非 BEM 的类名，此变更属于破坏性变更

fix(tabs): update classname and demo

---

src/badge/__test__/index.test.js
src/badge/badge.wxs

无
offset 的顺序错误，传入 `[10]` 应该调整水平方向，目前错误的调整垂直方向
- fix(Badge): 修复 offset 的顺序，首值应该调整水平方向

fix(offset): change order

---

src/button/README.md
src/button/__test__/__snapshots__/demo.test.js.snap
src/button/_example/base/index.wxml
src/button/button.less

- fix(Button): 修复 variant='text' 时，文本颜色样式错误
- feat(Button): 新增 CSS Variable 调整文本、边框、背景等颜色，具体查看文档

feat(Button): support CSS Variables

---

src/common/src/instantiationDecorator.ts

无
当 value 和 defaultValue 都没传时，需要当成非受控用法
- fix: 修复当 value 和 defaultValue 都没传时不能使用的问题

fix: fixed  uncontrolled when no value passed

---

src/cascader/README.md
src/cascader/_example/keys/index.wxml
src/cascader/_example/keys/index.wxss
src/cascader/cascader.less
src/radio-group/radio-group.ts
src/tabs/tabs.less

fix #955
无
- feat(Csacader): 支持 CSS Variables 进行自定义主题

feat(cascader): support css variables

---

src/calendar/__test__/__snapshots__/index.test.js.snap
src/calendar/calendar.less
src/calendar/calendar.wxml

fix #988
fix #956
无
- fix(Calendar): 修复无法滚动的问题
- fix(Calandar): 修复在布局不兼容的问题

fix(calendar): resolve scroll and flex layout

---

src/common/style/_variables.less
src/fab/__test__/__snapshots__/demo.test.js.snap
src/fab/_example/advance/index.js
src/fab/_example/fab.wxml
src/fab/fab.less
src/fab/fab.wxml

feat(fab): using new style

---

src/notice-bar/notice-bar.ts

- fix(NoticeBar): 修复 content 动态更新时， 滚动动画计算错误。
- feat(NoticeBar): 支持 prefixIcon 、theme 属性动态更新

fix(NoticeBar): support dynamic update of some properties

---

example/app.json
example/pages/home/home.json
src/action-sheet/_example/action-sheet.json
src/back-top/_example/back-top.json
src/cell-group/_example/cell-group.json
src/cell/_example/cell.json
src/checkbox/_example/checkbox.json
src/count-down/_example/count-down.json
src/dialog/_example/dialog.json
src/divider/_example/divider.json
src/drawer/_example/drawer.json
src/empty/_example/empty.json
src/footer/_example/footer.json
src/image-viewer/_example/image-viewer.json
src/image/_example/image.json
src/indexes/_example/indexes.json
src/loading/_example/loading.json
src/message/_example/message.json
src/picker/_example/picker.json
src/popup/_example/popup.json
src/radio/_example/radio.json
src/slider/_example/slider.json
src/stepper/_example/stepper.json
src/sticky/_example/sticky.json
src/swipe-cell/_example/swipe-cell.json
src/swiper/_example/swiper.json
src/tabs/_example/tabs.json
src/toast/_example/toast.json

fix #936 
使用全局 usingComponent，不需要单独声明
- build: 移除多余的组件声明

build: remove useless using

---

src/tab-bar/tab-bar.less

无
修复绝对定位时，宽度没有撑开的问题
- fix(TabBar): 修复绝对定位时，宽度没有撑开的问题

fix(tabbar): resolve width when fixed

---

src/cascader/cascader.ts

无
options 异步获取的话，不会通过 value 初始化选项
- fix(Cascader): 修复异步获取 options 时，无法使用 value 初始化已选选项

fix(cascader): resolve async options

---

src/empty/README.md
src/empty/__test__/__snapshots__/demo.test.js.snap
src/empty/__test__/demo.test.js
src/empty/_example/base/index.wxml
src/empty/_example/buttonEmpty/index.wxml
src/empty/_example/buttonEmpty/index.wxss
src/empty/_example/empty-page.less
src/empty/_example/empty-page.ts
src/empty/_example/empty-page.wxml
src/empty/_example/empty.json
src/empty/_example/empty.ts
src/empty/_example/empty.wxml
src/empty/_example/pageEmpty/index.js
src/empty/_example/pageEmpty/index.json
src/empty/_example/pageEmpty/index.wxml
src/empty/_example/pageEmpty/index.wxss
src/empty/empty.less
src/empty/empty.wxml
src/empty/props.ts
src/empty/type.ts

- feat(Empty): 新增 iconProps 属性
- feat(Empty): 新增 CSS Variables， 用于调整描述、操作内容文本颜色和间距等

style(Empty): using new style

---

src/navbar/__test__/__snapshots__/index.test.js.snap
src/navbar/navbar.ts
src/navbar/navbar.wxml

fix #1015 
使用正确的 CSS Variables 和 状态栏高度
- fix(NavBar): 使用正确的状态栏高度

fix(navbar): resolve status bar height correctly

---

src/search/search.wxml

fix #1084
默认渲染插槽，而不是在对应值未空时才渲染
- fix(Search): 修复插槽需要对应值为空时才渲染的问题

fix(search): render slot by default

---

src/tabs/README.md
src/tabs/__test__/__snapshots__/index.test.js.snap
src/tabs/tab-panel.wxml
src/tabs/tabs.less
src/tabs/tabs.wxml
src/tabs/tabs.wxs

fix #907
无
- fix(Tabs): 修复渲染 panel 时闪烁的问题

fix(tabs): resolve render blink

---

src/tabs/__test__/__snapshots__/demo.test.js.snap
src/tabs/__test__/__snapshots__/index.test.js.snap
src/tabs/_example/base/index.wxss
src/tabs/_example/tabs.json
src/tabs/_example/tabs.wxml
src/tabs/_example/vertical/index.js
src/tabs/_example/vertical/index.wxml
src/tabs/_example/vertical/index.wxss
src/tabs/_example/with-content/index.js
src/tabs/_example/with-content/index.wxml
src/tabs/_example/with-content/index.wxss
src/tabs/tabs.less
src/tabs/tabs.wxs

- fix(Tabs): 修复 placement='left' 时，面板内容不显示问题

fix(Tabs): fix tabs left layout

---

src/toast/_example/base/index.js
src/toast/toast.less

fix #981 
通过修改 `white-space = pre-line` 实现文本自定义换行
- fix(Toast): 支持文字换行

fix(toast): support text wrap

---

src/tabs/tabs.ts

fix #918
由于支持非等宽的 tab，因此计算 offset 的方法有误。
- fix(Tabs): 修复下标不显示的问题

fix(tabs): calculate offset correctly

---

src/footer/footer.less
src/footer/footer.wxml

fix #1068 
录屏链接
ios：https://share.weiyun.com/3QcwfYBB
安卓：https://share.weiyun.com/azKMvO5K
- fix(Footer): 支持无障碍

feat: aria-footer

---

src/navbar/navbar.less

fix #1092
无
- fix(NavBar): 修复背景色失效的问题

fix(navbar): resolve navbar color

---

src/input/README.md
src/input/type.ts

fix #994 
支持底层支持的新特性，type = nickname
但依赖基础库版本 2.12.2 +，[相关文档](https://developers.weixin.qq.com/miniprogram/dev/component/input.html)
- feat(Input): 新增支持 type = nickname

feat(input): support nickname type

---

src/cell/cell.less
src/common/style/_variables.less

fix #1095 
支持 CSS Variables
- fix(Cell): 新增支持 CSS Variables

feat(cell): support css variables

---

src/navbar/README.en-US.md
src/navbar/README.md
src/navbar/__test__/__snapshots__/demo.test.js.snap
src/navbar/_example/back/index.js
src/navbar/_example/back/index.wxml
src/navbar/props.ts
src/navbar/type.ts

fix(navbar): update docs and demo

---

src/loading/loading.wxml

fix #1113
修复 loading 的尺寸问题
- fix(Loading): 修复尺寸问题

fix(loading): resolve size problem

---

src/checkbox/checkbox.less
src/checkbox/checkbox.wxml
src/dropdown-menu/dropdown-item.wxml

无
由于checkbox重构了，影响到了 DropdownMenu 的样式

fix(dropdown-menu): resolve checkbox style

---

src/cascader/cascader.wxml

无
因为 Radio 重构导致 Cascader 样式有问题

fix(cascader): resolve radio style

---

src/checkbox/__test__/__snapshots__/demo.test.js.snap
src/checkbox/_example/type/index.wxml
src/checkbox/checkbox.less
src/checkbox/checkbox.wxml

fix #1134 
因为语法的差异，导致数组无法识别
- fix(Checkbox): 修复数组图标无法使用的问题

fix(checkbox): enable to use image icon

---

src/message/message.wxml

fix  #1046
1. 消息通知，自动播报
ios 录屏
https://user-images.githubusercontent.com/44194929/204958775-62871ce6-7ea0-4c2d-bd49-8479c43b4261.mov
- feat(Message): 支持无障碍访问

feat(message): support aria

---

src/stepper/__test__/__snapshots__/index.test.js.snap
src/stepper/stepper.wxml

fix #1021 
1. 操作按钮增加 `aria-label`、`aria-role`、`aria-disabled`
ios 录屏
https://user-images.githubusercontent.com/44194929/204758181-fd3b74d3-c072-4109-993d-d8c9aa49638e.mov
- feat(Stepper): 支持无障碍访问

feat(stepper): stepper aria

---

src/cascader/cascader.ts
src/radio-group/radio-group.ts

fix #1154
正常清除选项
- fix(Cascader): 修复重置 `options = []` 时报错的问题

fix(cascader): remove options without errors

---

.github/workflows/preview.yml

无
支持自动生成二维码，进行预览的功能
- build: 流水线支持自动预览功能

build: support auto preview

---

src/common/src/instantiationDecorator.ts
src/progress/progress.wxml

fix #1049
- feat(Progress): 支持无障碍访问

feat(progress): support progress aria

---

src/calendar/calendar.ts

fix #1145 
响应式处理属性
- fix(Calendar): 修复 `max-date`, `min-date`, `firstDayOfWeek` 无法动态修改的问题

fix(calendar): enable reactive props

---

src/checkbox/__test__/__snapshots__/demo.test.js.snap
src/checkbox/_example/special/index.wxml

fix: fix:aria-checkbox-demo

---

src/checkbox/checkbox.less
src/switch/switch.less

fix #1141
修复 scale 失败的问题
- fix(Switch): 修复视觉问题

fix(switch): resolve css scale failed

---

src/back-top/README.en-US.md
src/back-top/README.md
src/back-top/__test__/__snapshots__/demo.test.js.snap
src/back-top/__test__/demo.test.js
src/back-top/_example/back-top.json
src/back-top/_example/back-top.less
src/back-top/_example/back-top.ts
src/back-top/_example/back-top.wxml
src/back-top/_example/half-round/index.js
src/back-top/_example/half-round/index.json
src/back-top/_example/half-round/index.wxml
src/back-top/back-top.less
src/back-top/back-top.ts
src/back-top/back-top.wxml
src/back-top/props.ts
src/back-top/type.ts
src/common/utils.wxs

- feat(BackTop): 新增 CSS Variables
- feat(BackTop): 属性 icon 新增支持 Object 类型透传至图标组件，并支持同名插槽

style(BackTop): using css token

---

src/back-top/_example/back-top.json
src/back-top/_example/back-top.ts
src/back-top/_example/back-top.wxml

fix(back-top): update demo

---

src/notice-bar/_example/notice-bar.less
src/notice-bar/notice-bar.less

style(NoticeBar): align design

---

src/calendar/calendar.less

fix #1195
修复内容高度过高，导致按钮被挡住的问题
- fix(Calendar): 修复小屏幕适配的问题

fix(calendar): resolve max-height problem

---

src/tab-bar/__test__/__snapshots__/demo.test.js.snap
src/tab-bar/_example/badge/index.js
src/tab-bar/_example/badge/index.wxml
src/tab-bar/_example/base/index.js
src/tab-bar/_example/custom/index.js
src/tab-bar/_example/custom/index.wxml
src/tab-bar/_example/icon-only/index.js
src/tab-bar/_example/icon-only/index.wxml
src/tab-bar/_example/round/index.js
src/tab-bar/_example/round/index.wxml
src/tab-bar/_example/sub/index.js
src/tab-bar/_example/sub/index.wxml
src/tab-bar/_example/text-only/index.js
src/tab-bar/tab-bar-item.less
src/tab-bar/tab-bar-item.wxml
src/tab-bar/tab-bar.wxml

https://github.com/Tencent/tdesign-miniprogram/issues/1024

feat(tabbar): support aria-*

---

src/calendar/__test__/__snapshots__/index.test.js.snap
src/date-time-picker/__test__/__snapshots__/index.test.js.snap
src/dialog/__test__/__snapshots__/index.test.js.snap
src/overlay/__test__/__snapshots__/index.test.js.snap
src/overlay/overlay.wxml
src/picker/__test__/__snapshots__/index.test.js.snap

fix #1179  
https://share.weiyun.com/fFQFX4JE
- feat(Overlay): 支持无障碍访问

feat(overlay): support aria

---

src/count-down/__test__/__snapshots__/index.test.js.snap
src/count-down/count-down.wxml

fix #1180 
https://share.weiyun.com/SZ2cVIfo
- feat(CountDown): 支持无障碍访问

feat(count-down): support aria

---

src/tab-bar/_example/tab-bar.less
src/tab-bar/tab-bar.less

无
修复 Tabbar 在 `shape = round` & `safe-area-in-bottom = true` 的情况下，视觉错误的问题。
- fix(TabBar): 修复圆角下开启安全距离时视觉错误的问题

fix(tabbar): resolve safe area on round theme

---

src/input/README.md
src/input/__test__/__snapshots__/demo.test.js.snap
src/input/__test__/__snapshots__/index.test.js.snap
src/input/__test__/index.test.js
src/input/_example/base/index.wxml
src/input/_example/suffix/index.wxss
src/input/input.ts
src/input/input.wxml
src/input/props.ts
src/input/type.ts

- feat(Input):  clearable、prefixIcon、suffixIcon等属性新增 Object 类型，透传至 icon 组件
- break(Input): 移除 clearableIconProps、prefixIconProps、suffixIconProps 属性

feat(Input): extended attribute type

---

src/common/utils.ts
src/input/input.ts
src/input/input.wxml

chore: optimize setIcon function

---

src/button/__test__/__snapshots__/demo.test.js.snap
src/button/_example/icon-btn/index.wxml
src/button/_example/shape/index.wxml
src/button/button.wxml
src/calendar/__test__/__snapshots__/index.test.js.snap
src/common/template/button.wxml
src/sticky/__test__/__snapshots__/index.test.js.snap

fix #913 
1. hidden icon
2. button 增加 `aria-label`
https://user-images.githubusercontent.com/44194929/208037377-922d6b8f-dbb9-4d2b-925e-953c1ff0ef6f.mov
- feat(Button): 支持无障碍访问

feat(button): support aria

---

src/calendar/__test__/__snapshots__/index.test.js.snap
src/calendar/calendar.less
src/calendar/calendar.wxml
src/calendar/calendar.wxs
src/date-time-picker/__test__/__snapshots__/index.test.js.snap
src/dialog/__test__/__snapshots__/index.test.js.snap
src/picker/__test__/__snapshots__/index.test.js.snap
src/popup/popup.wxml

fix #1182
- 对应元素增加 aria 属性
- feat(Calendar): 支持无障碍访问
Android:
https://user-images.githubusercontent.com/5051221/206986176-7706f84d-ddc1-423f-a65d-09e7c86fbf14.mp4
iOS:
https://user-images.githubusercontent.com/5051221/206986320-d8d276f6-a363-4df5-a124-b320531ba56c.mp4

feat(calendar): 增加无障碍支持

---

src/input/__test__/__snapshots__/demo.test.js.snap
src/input/__test__/__snapshots__/index.test.js.snap
src/input/_example/bordered/index.wxml
src/input/_example/layout/index.wxml
src/input/_example/special/index.wxml
src/input/_example/suffix/index.wxml
src/input/input.wxml

fix #1016 
https://share.weiyun.com/TBmowV0U
- feat(Input): 支持无障碍访问

feat: input组件无障碍优化

---

src/calendar/README.en-US.md
src/calendar/README.md
src/calendar/__test__/__snapshots__/demo.test.js.snap
src/calendar/__test__/__snapshots__/index.test.js.snap
src/calendar/__test__/demo.test.js
src/calendar/_example/calendar.json
src/calendar/_example/calendar.wxml
src/calendar/_example/without-popup/index.js
src/calendar/_example/without-popup/index.json
src/calendar/_example/without-popup/index.wxml
src/calendar/_example/without-popup/index.wxss
src/calendar/calendar.less
src/calendar/calendar.wxml
src/calendar/props.ts
src/calendar/template.wxml
src/calendar/type.ts

无
支持不使用 Popup 和 CSS Variables
- feat(Calendar): 支持 CSS Variables，支持主题定制
- feat(Calendar): 新增 usePopup 属性，支持不使用弹出层用法

feat(calendar): support css variables & use-popup

---

example/app.json
src/checkbox/checkbox.less
src/checkbox/checkbox.wxml
src/dropdown-menu/README.md
src/dropdown-menu/_example/dropdown-menu.wxml
src/dropdown-menu/dropdown-item.json
src/dropdown-menu/dropdown-item.less
src/dropdown-menu/dropdown-item.ts
src/dropdown-menu/dropdown-item.wxml
src/dropdown-menu/dropdown-menu.less
src/dropdown-menu/dropdown-menu.ts
src/dropdown-menu/dropdown-menu.wxml
src/radio/radio.less
src/radio/radio.wxml

无
视觉升级
- feat(DropdownMenu): 视觉升级
- feat(DropdownMenu): 支持 CSS Variables，可自定义主题
- fix(Checkbox): 修复图标右侧显示时 border 样式错误的问题
- fix(Radio): 修复图标右侧显示时 border 样式错误的问题
- break(DropdownMenu): 调整外部样式类命名、DOM

feat(dropdown-menu): using new style

---

site/plugin-tdoc/md-to-vue.ts

chore: 修复文档多余斜杠问题

---

src/dropdown-menu/README.en-US.md
src/dropdown-menu/README.md
src/dropdown-menu/__test__/__snapshots__/demo.test.js.snap
src/dropdown-menu/__test__/index.js
src/dropdown-menu/__test__/index.test.js
src/dropdown-menu/__test__/index.wxml
src/dropdown-menu/_example/dropdown-menu.json
src/dropdown-menu/_example/dropdown-menu.wxml
src/dropdown-menu/_example/multi/index.wxml
src/dropdown-menu/_example/single/index.js
src/dropdown-menu/_example/single/index.wxml
src/dropdown-menu/dropdown-item-props.ts
src/dropdown-menu/dropdown-item.ts
src/dropdown-menu/dropdown-item.wxml
src/dropdown-menu/dropdown-menu.ts
src/dropdown-menu/props.ts
src/dropdown-menu/type.ts
src/popup/popup.wxml

无
- break(DropdownMenu): 废弃 optionsLayout 属性，移除 tree 相关逻辑，独立出 treeSelect 组件
- feat(DropdownMenu): 可通过 value 和 options 自动切换 label
- break(DropdownMenu):  变更外部样式类命名

fix(dropdown-menu): remove logic about tree

---

src/search/search.less

fix #1269
修复 CSS Variables 命名错误的问题
- fix(Search): 修复 CSS Variables 命名错误的问题

fix(search): correct typo

---

src/cascader/README.md
src/divider/README.md
src/drawer/README.md
src/grid/README.md
src/search/README.md
src/side-bar/README.md
src/swiper/README.md

无
无
- docs: 移除文档中不齐全的 CSS Varibles 相关信息

docs: remove something about custom theme

---

src/link/link.wxml

fix #1261 
- fix(link): 无障碍时icon单独读取问题. (#1261)
https://codesign.qq.com/s/JMwy0bmOYA9O6LB

fix(link): 无障碍时icon单独读取问题. (#1261)

---

src/avatar/avatar-group.wxml
src/cascader/cascader.wxml
src/image-viewer/image-viewer.wxml
src/input/input.wxml
src/link/link.wxml
src/message/message.wxml
src/notice-bar/notice-bar.wxml
src/popup/popup.wxml
src/upload/upload.wxml

无
使用正确的插槽名称，保持和文档一致，使用 kebab-case 而不是 camel case
- break: 全局修正插槽名称，保持和文档一致，使用 kebab-case

fix: using correct slot name

---

src/notice-bar/__test__/__snapshots__/index.test.js.snap
src/notice-bar/_example/customization/index.wxss
src/notice-bar/notice-bar.less
src/notice-bar/notice-bar.ts
src/notice-bar/notice-bar.wxml

#1244 
- fix(NoticeBar): 修复右侧额外信息行高不正确问题

fix(NoticeBar): fix some style problem

---

src/common/utils.ts
src/message/_example/base/index.js
src/message/message.less
src/message/message.ts
src/message/message.wxml

#1245 
- fix(Message): 修复间距、颜色样式错误问题

fix(Message): fix some style problem

---

src/avatar/avatar-group.ts
src/checkbox-group/checkbox-group.ts
src/checkbox/checkbox.ts
src/collapse/collapse.ts
src/common/src/instantiationDecorator.ts
src/dropdown-menu/dropdown-menu.ts
src/grid/grid.ts
src/picker/picker.ts
src/radio-group/radio-group.ts
src/radio/radio.ts
src/side-bar/side-bar.ts
src/steps/step-item.ts
src/steps/steps.ts
src/swiper/swiper-nav.ts
src/tab-bar/tab-bar.ts

无
使用底层逻辑获取组件间的关系，不需要另外调用 getRelationNodes 获取

refactor: using relation from core code

---

src/date-time-picker/_example/time/index.js
src/date-time-picker/_example/year-month-date/index.js
src/date-time-picker/_example/year-month/index.js
src/picker/_example/base/index.js
src/picker/_example/with-title/index.js

chore: remove optional chain on demo

---

src/empty/README.md
src/fab/README.md
src/indexes/README.md
src/notice-bar/README.md
src/progress/README.md
src/steps/README.md
src/steps/__test__/__snapshots__/demo.test.js.snap
src/steps/_example/special/index.wxml

chore: update website readme

---

src/action-sheet/README.md
src/calendar/README.md
src/cascader/README.md
src/collapse/README.md
src/drawer/README.md
src/dropdown-menu/README.md
src/fab/README.md
src/image-viewer/README.md
src/indexes/README.md
src/link/README.md
src/notice-bar/README.md
src/overlay/README.md
src/popup/README.md
src/progress/README.md
src/result/README.md
src/side-bar/README.md
src/textarea/README.md
src/tree-select/README.md

|组件 | 版本|
|  ----  | ----  |
| link | 0.32.0 |
| tree-select | 0.32.0|
| indexes-anchor | 0.32.0 | 
| side-bar | 0.25.0 | 
| cascader | 0.23.0 | 
| calendar | 0.22.0 | 
| result | 0.16.0 | 
| image-viewer | 0.10.0 | 
| overlay | 0.10.0 | 
| notice-bar | 0.9.0 | 
| action-sheet | 0.9.0|
| dropdown-menu | 0.8.0 | 
| collapse | 0.7.3 | 
| progress | 0.7.3 | 
| drawer | 0.7.2 | 
| fab | 0.7.2 | 
- docs: 补齐版本信息

docs: add version information

---

src/cell-group/cell-group.wxml
src/cell/__test__/__snapshots__/index.test.js.snap
src/cell/cell.wxml
src/collapse/__test__/__snapshots__/index.test.js.snap
src/indexes/__test__/__snapshots__/demo.test.js.snap
src/indexes/_example/base/index.wxml
src/indexes/indexes.less
src/indexes/indexes.wxml

re #1058
fix https://github.com/Tencent/tdesign-miniprogram/issues/1058
- feat(Indexes): 支持无障碍访问
Android:
https://user-images.githubusercontent.com/17818509/208077189-f689adc6-22a6-4af8-ae47-1542236a4ed3.mp4
iOS：
https://user-images.githubusercontent.com/17818509/208077228-92833b79-6bd9-4b09-8856-ea80db3482df.mp4

feat(indexes): 读屏优化

---

example/components/pull-down-list/index.wxml
example/pages/home/home.wxml

#1065
- 相关元素增加 aria-* 属性
- feat(example): 增加 a11y 支持
iOS:
https://user-images.githubusercontent.com/5051221/209783136-7be0f9ad-c979-4f60-a69f-cae968650401.mp4
Android:
https://user-images.githubusercontent.com/5051221/209783158-03a68b32-3571-47a9-8c73-4ec9860c097f.mp4

feat(example): add a11y support

---

src/swiper/_example/cards/index.wxss
src/swiper/swiper.less
src/swiper/swiper.wxml

fix #1315
修复视觉问题
- break(Swiper): 增加 `18rpx` 的圆角，并支持 CSS Variables，移除了图片的 shape

fix(swiper): update style

---

src/cascader/cascader.less
src/cascader/cascader.ts
src/cascader/cascader.wxml

fix #1322
修复视觉问题
增加特性自动定位到已选项
- fix(Cascader): 修复视觉问题
- feat(Cascader): 自动定位到已选的 radio 项

fix(cascader): update style

---

src/progress/__test__/__snapshots__/demo.test.js.snap
src/progress/_example/base/index.wxml
src/progress/_example/base/index.wxss
src/progress/_example/circle/index.wxml
src/progress/_example/circle/index.wxss
src/progress/_example/custom/index.wxml
src/progress/_example/custom/index.wxss
src/progress/_example/line/index.wxml
src/progress/_example/line/index.wxss
src/progress/_example/plump/index.wxml
src/progress/_example/plump/index.wxss
src/progress/_example/progress.less
src/progress/_example/progress.wxml
src/progress/_example/transition/index.wxml
src/progress/_example/transition/index.wxss
src/progress/progress.wxml

fix #1319 
- fix(Progress): 修复视觉问题

style(Progress): update style

---

site/docs/getting-started.md

docs: 文档 button 属性使用错误

---

src/tabs/__test__/__snapshots__/demo.test.js.snap
src/tabs/__test__/__snapshots__/index.test.js.snap
src/tabs/_example/base/index.wxml
src/tabs/_example/size/index.wxml
src/tabs/_example/size/index.wxss
src/tabs/_example/status/index.js
src/tabs/_example/status/index.wxml
src/tabs/_example/tabs.wxml
src/tabs/tabs.less
src/tabs/tabs.ts
src/tabs/tabs.wxml

fix #1312
修复视觉问题
修复定位问题
- fix(Tabs): 修复视觉问题
- fix(Tabs): 修复激活项定位的问题

fix(tabs): update style

---

src/steps/__test__/__snapshots__/demo.test.js.snap
src/steps/_example/vertical/index.wxml
src/steps/step-item.less

fix #1309
修复垂直样式不对齐的问题
- fix(Steps): 修复垂直样式不对齐的问题

fix(steps): update style

---

src/stepper/__test__/__snapshots__/demo.test.js.snap
src/stepper/__test__/__snapshots__/index.test.js.snap
src/stepper/__test__/index.test.js
src/stepper/_example/base/index.wxml
src/stepper/_example/min-max/index.wxml
src/stepper/_example/min-max/index.wxss
src/stepper/_example/size/index.wxml
src/stepper/_example/size/index.wxss
src/stepper/_example/theme/index.wxml
src/stepper/_example/theme/index.wxss
src/stepper/stepper.less
src/stepper/stepper.wxml

fix #1337 
- fix(Stepper): 修复组件视觉错误

fix(Stepper): update style

---

src/common/utils.ts
src/tag/README.en-US.md
src/tag/README.md
src/tag/__test__/__snapshots__/demo.test.js.snap
src/tag/__test__/index.test.js
src/tag/_example/checkable/index.wxml
src/tag/_example/checkable/index.wxss
src/tag/_example/closable/index.wxml
src/tag/_example/closable/index.wxss
src/tag/_example/tag.less
src/tag/_example/tag.wxml
src/tag/check-tag-props.ts
src/tag/check-tag.ts
src/tag/check-tag.wxml
src/tag/props.ts
src/tag/tag.ts
src/tag/tag.wxml
src/tag/type.ts

fix #1308
- feat(tag): 属性 icon 支持对象，透传至 icon 组件
- fix(CheckTag): 修复非受控用法
- feat(CheckTag): 属性 content 支持数组类型，用于显示已选/未选文案
- fix(CheckTag): 修复 content 不可用的问题

fix(tag): resolve icon and control

---

src/drawer/__test__/__snapshots__/demo.test.js.snap
src/drawer/_example/footer/index.js
src/drawer/drawer.less

fix #1304
无
- fix(Drawer): 修复样式问题

fix(drawer): update style

---

src/dialog/__test__/__snapshots__/demo.test.js.snap
src/dialog/_example/with-image/index.wxml

fix(dialog): replace url

---

src/common/utils.ts
src/dropdown-menu/dropdown-item.ts
src/dropdown-menu/dropdown-item.wxml
src/dropdown-menu/dropdown-menu.less

fix #1345 
修复重置逻辑，调整字体大小
- fix(DropdownMenu): 修复重置逻辑，调整字体大小

fix(dropdown-menu): update reset logic and style

---

src/switch/__test__/__snapshots__/index.test.js.snap
src/switch/switch.less
src/switch/switch.wxml

fix #1018 
- fix(Switch): 支持无障碍访问
【腾讯 CoDesign】TD-微信小程序-Switch-iOS-...
https://codesign.qq.com/s/zm5q0XQOLdZRBb6

fix(switch): 开关无障碍旁白补充

---

src/switch/__test__/__snapshots__/demo.test.js.snap
src/switch/_example/base/index.wxml
src/switch/_example/color/index.wxml
src/switch/_example/label/index.wxml
src/switch/_example/size/index.wxml
src/switch/_example/status/index.wxml

chore(switch): update demo

---

src/tab-bar/__test__/__snapshots__/demo.test.js.snap
src/tab-bar/_example/base/index.js
src/tab-bar/_example/custom/index.wxss
src/tab-bar/_example/sub/index.js
src/tab-bar/_example/text-only/index.js
src/tab-bar/tab-bar-item.less

fix #1311
修复视觉问题，以及更新示例
- fix(TabBar): 修复视觉问题

fix(tab-bar): update style

---

src/checkbox/checkbox.less

fix #1323 
无
- fix(Checkbox): 修复水平布局时垂直居中的问题

fix(checkbox): update style

---

src/search/__test__/__snapshots__/demo.test.js.snap
src/search/_example/base/index.wxml
src/search/_example/search.wxml
src/search/_example/status/index.js
src/search/_example/status/index.wxml
src/search/_example/status/index.wxss

fix(search): update demo

---

src/navbar/__test__/__snapshots__/demo.test.js.snap
src/navbar/__test__/__snapshots__/index.test.js.snap
src/navbar/_example/img/index.js
src/navbar/_example/img/index.wxss
src/navbar/navbar.less
src/navbar/navbar.ts
src/navbar/navbar.wxml

fix #1299
无
- fix(NavBar): 修复视觉问题
- break(NavBar): 胶囊相关 CSS Variables 命名变更

fix(navbar): update style

---

src/navbar/__test__/__snapshots__/index.test.js.snap
src/navbar/navbar.ts
src/navbar/navbar.wxml

fix #1296
无
- fix(Navbar): 修复 custom-style 属性的响应式问题

fix(navbar): make the custom-style property reactive

---

site/plugin-tdoc/component.vue

chore: 调整miniprogram-live 预览环境

---

src/link/__test__/__snapshots__/demo.test.js.snap
src/link/_example/content/index.wxml

fix #1343 
- fix(Link): 更新示例demo

fix(Link): update demo

---

src/textarea/__test__/__snapshots__/demo.test.js.snap
src/textarea/__test__/demo.test.js
src/textarea/_example/autosize/index.wxml
src/textarea/_example/card/index.js
src/textarea/_example/card/index.json
src/textarea/_example/card/index.wxml
src/textarea/_example/card/index.wxss
src/textarea/_example/custom/index.wxml
src/textarea/_example/custom/index.wxss
src/textarea/_example/disabled/index.wxml
src/textarea/_example/maxcharacter/index.wxml
src/textarea/_example/maxlength/index.wxml
src/textarea/_example/textarea.json
src/textarea/_example/textarea.wxml

fix #1341 
说明： 由于原生Textarea 组件不支持自定义 placeholder 行高，已和设计沟通，Textarea 组件暂不实现横排布局
- fix(Textarea): 更新示例demo

fix(Textarea): update demo

---

src/swiper/README.en-US.md
src/swiper/README.md
src/swiper/__test__/__snapshots__/demo.test.js.snap
src/swiper/__test__/index.test.js
src/swiper/_example/custom/index.wxml
src/swiper/props.ts
src/swiper/swiper-nav.ts
src/swiper/swiper-nav.wxml
src/swiper/swiper.ts
src/swiper/swiper.wxml
src/swiper/type.ts

无
无
- feat(Swiper): 属性 navigation 支持 boolean，默认值为 true
- feat(SwiperNav): 新增属性用于单独控制

fix(swiper): update api

---

example/app.json
src/side-bar-item/side-bar-item.less
src/side-bar/__test__/__snapshots__/demo.test.js.snap
src/side-bar/__test__/demo.test.js
src/side-bar/_example/base/index.wxss
src/side-bar/_example/custom/index.js
src/side-bar/_example/custom/index.json
src/side-bar/_example/custom/index.wxml
src/side-bar/_example/custom/index.wxss
src/side-bar/_example/side-bar.wxml
src/side-bar/_example/switch/index.js

fix #1305 
无
- fix(SideBar): 支持选项标题换行

fix(side-bar): update style

---

src/tree-select/_example/normal/index.js
src/tree-select/tree-select.less
src/tree-select/tree-select.wxml

fix #1348
无
- fix(TreeSelect): 修复视觉问题

fix(tree-select): update style

---

src/indexes-anchor/indexes-anchor.less
src/indexes-anchor/indexes-anchor.wxml
src/indexes/README.md
src/indexes/__test__/__snapshots__/demo.test.js.snap
src/indexes/_example/base/index.js
src/indexes/_example/base/index.wxml
src/indexes/_example/custom/index.js
src/indexes/_example/custom/index.wxml
src/indexes/_example/custom/index.wxss
src/indexes/indexes.less
src/indexes/indexes.ts

fix #1344
无
- feat(Indexes): 增加 change 事件
- feat(Indexes): 修复视觉问题

fix(indexes): update style

---

src/collapse/__test__/__snapshots__/demo.test.js.snap
src/collapse/_example/accordion/index.wxml
src/collapse/_example/collapse.wxml
src/collapse/_example/theme/index.wxml

fix(collapse): update demo

---

src/image/__test__/__snapshots__/demo.test.js.snap
src/image/_example/image.wxml
src/image/_example/status/index.wxml

fix(image): update demo

---

src/checkbox/checkbox.wxml
src/radio/radio.wxml

#1023
#1026 
修复 a11y 的点击事件
- fix(Radio): 修复 a11y 的点击事件
- fix(Checkbox): 修复 a11y 的点击事件

fix(radio): resolve click for a11y

---

src/swiper/README.md
src/swiper/__test__/__snapshots__/demo.test.js.snap
src/swiper/__test__/__snapshots__/index.test.js.snap
src/swiper/_example/base/index.js
src/swiper/_example/base/index.wxml
src/swiper/swiper.ts
src/swiper/swiper.wxml

fix #1373
增加点击事件
- feat(Swiper): 增加 click 事件

feat(swiper): add click event

---

src/back-top/back-top.ts
src/pull-down-refresh/__test__/__snapshots__/demo.test.js.snap
src/pull-down-refresh/_example/base/index.js
src/pull-down-refresh/_example/base/index.json
src/pull-down-refresh/_example/base/index.wxml
src/pull-down-refresh/pull-down-refresh.ts
src/pull-down-refresh/pull-down-refresh.wxml

fix #1389 
无
- feat(PullDownRefresh): 新增 scroll 事件
- feat(BackTop): 放置 pull-down-refresh 内部时，将会滚动该容器到顶部

feat(pulldown-refresh): add scroll event

---

src/action-sheet/action-sheet.less

fix #1421 
- fix(ActionSheet): 移除 focus 样式

fix(action-sheet): tabindex 元素去掉outline. (#1421)

---

src/toast/toast.ts
src/toast/toast.wxml

fix #1243 
无
- fix(Toast): 禁止 toast 区域滑动

fix(toast): prevent scroll on toast area

---

src/dialog/_example/base/index.wxss
src/dialog/_example/dialog.wxml

fix(dialog): update demo

---

src/icon/icon.ts

fix #1426
无
- fix(Icon): 移除无效的 behaviors

fix(icon): remove invalid behaviors

---

src/tabs/__test__/__snapshots__/demo.test.js.snap
src/tabs/_example/with-content/index.wxml

fix(tabs): update demo

---

src/common/bus.ts
src/slider/__test__/index.test.js
src/slider/slider.ts
src/slider/slider.wxml

fix #1338
无
- fix(Slider): 优化刻度样式，以及默认风格时滑动的距离

fix(slider): resolve default style

---

src/collapse/collapse-panel.ts
src/dropdown-menu/dropdown-item.ts
src/image/image.ts
src/rate/rate.ts

fix: using uniform get rect function

---

src/collapse/__test__/__snapshots__/index.test.js.snap
src/collapse/collapse-panel.less
src/collapse/collapse-panel.ts
src/collapse/collapse-panel.wxml
src/collapse/collapse.ts

fix #1375
使用 animation 来展开收起，避免在 android 上有延迟。
- fix(Collapse): 修复在 Android 下部分机型收起延迟的问题

refactor(collapse): using animation to expand

---

src/swipe-cell/_example/swipe-cell.json
src/swipe-cell/_example/swipe-cell.less
src/swipe-cell/swipe-cell.ts

fix #1393 
- fix(SwipeCell): 修复滑动距离计算错误

fix(SwipeCell): fix swipe distance calculation error

---

src/grid/__test__/__snapshots__/demo.test.js.snap
src/grid/_example/badge/index.js
src/grid/_example/badge/index.wxml
src/grid/_example/base/index.js
src/grid/_example/base/index.wxml
src/grid/_example/border/index.js
src/grid/_example/border/index.wxml
src/grid/_example/card/index.js
src/grid/_example/card/index.wxml
src/grid/_example/description/index.js
src/grid/_example/description/index.wxml
src/grid/_example/grid.wxml
src/grid/_example/icon-grid/index.js
src/grid/_example/multiple/index.js
src/grid/_example/multiple/index.wxml
src/grid/_example/scroll/index.js
src/grid/_example/scroll/index.wxml
src/result/__test__/__snapshots__/demo.test.js.snap
src/result/_example/custom/index.wxml

fix #1396 
- fix(Grid): 更新占位图片

fix(Grid): update demo

---

src/checkbox-group/checkbox-group.ts
src/checkbox-group/props.ts
src/checkbox-group/type.ts
src/checkbox/README.en-US.md
src/checkbox/README.md
src/checkbox/props.ts
src/checkbox/type.ts

无
checkbox group 使用单独的 props.js 文件。

Fix/checkbox group/props

---

example/app.json
src/badge/_example/theme/index.json
src/calendar/_example/base/index.json
src/calendar/_example/custom-button/index.json
src/calendar/_example/custom-range/index.json
src/calendar/_example/custom-text/index.json
src/calendar/_example/multiple/index.json
src/calendar/_example/range/index.json

fix: update using component

---

src/collapse-panel/collapse-panel.less
src/collapse-panel/collapse-panel.ts
src/collapse/__test__/__snapshots__/index.test.js.snap

无
当 panel 内容为动态内容时，支持展开
- fix(Collapse): 当 panel 内容为动态内容时，支持展开

fix(collapse): enables nested use

---

src/cell/cell.less
src/switch/_example/base/index.wxss
src/switch/_example/switch.less
src/switch/_example/switch.wxml

fix #1340
- feat(Cell): 新增 CSS Varialbes 用于控制高度

feat(cell): support custom height

---

src/action-sheet/_example/action-sheet.wxml
src/action-sheet/action-sheet.less
src/action-sheet/action-sheet.wxml
src/toast/_example/close/index.json
src/toast/_example/cover/index.json
src/toast/_example/display/index.json
src/upload/_example/upload.less
src/upload/_example/upload.wxml

fix #1342
fix #1346 
fix #1243 

fix: some demo

---

src/indexes/README.en-US.md
src/indexes/README.md
src/indexes/__test__/__snapshots__/demo.test.js.snap
src/indexes/_example/custom/index.wxml
src/indexes/_example/custom/index.wxss
src/indexes/_example/indexes.wxml
src/indexes/indexes.ts
src/indexes/props.ts
src/indexes/type.ts

fix #1344
fix #1478
支持新属性，stickyOffset
- feat(Indexes): 新增支持 stickyOffset 属性，用于调整吸顶时的距离

feat(indexes): support sticky-offset

---

src/stepper/__test__/index.test.js
src/stepper/stepper.less
src/stepper/stepper.wxml

fix #1337 补充问题
- fix(Stepper): 修复 `theme='normal'`时禁用态视觉错误

fix(Stepper): fix disabled state style error

---

src/rate/__test__/__snapshots__/demo.test.js.snap
src/rate/_example/action/index.wxml
src/rate/_example/rate.wxml
src/rate/rate.less
src/rate/rate.ts
src/rate/rate.wxml
src/rate/rate.wxs

fix #1334
无
- fix(Rate): 修复半选时 tips 的图标

fix(rate): optimize detail

---

src/collapse-panel/collapse-panel.less
src/collapse-panel/collapse-panel.wxml
src/collapse/__test__/__snapshots__/index.test.js.snap

无
当 Collapse 收起时，隐藏 header 的边框
- fix(Collapse):  面板收起时，隐藏 header 的边框

fix(collapse): remove header border when retracted

---

src/cascader/cascader.ts

fix #1500
multipleSlot没开启导致插槽无法使用
- fix(Cascader): 修复 slot 无法使用的问题

fix(cascader): enable multiple slot

---

src/icon/README.md
src/image/README.md
src/result/README.md

docs: add faq for image

---

src/dialog/__test__/__snapshots__/demo.test.js.snap
src/dialog/_example/with-input/index.json
src/dialog/_example/with-input/index.wxml
src/dialog/_example/with-input/index.wxss
src/dialog/dialog.less
src/input/__test__/__snapshots__/index.test.js.snap
src/input/__test__/index.test.js
src/input/input.less
src/input/input.ts
src/input/input.wxml

fix #1442
移除内置的 input 样式，优化 input 的结构
- break(Dialog): 移除内置的 input 样式
- break(Input): 优化 DOM，移除外置的 wapper 元素

fix(dialog): remove built-in input style

---

src/cell/__test__/__snapshots__/demo.test.js.snap
src/cell/_example/base/index.wxml
src/cell/_example/multiple/index.wxml
src/cell/_example/theme/index.wxml
src/cell/cell.less

修改说明： 拆分 title、required、leftIcon、rightIcon 属性对应的 font-size 和 color 变量，其中 leftIcon 内置颜色取 `@brand-color`
- feat(Cell): 补充 CSS Variables

feat(Cell): enrich CSS Variables

---

src/link/link.wxml
src/notice-bar/__test__/__snapshots__/demo.test.js.snap
src/notice-bar/_example/customization/index.js
src/notice-bar/_example/customization/index.json
src/notice-bar/_example/customization/index.wxml
src/notice-bar/_example/event/index.js
src/notice-bar/_example/event/index.json
src/notice-bar/_example/event/index.wxml
src/notice-bar/_example/notice-bar.json
src/notice-bar/_example/notice-bar.wxml
src/notice-bar/_example/suffixIcon/index.js
src/notice-bar/_example/suffixIcon/index.json
src/notice-bar/_example/suffixIcon/index.wxml

feat(NoticeBar): update demo

---

src/swiper/swiper.ts
src/swiper/swiper.wxml
src/tabs/_example/tabs.json
src/tabs/_example/tabs.wxml

fix #1391 
- fix(Swiper): 修复 `autoplay` 状态下，`swiper` 偶现左右抖动问题

fix(Swiper): fix swiper-item switching error when autoplay state

---

src/navbar/navbar.less

无
当使用 navbar 时，根元素没有高度，高度无法正常使用 flex 布局
- fix(NavBar): 补充根元素缺失的高度

fix(navbar): add height for root element

---

example/project.config.json
src/search/README.md
src/search/search.wxml

fix #1527 
- fix(Search):  修复插槽命名错误

fix(Search): fix slot name error

---

src/image-viewer/image-viewer.less
src/image-viewer/image-viewer.ts
src/image-viewer/image-viewer.wxml

- fix(ImageViewer): 优化插槽渲染逻辑，不再需要传入 slot 字符串
- fix(ImageViewer): 修复关闭点击不生效的问题，以及 trigger 参数不对的问题

fix(image-viewer): update slot render logic & event params

---

src/image-viewer/README.md
src/image/README.md

docs(image): update api for slot

---

src/calendar/calendar.less

fix #1537 
参考文档：[tabindex控制焦点](https://web.dev/i18n/zh/control-focus-with-tabindex/#%E6%A3%80%E6%9F%A5%E6%82%A8%E7%9A%84%E6%8E%A7%E4%BB%B6%E6%98%AF%E5%90%A6%E5%8F%AF%E9%80%9A%E8%BF%87%E9%94%AE%E7%9B%98%E8%AE%BF%E9%97%AE)
- fix(Calendar):  移除 `tabindex` 元素 的 `outline` 样式

fix(Calendar): remove the outline style of the tabindex element

---

src/input/input.wxml

- feat(Input): 支持名为 `tips` 的插槽

feat(Input): support for slots named tips

---

src/button/button.less

- fix(Button): 修复 CSS Variable 变量命名错误

fix(Button): fix css variable naming errors

---

site/docs/custom-style.md
site/site.config.mjs

docs: add custom-style

---

src/input/input.ts
src/notice-bar/__test__/__snapshots__/demo.test.js.snap
src/notice-bar/_example/customization/index.wxml
src/notice-bar/_example/iconDemo/index.wxml
src/radio/radio.ts
src/slider/slider.ts
src/step-item/step-item.wxml
src/textarea/textarea.ts
src/upload/upload.ts

fix: resolve console warnings

---

src/calendar/template.wxml

无
移除 title 插槽上的渲染条件
- fix(Calendar): 优化 title 插槽，不再需要传入 slot 字符串

fix(calendar): remove condition of title slot

---

.gitmodules
script/gulpfile.base.js

feat: add submodule

---

src/image/README.md
src/image/__test__/__snapshots__/demo.test.js.snap
src/image/_example/status/index.wxml
src/image/image.wxml

fix #1608
将插槽渲染逻辑改回之前，需要手动传入 slot 字符串
- fix(Image): 插槽的渲染需要传入对应 slot 的字符串

fix(image): update slot render logic

---

site/docs/overview.md
site/site.config.mjs

docs: update overview.md

---

src/tab-panel/tab-panel.ts

fix #1612 
无
- fix(Tabs): 修复属性不支持响应式变化的问题

fix(tabs): resolve property reactive problem

---

src/dropdown-item/dropdown-item.ts
src/dropdown-menu/README.en-US.md
src/dropdown-menu/README.md

#1603
新增 reset 事件
- feat(DropdownMenu): 新增 reset 事件

feat(dropdown-menu): add reset event

---

src/dialog/__test__/index.test.js
src/dialog/dialog.ts
src/swiper-nav/swiper-nav.ts
src/swiper/swiper.wxml
src/textarea/__test__/index.test.js
src/textarea/textarea.ts

无
修复事件名称，从驼峰写法改成连字符写法。符合文档
- fix(Dialog): 修复事件名，从 overlayClick 改成 overlay-click
- fix(SwiperNav): 修复事件名，从 navBtnChange 改成 nav-btn-change
- fix(TextArea): 修复事件名，从 lineChange改成 line-change

fix: resolve event name

---

src/fab/fab.wxml

无
修复 fab 丢失style 默认值的问题
- fix(Fab): 修复丢失style 默认值的问题

fix(fab): recover style default value

---

src/swipe-cell/README.md

- fix(SwipeCell): 修复`API` 文档显示错误

fix(SwipeCell): fix docs

---

src/dialog/dialog.less

- fix(Dialog): 修复文字按钮`hover`态圆角不正确

fix(Dialog): fix button style

---

src/switch/switch.less
src/switch/switch.wxml

- fix(Switch): 优化禁用态下 loading 的颜色

fix(switch): update loading color

---

src/cell/__test__/__snapshots__/index.test.js.snap
src/cell/__test__/__virtualHostSnapshot__/index.test.js.snap
src/cell/cell.less
src/cell/cell.wxml
src/collapse/__test__/__snapshots__/index.test.js.snap
src/collapse/__test__/__virtualHostSnapshot__/index.test.js.snap

chore(Cell): adjust className for hover-class

---

src/date-time-picker/README.md
src/date-time-picker/date-time-picker.wxml
src/date-time-picker/props.ts
src/date-time-picker/type.ts
src/picker/README.md
src/picker/picker.wxml

- break(Picker): 移除 `footer` 插槽
- break(DateTimePicker): 移除 `footer` 插槽

chore(Picker&&DateTimePicker): remove footer slot

---

src/radio-group/props.ts
src/radio-group/radio-group.wxml
src/radio-group/type.ts
src/radio/README.en-US.md
src/radio/README.md
src/radio/__test__/__snapshots__/demo.test.js.snap
src/radio/_example/align/index.wxml
src/radio/props.ts
src/radio/radio.ts
src/radio/radio.wxml
src/radio/type.ts

- break(Radio): 属性 align 更名为 placement
- break(RadioGroup): 属性 align 更名为 placement

chore(Radio): align attribute is renamed to placement

---

src/checkbox/README.en-US.md
src/checkbox/README.md
src/checkbox/checkbox.wxml
src/checkbox/props.ts
src/checkbox/type.ts

- break(Checkbox): `align` 属性更名为 `placement`

chore(Checkbox): align attribute is renamed to placement

---

src/search/README.md
src/search/__test__/__snapshots__/demo.test.js.snap
src/search/__test__/__virtualHostSnapshot__/demo.test.js.snap
src/search/__test__/index.test.js
src/search/_example/action/index.wxml
src/search/props.ts
src/search/search.less
src/search/search.ts
src/search/search.wxml
src/search/type.ts

- break(Search):  移除 `right-icon` 属性相关
- feat(Search): 新增 `clearable`，用于启用清除控件

chore(Search): remove the right-icon and add the clearable attribute

---

src/button/README.en-US.md
src/button/README.md
src/button/__test__/__snapshots__/demo.test.js.snap
src/button/_example/icon-btn/index.wxml
src/button/_example/shape/index.wxml
src/button/button.wxml
src/button/props.ts
src/button/type.ts

无
button 支持 suffix 插槽
- feat(Button): 新增支持 suffix 插槽

feat(button): support suffix slot

---

src/avatar-group/props.ts
src/avatar/README.md
src/avatar/__test__/__snapshots__/demo.test.js.snap
src/avatar/__test__/__snapshots__/index.test.js.snap
src/avatar/__test__/__virtualHostSnapshot__/demo.test.js.snap
src/avatar/__test__/__virtualHostSnapshot__/index.test.js.snap
src/avatar/_example/action/index.wxml
src/avatar/_example/exhibition/index.wxml
src/avatar/avatar.less
src/avatar/avatar.wxml
src/avatar/avatar.wxs

- break(Avatar): 移除 `bordered` 属性
- break(AvatarGroup): `cascading` 属性默认值变更为 `left-up`

chore(Avatar): remove bordered attribute

---

src/link/link.wxml
src/message/README.en-US.md
src/message/README.md
src/message/__test__/__snapshots__/index.test.js.snap
src/message/__test__/__virtualHostSnapshot__/index.test.js.snap
src/message/_example/base/index.js
src/message/message.json
src/message/message.less
src/message/message.ts
src/message/message.wxml
src/message/props.ts
src/message/type.ts

- break(Message): 移除 `action` 属性相关
- feat(Message): 新增 `link` 属性
- fix(Message): 修复主题图标不正确

chore(Message): remove action and add the link attribute

---

src/navbar/__test__/__snapshots__/demo.test.js.snap
src/navbar/_example/back-home/index.js
src/navbar/_example/back-home/index.wxml
src/navbar/navbar.less

fix #1622 
修复胶囊内部点击事件没反应的问题
- fix(NavBar): 修复胶囊内部点击事件没反应的问题

fix(navbar): resolve capsule event currectly

---

src/footer/README.en-US.md
src/footer/README.md
src/footer/__test__/__snapshots__/demo.test.js.snap
src/footer/__test__/__snapshots__/index.test.js.snap
src/footer/__test__/__virtualHostSnapshot__/demo.test.js.snap
src/footer/__test__/__virtualHostSnapshot__/index.test.js.snap
src/footer/_example/base/index.js
src/footer/_example/base/index.wxml
src/footer/_example/link/index.js
src/footer/_example/link/index.wxml
src/footer/_example/logo/index.wxml
src/footer/footer.less
src/footer/footer.wxml
src/footer/props.ts
src/footer/type.ts

- break(Footer): `copyright` 更名为 `text`
- break(Footer): `textLinkList` 更名为 `links`
- break(Footer):  移除 `theme` 属性

chore(Footer): copyright attribute is renamed to text

---

src/dialog/dialog.ts
src/dialog/index.ts

- fix(Dialog): 修复 confirm 的拼写错误

fix(dialog): resolve word misspelling

---

src/slider/slider.less
src/slider/slider.ts
src/slider/slider.wxml

fix #1402 
- fix(slider): 规范无障碍语义.
【腾讯 CoDesign】TD-微信小程序-Slider-iOS-...
https://codesign.qq.com/s/dqN2924xMvZaBXe

fix(slider): 规范无障碍语义.

---

src/toast/README.en-US.md
src/toast/README.md
src/toast/__test__/__snapshots__/demo.test.js.snap
src/toast/_example/theme/index.js
src/toast/_example/theme/index.wxml
src/toast/index.ts
src/toast/toast.ts
src/toast/type.ts

无
统一 API 命名
- fix(Toast): 属性 theme 的枚举值 fail 替换成 error

fix(toast): replace fail theme with error

---

site/docs/overview.md

fix #1650 
- fix: 修复组件预览文档中链接地址错误

fix: fix overview.md errors

---

src/cell/__test__/__snapshots__/index.test.js.snap
src/cell/cell.wxml
src/collapse-panel/collapse-panel.less
src/collapse/__test__/__snapshots__/index.test.js.snap

无
修复 collapse 在 disabled 状态下标题颜色错误的问题
- fix(Collapse): 修复 disabled 状态下标题颜色错误的问题
- fix(Cell): 修复外部样式类 t-class-title 放置位置错误的问题

fix(collapse): resolve disabled color

---

src/drawer/drawer.less
src/drawer/drawer.wxml

- feat(Drawer): 补充 `hover` 态样式

feat(Drawer): add hover style

---

src/tag/tag.wxml

fix #1668 
- fix(Tag): 修复 `close` 与 `click` 事件一并触发的问题

fix(Tag): use catch to bind events

---

src/rate/README.md
src/rate/__test__/__snapshots__/demo.test.js.snap
src/rate/_example/action/index.wxml
src/rate/_example/base/index.wxml
src/rate/_example/color/index.wxml
src/rate/_example/count/index.wxml
src/rate/_example/show-text/index.wxml
src/rate/_example/size/index.wxml
src/rate/_example/un-filled/index.wxml
src/rate/props.ts
src/rate/rate.ts
src/rate/rate.wxml
src/rate/rate.wxs
src/rate/type.ts

无
移除 variant 属性，完全依赖 icon 属性来控制图标
修复 tips 偶尔会不消失的问题
- fix(Rate): 修复 tips 偶尔会不消失的问题
- break(Rate): 移除 variant 属性，完全依赖 icon 属性来控制图标

fix(rate): remove variant property and update tips disapper logic

---

src/back-top/_example/back-top.ts
src/back-top/back-top.ts

- fix(BackTop): 修复 `icon` 不显示问题

fix(BackTop): fix icon

---

src/picker/__test__/__snapshots__/demo.test.js.snap
src/picker/__test__/__virtualHostSnapshot__/demo.test.js.snap
src/picker/_example/with-title/index.js
src/picker/_example/with-title/index.wxml

fix(Picker): update demo
